### PR TITLE
Add current item in the breadcrumb in navigation

### LINKED ISSUE #1650: Add current item in the breadcrumb in navigation

### LINKED ISSUE #1699: Breadcrumb is not reactive when navigating to same route
## Reproduce

1. Go to the Record Page for one author.
1. Observe the breadcrumb displaying "Authors".
1. Within the list of publications, click on the Record Page link for a Publishers record.
1. Expect the breadcrumb to display "Publishers".
1. Instead, observe the breadcrumb to still display "Authors".

### PR DESCRIPTION
**Pull request by seancolsen**
Related to #1699
Related to #1650

Replaces #1693

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by pavish — CHANGES_REQUESTED** [review]
@seancolsen 

This is a general review comment. When the current item is added to the breadcrumb, there should not be an arrow after it.

Screenshot 2022-09-20 at 2 49 54 AM

Notice in the above screenshot, that the arrow with search icon makes it seem like the public schema is within a public schema.

If breadcrumb search is a concern, we would generally not need it in such scenarios since the pages would contain all links needed. Eg., Schema page will contain all the tables & explorations.

Since this is a UX concern, I'm looping in @kgodey and @ghislaineguerin.

**Comment by seancolsen** [comment]
> When the current item is added to the breadcrumb, there should not be an arrow after it.

Ok. That's unfortunately not an easy change to make. The breadcrumb system is already hacky, and the design change you're proposing adds even more complexity. I'm okay with going that direction, but before I do I want to make doubly sure that's actually the design we want.

Consider the Table Page. Its breadcrumb entry has a Record Selector button after it, like so:

image

And when the user is on the Record Page, we use that Record Selector button to separate the Table Page link from the Record Page link, like so:

image

Do we want to keep that behavior, or change it somehow?


Given that this breadcrumb design was a sticking point in the initial design phase and we've already gone back and forth on a bit, I wonder if it would be worth producing another round of mockups like I originally produced [here](https://gist.github.com/seancolsen/d3c42a14ba6c860af6e576205e5092d2#navigation-via-the-site-header) which show the site header and the page title _for every page on the site_. That way all of us can review the entire navigation/breadcrumb design more comprehensively before I go down the road of adding that additional to remove the breadcrumb separator for some specific pages.

Also I'm open to any ideas which propose more drastic changes to the navigation design.

**Comment by kgodey** [comment]
> I wonder if it would be worth producing another round of mockups like I originally produced [here](https://gist.github.com/seancolsen/d3c42a14ba6c860af6e576205e5092d2#navigation-via-the-site-header) which show the site header and the page title _for every page on the site_. 

This is the expected outcome of #1658. I don't think we should make any more changes to navigation until we have the new designs from #1658.

**Review by pavish — APPROVED** [review]

**Comment by pavish** [comment]
@seancolsen @kgodey I'll update #1658 with the concerns. The PR looks good otherwise. I've leave it to @rajatvijay to review and merge since he's assigned to it.

I've approved the PR because I requested changes earlier.

**Comment by seancolsen** [comment]
I've marked this as a draft because I've discovered another finicky bug with the breadcrumb reactivity

1. Navigate to the record page for one Authors record.
2. Open the breadcrumb selector to see a list of tables within the Library Management schema.
3. Hover "Publications".
4. Click the record selector button for Publications.
5. Click on a Publications record to navigate to a Publications record page.
6. Observe a breadcrumb that has too many entries in it

    image

Ugh.

I already spent a few hours yesterday toiling with this imperative logic in the breadcrumb component, and I mentioned [here](https://github.com/centerofci/mathesar/pull/1693#issuecomment-1251421282) that I'm still not happy with it. This latest bug might tip the scale towards spending the time to form a more-robust, less-hacky solution where we can declaratively derive the breadcrumb components from the route. Given that it may now take a non-trivial amount of additional time to properly address #1650 and #1699, I'm inclined to put this work on hold until #1658 is completed.

**Comment by pavish** [comment]
@seancolsen I think it's best to merge this PR in. The route changes (adding a RecordPageRoute), and the file structure changes (moving from system to components) are good enough for a merge. The more bugs we encounter with such reactivity issues, we'd be more informed when implementing the declarative route based breadcrumb.

Let's keep the issues open and merge this in. We can add all the reactivity related bugs to #1699.

**Comment by seancolsen** [comment]
@pavish Ok I squished the most recent bug with the breadcrumb. There are now no breadcrumb bugs of which I'm aware. Coincidentally, I also wanted to base some work on top of this PR. I've gone ahead and enabled auto-merge. @rajatvijay I welcome any retroactive review you're inclined to give this PR.

**Pull request merged**
