### PR TITLE
Reflect only correct table for column index

### LINKED ISSUE #663: IndexError when deleting a column
## Description

An indexError occurs when deleting a column through the API. Most of the time the error occurs when deleting the first or second column of a table. Deleting the last columns in a table does not seem to produce this error. 

## Expected behavior

- A column should be deleted

## To Reproduce

1. Delete the first  or second column of a table via API. Example: api/v0/tables/1/columns/1/
2. Delete the first or second column of another table via API. Example: api/v0/tables/2/columns/0/

## Screenshots

Screenshot (35)
Screenshot (36)

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #663 

When reflecting the index of a column, we now check the table OID when finding deleted columns.  Otherwise, we think any column deleted anywhere in the DB (with a smaller index than the column being reflected) should affect the index of the current column.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mr-gabe49** [comment]
Thanks @mathemancer, It works!

**Comment by mathemancer** [comment]
> I apologize @mathemancer. I'm still encountering the same error after merging the latest master. I had previously hardcoded your changes into my `columnDelete` branch and had no problems then.

 Can you be more precise?  I'm not sure what you mean.  This PR isn't yet merged into master, so the fix isn't available there.

**Comment by mr-gabe49** [comment]
> > I apologize @mathemancer. I'm still encountering the same error after merging the latest master. I had previously hardcoded your changes into my `columnDelete` branch and had no problems then.
> 
> Can you be more precise? I'm not sure what you mean. This PR isn't yet merged into master, so the fix isn't available there.

@mathemancer Oh yeah you're right. It works. I don't know what I was thinking.

**Review by eito-fis — APPROVED** [review]
Looks good to me!

**Review by pavish — APPROVED** [review]
Looks good to me!

**Pull request merged**
