### PR TITLE
Minor fixes for `install.sh`

### LINKED ISSUE #2576: Installation issues when running on mac (silicon)
## Description
I'm facing these issues while trying to install using the latest `install.sh` script from master. I'm running 'macOS Big Sur', on a mac with Apple M1 processor.

1. Error thrown, while the line `sudo docker compose --profile prod up -d --wait` runs in the install script. Any command with `sudo docker` throws an error.

   ```
    2023/02/25 23:34:45 must use ASL logging (which requires CGO) if running as root
    2023/02/25 23:34:45 must use ASL logging (which requires CGO) if running as root
    2023/02/25 23:34:45 must use ASL logging (which requires CGO) if running as root
    2023/02/25 23:34:45 must use ASL logging (which requires CGO) if running as root
    [+] Running 0/0
    ⠋ watchtower Pulling                                                                                                                   0.1s
    ⠋ db Pulling                                                                                                                           0.1s
    ⠋ caddy-reverse-proxy Pulling                                                                                                          0.1s
    ⠋ service Pulling                                                                                                                      0.1s
    error getting credentials - err: exit status 1, out: ``
   ``` 
    This is because docker cannot run as root (or with sudo privileges) in mac.
    If possible, we should avoid `sudo` generally, while running on a mac.

2. The images don't run after downloading because the platforms do not match.
    ```
    ⠙ caddy-reverse-proxy The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
    ⠿ Container mathesar_service                                                                                                                                         Waiting 19.1s
    ⠏ service The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested              0.0s
    container for service "service" exited (3)
    ```
    We should be publishing an arm image along with the existing amd image. I sent a mail regarding this.

3. Installation fails because wget is not installed by default. We need to check if it is present during installation.

4. Startup (i.e. `docker compose --profile prod up -d --wait`) fails because `SECRET_KEY` in `.env` file is empty.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #2576 
Related to #2572 

This PR:

- removes `wget` call (using `curl` instead)
- Avoids using `sudo` for docker commands on macOS (or any `darwin` system)
- Removes `-w 0` flag from `base64` call.
- Adds a timeout restriction for database connections, so service _fails_ when failing to connect to the DB.
  - This is okay since we are using the healthcheck on the internal DB as a prereq for the service
- Prints the `docker compose` logs whenever bringing up the system fails.

**Technical details**

The `-w 0` command is only relevant for us if the default wrapping line length on the user's `base64` command is set greater than 50. I googled around a bit, and only found 72 as the default.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@pavish You'll still need to build/push an image based on this (I think). It's taking forever on my machine for the arm64 part.

**Comment by mathemancer** [comment]
Another note: @kgodey I decided to defer the full docs for recovery on failure till a future PR. I think it makes sense to give them the logs, and let them look in our troubleshooting section or ask us for help based on what they see there.

My reasoning is that "connection didn't work" is pretty non-specific, and may not be enough info. Also, there are a number of reasons the service start-up could fail, and this will give them feedback on all such problems.

**Review by kgodey — APPROVED** [review]
Approved on my end, but I haven't tested it. @pavish please test and merge.

**Review by pavish — APPROVED** [review]
Looks great!

I tested installation with the install script and it works like a charm!

**Pull request merged**
