### PR TITLE
added docker compose

### LINKED ISSUE #2726: Update `docker-compose` to `docker compose` in documentation
## Description

using 
```
docker-compose --profile dev up
```
doesn't work.
using 
```
docker compose --profile dev up
```
Works

## Expected behavior

I expected it to set up and give the localhost link for me to access mathesar locally

## To Reproduce

```
cp .env.example .env
```
use this after
```
docker-compose --profile dev up
```
during set up

## Environment
 - OS: Ubuntu 
 - Browser: Firefox

## Additional context

image

### PR DESCRIPTION
**Pull request by smruthi49**
Fixes #2726 

added the docker set up code which creates container 
modified the docs from
```
docker-compose --profile dev up
```
to
```
docker compose --profile dev up
```

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by rajatvijay** [comment]
@smruthi49 please use the PR template. I see the checklist is missing.

**Comment by rajatvijay** [comment]
@smruthi49 here it is



Fixes #[issue number]



**Technical details**


**Screenshots**


## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin


<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>



PS: You can always get this by trying to open a new PR and copy the description before actually opening it.

**Comment by kgodey** [comment]
The PR template lives here https://github.com/centerofci/mathesar/blob/develop/.github/PULL_REQUEST_TEMPLATE

**Comment by smruthi49** [comment]
thankyou @rajatvijay and @kgodey 
I have now updated. I hope it follows the template now.
Let me know if there are any changes

**Comment by rajatvijay** [comment]
@smruthi49 I have re-run the checks now

**Comment by smruthi49** [comment]
@rajatvijay , can you re run again and check?

**Comment by rajatvijay** [comment]
@smruthi49 the "Lint Python Code" check is still failing. 

Reason: 

> ./demo/__init__.py:1:44: W292 no newline at end of file

**Comment by smruthi49** [comment]
@rajatvijay i have added new line at the end of file, please check if that works now.

**Comment by smruthi49** [comment]
@rajatvijay , It passed all checks. 
What does it mean by "This pull request may be merged without approvals."

**Comment by rajatvijay** [comment]
@smruthi49 You are seeing that message because approvals are not mandatory for the core team. 

Anyways, I have initiated the review of this PR. Please keep track

**Comment by smruthi49** [comment]
@rajatvijay, I updated the branch. Could you run the tests?
and yes, I keep track of it :)

**Comment by rajatvijay** [comment]
@smruthi49 they run automatically if the changes introduced are not from your end.

**Review by silentninja — APPROVED** [review]
Thanks for the PR @smruthi49

**Pull request merged**
