### PR TITLE
More installation fixes

### LINKED ISSUE #2572: Installation issues on a Debian 11 server
I tried following the installation steps in a Debian 11 server on GCP. I connected an existing database (I set one up on GCP too). It took forever, and it ended up saying `Container mathesar_service Unhealthy`.

This seems like the same issue reported by one of our usability testers. Anyone should be able to reproduce it by spinning up a Debian 11 server in GCP and trying to install Mathesar on it.

I tried stopping and re-starting Mathesar using the commands in the docs, and I got a bunch of logs, but no indication of whether the site was up. I tried going to the server's IP in my browser, but there was no response. Finally, after a few minutes, I saw the login screen. I tried logging in, but it kept telling me my username and password were wrong.

List of issues, including some additional ones I ran into:
- [ ] Installation didn't work. Installation script ended up saying `Container mathesar_service Unhealthy`
- [ ] I couldn't log in after the site was up.
- [ ] The install script stopped midway because of `wget` being missing. We should add `wget` to our dependencies and check if it's installed when we check for Docker. See "wget failure" image.
- [ ] My DB password had an `)` in it, which broke the `.env` file and the script. This password was auto-generated by GCP, so it seems like a pretty common issue.
- [ ] It took a long time to pull all the images (2-3 min), and I was worried there was something wrong. We should warn users it could take a while (or fix the issue).
- [ ] Once I stopped and started Docker, I did not know how to exit. `Ctrl+C` quit all the Docker containers and took down Mathesar. We should update the start command in the docs to be a command that runs in the background.
- [ ] The user needs to have some feedback on whether starting the containers worked successfully.
- [ ] Handle DB connectivity failing

### wget failure
Screen Shot 2023-02-24 at 2 19 39 PM

### Password failure
Screen Shot 2023-02-24 at 2 23 33 PM

### LINKED ISSUE #2582: Non-default DB port
## Description

When a user chooses a non-default Postgres port in `install.sh`, the service container can't connect to the DB container.

## Expected behavior

The connection should work properly.

## To Reproduce

Run `install.sh`, choose 6543 for the DB port for a new database.

## Additional context

This is probably because the internal docker network doesn't use the same port that's mapped onto localhost on the host. So when the service container tries to connect on the mapped port 6543, the traffic is refused.

### LINKED ISSUE #2592: install.sh fails with empty secret_key on Mac OS Ventura
## Description

Mathesar fails to start because secret_key is empty in .env file after running `install.sh`. The script also fails due to that and steps after that do not run.

Note: This happens on Mac OS Ventura, but seems to work fine on Big Sur

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #2572 
Fixes #2582 
Fixes #2592 

This PR:

- Adds some quotes and brackets around variables to avoid word splitting
- Adds a custom URI encoding function and uses it for passwords and other postgres connection string pieces.
- Fixes a bug in Mathesar's engine creator that threw errors with exotic passwords
- Fixes a bug preventing users from exposing a non-default DB port on localhost
- Changes the secret key generation function for compatibility with newer macOS
- Adds lots of output when the installer fails during the docker setup.
- Adds a step to clean up docker state when the installer fails during the setup.
- Adds some messaging around the time for pulling docker images and starting containers.
- Changes the start command in the docs to background the process

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
Okay, this should be ready for review.

@ghislaineguerin If you have time, please try on your machine too, since one of the fixes relates to your environment.

**Review by ghislaineguerin — APPROVED** [review]
Worked perfectly.

**Comment by pavish** [comment]
@mathemancer I did not get any errors printed when curl fails to fetch `docker-compose.yml` file though. Setup exited without any message.

```
DOCKER SETUP

This step downloads and runs all needed Docker images and starts your Mathesar
installation.

--------------------------------------------------------------------------------

Downloading docker-compose.yml...
pavish@Pavishs-MacBook-Pro mathesar % 
```

**Comment by kgodey** [comment]
> We need to have a message printed here. 

We'll handle that in a separate PR for #2593.

**Pull request merged**
