### PR TITLE
Add query-param for faster type inference when columns known not to have defaults

### LINKED ISSUE #2370: Bypass column defaults-related logic when importing
Meta issue: #2347

Handling column defaults in column type inference is very expensive, but it's also unnecessary when inferring column types for a newly imported column (because it won't yet have defaults). This issue is about disabling that expensive logic when inferring types for a newly imported table.

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #2370

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dmos62** [comment]
Added a `columns_might_have_defaults` (defaults to `True`) query param for the `type_suggestions` endpoint. When set to `False` (via an URL like `/api/db/v0/tables/[table id]/type_suggestions/?columns_might_have_defaults=false`), bypasses defaults-related logic which gives a 50% speed up (see profiling screenshots below).

We probably shouldn't set `columns_might_have_defaults` to false by default (this PR doesn't), because type inference might break if any of the columns had column defaults. This is not a problem during CSV import, because none of the columns have defaults at this time (except `id` column, but don't perform type inference on it anyway).

Profile when `columns_might_have_defaults` not provided or set to true:


Profile when `columns_might_have_defaults` set to false:

**Comment by dmos62** [comment]
@pavish requesting your review to make sure you can make use of the [new query parameter for `type_suggestions` endpoint](https://github.com/centerofci/mathesar/pull/2344#issuecomment-1406497747) when importing a new table.

**Review by mathemancer — CHANGES_REQUESTED** [review]
Overall, I think the logic is fine here, and it seems to work. However, I'd _really_ prefer a parameter such as `check_column_defaults`:
- It's shorter and more instructive
- It works for plural and singular columns (the current param is confusing in single column functions)

I'd also be open to another options that satisfies the above bullet points.

**Comment by pavish** [comment]
@dmos62 Let me know when we have a consensus on the param name and when you need to me to set this parameter on the frontend.

If you'd like to do it yourself, the request is made within the function `getTypeSuggestionsForTable` in `/src/stores/tables.ts`.

**Comment by dmos62** [comment]
Thanks @pavish. [I made the change here](https://github.com/centerofci/mathesar/pull/2344/commits/6ca015ea6612432d33330f539b5f420b59e706f0).

@mathemancer I'd prefer to use the declarative expression, but if you feel that `check_column_defaults` is better, I can cede this debate.

This command would make the change:

```sh
git grep -l columns_might_have_defaults . | xargs sed -i 's/columns_might_have_defaults/check_column_defaults/g'
```

**Review by mathemancer — APPROVED** [review]
After chewing this over, I don't think it makes sense to worry so much about the name. The current one is clear enough.

**Pull request merged**
