### PR TITLE
Add `display_names` key to UIQuery

### LINKED ISSUE #1869: Make it easier to rename DE query columns
Map `alias`es to `display_name`s separately when doing HTTP requests to update display names. Currently a display name is either defined on an initial column definition or on a transformation definition. Simplify that.

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #1869

[This](https://github.com/centerofci/mathesar/pull/1977/files#diff-6717ada562025250ce2bf826376d28ec4593264a39d25239f62f9d216c4e70c6R27) should sum up what the API is being changed to. `display_names` is now a top-level attribute of a query and its structure is a mapping of aliases to display names.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@dmos62 Please make sure to include your reviewers in the "Assignees" section of PRs as well. I've done it myself a few times now.

**Review by mathemancer — APPROVED** [review]
Nice work. The code and tests look good to me. I also appreciate the clean up in the `UIQuery` model; thanks for that.

I'm approving, and not merging since I'm not sure whether you want @pavish to validate the API is as expected.

**Review by pavish — APPROVED** [review]
@dmos62 I tested the PR out and it works as expected!

**Comment by pavish** [comment]
@dmos62 I added a [couple small commits](https://github.com/centerofci/mathesar/pull/1977/files/9c3eea22f690ee7e4d254879f403166ed06dd457..cd568fd60a2c6442058f2caecc3c654e34db11a3) which should fix the workflow failure.

**Pull request merged**
