### PR TITLE
602 add vulture

### LINKED ISSUE #602: Set up Vulture to scan for unused Python code
## Problem

We should ensure that the codebase does not have unused code to make maintenance easier.

## Proposed solution

Set up `vulture` to run on a GitHub Action for all PRs so that we can remove dead code.

We should also do a one-time PR that removes existing dead code.

## Additional context

Here's a GitHub Action: https://github.com/marketplace/actions/python-vulture-action

### PR DESCRIPTION
**Pull request by VFermat**
Fixes #602 

Adds a GitHub action to run [Vulture](https://pypi.org/project/vulture/) to Pushes and Pull Requests.
Vulture looks for unused code.

**Technical details**
Vulture gives confidence on the unused code found. For this action I went with 90%, as used on [this action](https://github.com/marketplace/actions/python-vulture-action)

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

Vitor Eller

### CODE REVIEW

**Comment by seancolsen** [comment]
Thanks for this PR, @VFermat! 

@kgodey or @mathemancer would you care to review this?

**Comment by kgodey** [comment]
@seancolsen I'll take it, I've assigned myself. Thanks!

**Review by kgodey — CHANGES_REQUESTED** [review]
@VFermat This looks great, but the output doesn't show which file the dead code is in so it's hard to fix. See: https://github.com/centerofci/mathesar/runs/4142244656?check_suite_focus=true

This seems to be an issue with the action. I'm not sure that we need to use a GitHub action specific to Vulture, perhaps just running Vulture manually would work? e.g. see this example of a workflow where we run a Python script on the code. https://github.com/centerofci/mathesar-wiki/blob/master/.github/workflows/run-link-rot-detection.yml

**Comment by VFermat** [comment]
@kgodey alright! I will test it as a workflow!

**Comment by VFermat** [comment]
@kgodey adding a reminder here!

**Comment by kgodey** [comment]
@VFermat sorry, I didn't realize this was ready for re-review, the usual practice is to request re-review via GitHub (step 7 here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)

**Comment by VFermat** [comment]
@kgodey sorry for that!

I don't think I have permission to alter the status of my pull requests tho... Can you check that for me please?

**Comment by kgodey** [comment]
@VFermat Can you click this button in the top right of the PR?
Screen Shot 2021-11-16 at 4 16 21 PM

**Review by kgodey — CHANGES_REQUESTED** [review]
I don't see any output here when `vulture` runs: https://github.com/centerofci/mathesar/runs/4230565151?check_suite_focus=true

Running ` vulture . --min-confidence 90` locally results in this:

```
/Users/kgodey/Code/mathesar/db/types/email.py:26: unused variable 'kw' (100% confidence)
/Users/kgodey/Code/mathesar/db/types/money.py:16: unused variable 'kw' (100% confidence)
/Users/kgodey/Code/mathesar/db/types/uri.py:45: unused variable 'kw' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/migrations/0012_transfer_database.py:6: unused variable 'schema_editor' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/migrations/0012_transfer_database.py:15: unused variable 'schema_editor' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/signals.py:9: unused variable 'sender' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/tests/api/test_schema_api.py:23: unused variable 'empty_nasa_table' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/tests/conftest.py:46: unused variable 'django_db_setup' (100% confidence)
/Users/kgodey/Code/mathesar/mathesar/tests/test_multi_db.py:71: unused variable 'multi_db_test_db' (100% confidence)
```

I don't see that on the action output.

**Comment by seancolsen** [comment]
@VFermat I'm looking over our open PRs and noticed that this one still need some changes from you to resolve @kgodey's feedback above. It would be great to get this merged. Are you still working on it? Do you need any help or clarification on the review? Thanks!

**Comment by mathemancer** [comment]
@kgodey All the things found in your local run appear to be specifically excluded by the lines in `pyproject.toml`.  At least one of those things makes sense to exclude (`kw` is idiomatic where it's used).  Should we just start with those excluded for now, or would you rather start with _nothing_ excluded?  I prefer the latter.

**Review by kgodey — CHANGES_REQUESTED** [review]
@mathemancer I apparently didn't think to check the configuration, thanks for pointing that out.

I think we should exclude the things we don't intend to fix (including skipping the `migrations` directories entirely) and remove the continue on error. The idea behind setting this up was to make sure we deleted unused code in PRs.

**Comment by mathemancer** [comment]
Closing this PR, since it's a bit tedious to work on the fork without permissions to that repo, so I'm creating a branch in this  repo, and basing a new PR #965 off of that.  @VFermat If you're out there, thank you very much for your work on this.  @kgodey Please see the new PR for continued review / discussion.

**Pull request closed without merging**
