### PR TITLE
Escape key cancel edits and transitions to select mode

### LINKED ISSUE #1116: Esc key should cancel edits instead of saving
## Steps to reproduce

1. Begin editing a text cell.
1. Modify the contents.
1. Press the Esc key.
1. Expect the cell to transition to select mode, restoring the value before you began making your edits.
1. Observe the cell to transition to select mode, saving the value you entered.

## Expected behavior
1. For stepped input columns (all string based columns, number etc.,) which contain an edit mode, "Esc" key in edit mode should revert the value to what is present in the DB and cancel unsaved edits.
1. For all other columns, "Esc" key would essentially do nothing since value change is based on different interactions.

## Additional context

- The current behavior was established in #1080.
- "Save of Esc" is consistent with AirTable.
- "Cancel on Esc" is consistent with LibreOffice and Google Sheets

### PR DESCRIPTION
**Pull request by chidam333**
Fixes  #1116

Escape key cancels edits and transitions to select mode

**Technical details**
One of the test fails but i am not aware what that test is about
i have it below
This is what the new changes looks like

https://user-images.githubusercontent.com/86545749/194195126-297f7549-4b21-456b-bd0e-e7a63240bdd6.mp4

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

image

### CODE REVIEW

**Comment by chidam333** [comment]
`Still in progress`
Is this for me? I think 🤔 i solved the issue

**Review by seancolsen — CHANGES_REQUESTED** [review]
@chidam333 Thanks for this PR.

Here are some things we'll need to fix:

- The ticket specifies that the escape-to-cancel behavior should apply to all column types which contain an edit mode. Your changes only appear to cover the TextAreaCell. We need to handle other cell types too such as NumberCell.
- I see that the escape key reverts the edit. That's good. But it also needs to transition from edit mode to select mode.
- I would like to see the bulk of the changes made in TextAreaCell.svelte, without modifying much of anything inside TextArea.svelte.
- At a glance, I'm not sure what's going on with this code:

    ```ts
    let duplicate = {accept:true,value:""}; 
    ```

    I'd like new code to be more readable than that by using more descriptive naming.

- There are some CI failures due to linting and formatting. See our [front end docs](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/README.md) for more info on how to run the linting and formatting commands.

**Comment by chidam333** [comment]
Great . I will look into this issues and start working on it as soon as I can .

**Comment by seancolsen** [comment]
I'm closing this PR because it seems to be superseded by #1827

**Pull request closed without merging**
