### PR TITLE
backend changes for column order

### PR DESCRIPTION
**Pull request by AlekLefebvre**
Related to #1584

Added a display_options dictionnary to the table model and to the database. Added it as a field that can be modified with a partial update of a table.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Can we also use this for https://github.com/centerofci/mathesar/issues/1421?

**Comment by AlekLefebvre** [comment]
It could be added to the table display_options but would it make more sense to keep the column widths at the column level instead?

**Comment by kgodey** [comment]
@AlekLefebvre Thanks, this is helpful. I'll defer the decision on how/when to do #1421 to @seancolsen since he's more familiar with the frontend code.

**Comment by seancolsen** [comment]
@kgodey 

> Can we also use this for https://github.com/centerofci/mathesar/issues/1421?

This PR implements `display_options` for tables. My inclination would be persist the column widths within the _column_ `display_options` (not tables). So for that reason, I'd suggest that we handle #1421 separately.

**Comment by seancolsen** [comment]
@silentninja can you review this? I'd like your opinion on whether you think it's best to use table-level `display_options`, as I had originally spec'ed in the [ticket](https://github.com/centerofci/mathesar/issues/1584) (a while ago), or whether you'd prefer to use the "settings" system that you used to implement the table-level metadata for the record summaries. 

I had some trouble running this code locally because of some problem with Django migrations. @AlekLefebvre maybe you could look into that? Django wanted me to merge migrations. Then it said that it had conflicting migrations. I didn't attempt to troubleshoot. Perhaps that's the culprit for the failing CI? I don't know.

**Comment by silentninja** [comment]
@seancolsen @AlekLefebvre Sorry for the late reply. I would prefer to have the table `display_options` under the `settings` instead of it being a table-level field. The reason for it is that we could have different Table Settings for each individual user in the future. Even if we don't end up implementing such a feature, having the flexibility might come in handy.

We didn't do the same for columns because the user could use the Data Explorer to customise the columns to their liking or based on the their use cases.

**Comment by silentninja** [comment]
@AlekLefebvre I am unassigning myself for now as I have reviewed it. Please re-request a review from me once the PR is ready to be reviewed again

**Pull request merged**
