### PR TITLE
#2702

### LINKED ISSUE #2702: Show both row level and column level context menu options in the cell level context menu
## Description
* The right click context menu on a column header has the following options:
  - Screenshot 2023-03-17 at 5 11 03 PM
* The right click context menu on a row header has the following options:
  - Screenshot 2023-03-17 at 5 11 43 PM
* The right click context menu on a cell, only shows an option to set the cell to Null.
  - Screenshot 2023-03-17 at 5 12 31 PM

## Expected
* **The right click context menu on a cell should show the cell level options along with both the column level and row level options.**
* Each section should be separated by a horizontal line in the context menu, and should include headers.

Anyone working on this issue should propose a rudimentary UX design and get it approved before implementation.

----
cc: @ghislaineguerin @seancolsen @rajatvijay Do you think this makes sense?
Update: Resolved, as we are all in agreement.

### PR DESCRIPTION
**Pull request by TafreedAhmad**
Fixes #2702  

**Technical details**

Cell shows options for both row and column levels now!

**Screenshots**
226200130-9148318f-bf98-4383-93ee-baf9c2be44d3

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@TafreedAhmad Please update the PR description to be the same as the GH PR template we use. We rely on the Developer Certificate of Origin, and we cannot merge without it.

**Comment by pavish** [comment]
@TafreedAhmad Thanks!

**Comment by TafreedAhmad** [comment]
Do I need to add something else in this PR? @pavish

**Comment by pavish** [comment]
> Do I need to add something else in this PR?

@TafreedAhmad Nothing else required.

We'll have someone from the core team assigned to review the PR.

**Comment by rajatvijay** [comment]
@TafreedAhmad some of the checks seem to be failing. Please fix them before the review can start.

**Comment by TafreedAhmad** [comment]
> @TafreedAhmad some of the checks seem to be failing. Please fix them before the review can start.

https://github.com/centerofci/mathesar/pull/2728
There were some local branch-level issues that I was facing so I made a new one, this one works the same and have the tests checked, especially the lint one which was causing some problems. @rajatvijay

**Comment by rajatvijay** [comment]
as per the comment here: https://github.com/centerofci/mathesar/pull/2721#issuecomment-1476616119 I am closing this PR.

**Pull request closed without merging**
