### PR TITLE
Improve live demo banner

### LINKED ISSUE #2468: Figure out how to navigate from the live demo back to Mathesar.org
In live demo mode, we should:
- Add a link back to Mathesar in the live demo banner.
- Add a link to Mathesar.org in the top corner menu.

### LINKED ISSUE #2494: Allow users to sign up for Mathesar mailing list from live demo
Users may be interested in signing up for the mailing list once they've looked at our live demo for a while. We should allow them to do so. Many users won’t return to the website after playing with the demo, so they miss out on signing-up.

One idea:
- Consider setting up an opt-in pop up that emerges after 10-15 minutes of continuous use. Copy can be the same as mailing list sign-up on our website.

We can also consider other UI ideas.

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #2468
Fixes #2494

## Before

image

## After

image

- It responds to narrow screens by wrapping

    image

- It does not scroll out of the viewport

    https://user-images.githubusercontent.com/42411/220983508-45983918-71d1-4912-a832-6c7285e89f54.mp4

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@kgodey and @ghislaineguerin You might like to look at this PR too, just by looking at the screenshots to make sure you like the result.

**Comment by kgodey** [comment]
Looks good @seancolsen. One minor suggestion: change the text to "Mathesar is in demo mode." (remove the "live", I think it's unnecessary.)

**Comment by seancolsen** [comment]
@kgodey 

> change the text to "Mathesar is in demo mode."

Done via 677fa6c8d92a7e80dcadcebc28628ece4d1ff26b

**Review by rajatvijay — APPROVED** [review]
LGTM!

**Pull request merged**
