### PR TITLE
Add E2E test for trying to to rename a table to the name of another table

### LINKED ISSUE #1125: Add E2E test for trying to to rename a table to the name of another table
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "trying to to rename a table to the name of another table" works as-expected. Here's a visual demo of what the test should do:

Peek 2022-03-02 16-45

## Tips

- Assert that the error message is shown and that the save button is disabled

### PR DESCRIPTION
**Pull request by ManishShah120**
Fixes #1125 

Added e2e tests for renaming a table name with the existing table names.

**Technical details**

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Adding @seancolsen as a frontend reviewer since this is an E2E test.

**Comment by seancolsen** [comment]
@ManishShah120 We have a continuous integration workflow step failing in this PR due to some Python linting errors. You can see the error details by clicking on the "details" link in the step with the red X above. The relevant part is:

```
./mathesar/tests/integration/test_tables.py:13:1: E302 expected 2 blank lines, found 1
```

You can see this error locally too by running:

```
flake8 .
```

Can you push another commit after you've verified that you have no errors locally from flake8?

**Comment by ManishShah120** [comment]
Done @seancolsen

**Review by kgodey — APPROVED** [review]
Python code looks fine to me. I'll leave it to @seancolsen to evaluate the E2E test and merge.

**Review by seancolsen — APPROVED** [review]
Looks good. Thanks @ManishShah120

**Pull request merged**
