### PR TITLE
UI for creating & managing shares for tables and explorations

### LINKED ISSUE #3035: Implement frontend flow: User sharing an entity
I've not added a description, since I'll be implementing this.

Refer [Product spec](https://wiki.mathesar.org/en/product/specs/publicly-shareable-links) for detailed info.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #3035 

### This PR
* Allows users to share tables and queries from the UI

### Demo
<div>
    <a href="https://www.loom.com/share/2b6318e2e9aa44a4a070f7ed18bd5a49">
      <p>Demo of UX for Share Table and Share Exploration Functionality - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/2b6318e2e9aa44a4a070f7ed18bd5a49">
      
    </a>
  </div>

### Flow: Sharing an entity
**When table isn't shared**
Screenshot 2023-08-03 at 6 15 04 AM

**After sharing the table**
Screenshot 2023-08-03 at 6 15 16 AM

### Flow: Viewing shared entity using the link
**Table**
Screenshot 2023-08-03 at 6 16 04 AM

**Exploration**
Screenshot 2023-08-03 at 6 17 35 AM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@ghislaineguerin and @kgodey I've requested your reviews for the UX for sharing tables & explorations.

Please take a look at the video for demonstration of the feature.

**Comment by pavish** [comment]
This PR is marked as a draft because it depends on another PR which isn't merged it. But it is ready for review.

**Comment by ghislaineguerin** [comment]
Thank you, @pavish . I think this is pretty straightforward. I don't see anything at this point that needs to be changed. I believe the options to create a link, and then to disable and regenerate, are very easy to understand.

Let's please ensure that we're using title case in the action buttons, as I believe we do that elsewhere. If you look at the 'Links' section in the inspector, we have 'Create Link,' where 'Link' is in uppercase.

I also don't know if we want (and this is something just to consider) to show somewhere in the table properties that this table is currently shared. The only way to know the status is to open the share button.

**Comment by kgodey** [comment]
@pavish The UI looks good to me, nice work!

Like @ghislaineguerin, I also have a question about what the "Share" button will look like when there's already a link created. I assume it will change state somehow to show that the table / exploration is shared. I'd like to see that too.

**Comment by seancolsen** [comment]
Re-assigned to @rajatvijay for review per [discussion](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$au2_g-nS9Y4UGj3bxatxNtKtlMD7GNDzNVl8bhwqNOE?via=matrix.mathesar.org&via=matrix.org).

**Review by dmos62 — COMMENTED** [review]
Backend changes approved.

**Comment by pavish** [comment]
@ghislaineguerin and @kgodey

Thanks for your reviews.

> what the "Share" button will look like when there's already a link created. I assume it will change state somehow to show that the table / exploration is shared. I'd like to see that too.

This is currently not handled. The user will only know if the table is already shared or not when they open the dropdown.

I thought of a change in color, or a dot notification, both of which require a UX pattern which we haven't established uniformly, and I ultimately decided to get the feature completed and handle this later.

We can handle this as a separate issue for the next release. Does that sound good?

**Comment by kgodey** [comment]
> We can handle this as a separate issue for the next release. Does that sound good?

Yes, but please make an issue to track it.

**Review by rajatvijay — APPROVED** [review]
LGTM 🚀

**Pull request merged**
