### PR TITLE
sorted schemas alphabetically by name

### LINKED ISSUE #1897: Sort list of schemas
On the Database Page, the schemas appear in random order.

image

I think they should be listed alphabetically, perhaps with `public` first.

I'm not sure whether it would be better to handle this on the back end or the front end.

Any thoughts @mathemancer @rajatvijay?

Update:
* This issue is supposed to be handled on the backend.
* Part of this issue is solved in https://github.com/centerofci/mathesar/pull/2062
* Refer https://github.com/centerofci/mathesar/issues/1897#issuecomment-1470542703 for the current state of the issue.

### PR DESCRIPTION
**Pull request by ayao451**
Fixes #1897

Added sorting to the schemas by name!

**Technical details**

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by kgodey — APPROVED** [review]

**Comment by silentninja** [comment]
@kgodey @ayao451 We cannot sort a Schema by its name as we don't store the `name` of the Schema in the Django model. This sorting should be done on the Users database

**Comment by ayao451** [comment]
Sounds good, I will fix this with my next PR

**Comment by kgodey** [comment]
Sorry for leading you astray @ayao451. I'm not sure why the test failure didn't block your PR from being merged, it should have.

I noticed you had `I tried running the project locally and verified that there are no visible errors.` unchecked in your PR description. Please always make sure the project runs fine locally before submitting a PR.

**Comment by ayao451** [comment]
@kgodey We are also doing a project with four people! I am not the only one doing this project, are there other easier tasks for us to take that you recommend?

**Comment by silentninja** [comment]
@ayao451  #1897 is really a complicated issue and will need a really good understanding of the codebase to fix it. Please don't worry about this PR, I will take care of it.

**Comment by silentninja** [comment]
> We are also doing a project with four people! I am not the only one doing this project, are there other easier tasks for us to take that you recommend?

@ayao451 Please take a look at #2053. It might a good issue to start working on

**Pull request merged**
