### PR TITLE
Fixes #2736: database page table and exploration count update without reloading 

### LINKED ISSUE #2736: Database Page not reflecting updated Table Count unless reloaded
## Description
The Database page shows the table count of all the schemas from the last time the page is reloaded. Creating a table or deleting one doesn't change the table count of the schema. The Table count updates to the current value once it is reloaded and gets fixed to that until the next reload.

## Expected behavior
The table count should change once the tables are created or deleted.

## To Reproduce
- Go to the database page (login redirects you to this page).
- Select a schema and create a table.
- Now go back to the database page by clicking on the Mathesar icon on the left top corner.
- The table count hasn't changed.

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29

### PR DESCRIPTION
**Pull request by HamzaA598**
Fixes #2736

**Technical details**

To make the database page reflect changes, it is necessary to access the database to obtain the count of tables and queries. Then we need to make the two variables reactive. This will enable the UI to dynamically update as the underlying database changes.

**screencast**

mathesar_tables _ public _ Mathesar - Google Chrome 2023-03-30 22-52-20

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@rajatvijay There's already a PR under review for the same issue which is assigned to me. Please prioritize the PRs before assigning them for review.

**Comment by HamzaA598** [comment]
@pavish I thought multiple pull requests on the same issue are ok. Are they not?

**Comment by pavish** [comment]
Assigning this back to me, as the discussion over multiple PRs for same issue was resolved in private Matrix chats.

**Review by pavish — CHANGES_REQUESTED** [review]
This PR does not fix the issue. Please read through the issue description and the codebase to understand it better.

The tables and queries store only contain the details of the tables & explorations of the currently open schema. If we have more than one schema, the logic will show the same count everywhere.

**Comment by pavish** [comment]
@HamzaA598 I'm going to close this PR since the implementation widely differs from what is expected and the bug isn't fixed. Please open a new one once you fix the issue.

**Pull request closed without merging**
