### PR TITLE
Updated Django REST Framework settings to use JSONParser as the default parser for incoming requests

### LINKED ISSUE #3089: Remove redundant Request body content types
Currently, the requestBody section of some API endpoints specifies three content types: application/json, application/x-www-form-urlencoded, and multipart/form-data. However, in our application, we only use the application/json content type for request payloads.

Example :
```requestBody:
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/JsonDataFile'
    application/x-www-form-urlencoded:
      schema:
        $ref: '#/components/schemas/DataFile'
    multipart/form-data:
      schema:
        $ref: '#/components/schemas/DataFile'
```

**Proposed Solution:**
 The unnecessary application/x-www-form-urlencoded and multipart/form-data content types from the requestBody should be removed.To achieve this we need to ensure that our API views are set to use the JSONParser class as the default parser for incoming requests. This can be achieved by updating our Django REST Framework settings as follows:

```
# common_settings.py
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Other DRF settings...
}

### PR DESCRIPTION
**Pull request by varshadr**
Fixes #3089 

This PR removes unnecessary application/x-www-form-urlencoded and multipart/form-data content types from the requestBody section in relevant API endpoints, by updating the Django REST Framework settings to use JSONParser as the default parser for incoming requests.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by silentninja — APPROVED** [review]
This looks good to me

**Review by silentninja — DISMISSED** [review]
The test cases are failing. This is happening because uploading `/datafiles/` API relies on the `multipart/form-data`. So you would need to add additional `multipart/form-data` parser support for the `/datafiles/`API. Please request a review once the test cases are passing

**Review by iamrajiv — APPROVED** [review]

**Comment by seancolsen** [comment]
@varshadr I'm re-assigning this to @mathemancer because Mukesh will no longer be working with you on this project. Please assign any further PRs to @mathemancer for review.

**Comment by varshadr** [comment]
> @varshadr I'm re-assigning this to @mathemancer because Mukesh will no longer be working with you on this project. Please assign any further PRs to @mathemancer for review.

Sure @seancolsen , I will

**Review by mathemancer — APPROVED** [review]
Looks good to me. Nice work, @varshadr !

**Pull request merged**
