### PR TITLE
Money type domains WIP

### LINKED ISSUE #417: Backend work for Mathesar money custom type
This issue is to create a custom `Money` data type to handle monetary data.  At the DB level, this will refer to a number of types such as `MATHESAR_TYPES.MONEY_USD`, `MATHESAR_TYPES.MONEY_JPY`, etc.  Each underlying type should have a name of the form `MATHESAR_TYPES.MONEY_<currency code>`, where `currency code` is one of the 3-character currency codes defined in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html).  

As part of this issue, we need to:
- Create a `Money` friendly type name in the service
- Create a number of `MATHESAR_TYPES.MONEY_<currency code>` types in the database that store currency amounts.  The amount should be a `NUMERIC` type.
  - The types should be case-insensitive at the DB layer and uppercase in the API
- We'll create the types automatically, putting things together using some package like https://github.com/arshadkazmi42/currency-symbols or https://github.com/python-babel/babel to provide currency symbol info.
- Users should be able to use the API to change a column to `MATHESAR_TYPES.MONEY_<currency code>` if it's possible to do so.
- Automatic type inference during file import suggests `MATHESAR_TYPES.MONEY_<currency code>` when it makes sense to do so.

**Additional Context** 
- Blocked until #409 is complete, to serve as a model for DB case insensitivity
- See PR #368 for code that calculates which types are allowed for a column.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #417

**Technical details**

**Screenshots**

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@mathemancer I thought we were going to leave the multi-currency `MONEY` type in so we could build a UI for it in the future? It looks like this PR deletes it.

I made the following issues to build a design/frontend for it:
- #656 
- #657

**Comment by mathemancer** [comment]
> @mathemancer I thought we were going to leave the multi-currency `MONEY` type in so we could build a UI for it in the future? It looks like this PR deletes it.
> 
It leaves it in, but avoids hooking it up to the API.  It's also removed from "supported types", since that would end up getting picked up by the API code.  This is the reason for the removal of all the associated tests.

**Comment by kgodey** [comment]
@mathemancer do you want to close this PR since we're going to be implementing money via display options?

**Comment by mathemancer** [comment]
> @mathemancer do you want to close this PR since we're going to be implementing money via display options?

Good idea, closing.

**Pull request closed without merging**
