### PR TITLE
Frontend: File import page

### LINKED ISSUE #149: Switch to new CSV file import API
**Problem**

We're switching to CSV file imports via API in https://github.com/centerofci/mathesar/pull/141. The frontend still uses the old version.

**Proposed solution**

The frontend code should use the new APIs.

### LINKED ISSUE #293: File import component
We require a drag and drop file import component. As part of this ticket, we'll also have to handle ARIA accessibility and unit tests for it.

### LINKED ISSUE #294: File import page
Implementation of file import page based on design spec.

  - Get table name & schema
  - Allow users to upload file
  - Show upload status & processing status
  - Do not allow users to close tab
  - Tests

### PR DESCRIPTION
**Pull request by pavish**
Fixes #293 
Fixes #149 
Fixes #294 

## This PR:
* Handles file import, based on data_files and table APIs
* Handles tab state as dedicated store
* Components:
  - File upload drag and drop component
  - Progress
  - Notification
* Fixes a bug in Safari, related to CancellablePromise class
  - Safari does not support # based private properties in class. The properties are made public now.
 
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
The code here looks quite good, and my only feedback is around behavior. It's likely these are known issues and intended to be fixed in the future. 

## UX Issues

- When an upload errors, a generic failure message is shown. It would be good to show the name of the file that failed as well.

CleanShot 2021-07-07 at 15 09 34 2@2x

- I tested two kinds of upload failures:
 	1. Uploading an invalid media type (e.g., images, .txt files, etc.)
 	2. Uploading a corrupt/invalid CSV file that can't be parsed
Currently, these failures report the same error message, which may confuse users who upload a malformed CSV and wonder why it didn't work.
- When uploading multiple files, the multiple files display, but do not actually upload. 

CleanShot 2021-07-07 at 15 19 49@2x

- When uploading multiple files, and one or more is invalid (either incorrect file format or a malformed CSV), all files fail to upload and the generic error message is shown.

**Comment by pavish** [comment]
@zackkrida
1. I agree with showing specific error messages, instead of generic ones. Currently we do not have a streamlined error handling structure on the backend. @kgodey I assume this is in one of our milestones. When we get to that, the error messages would be more specific.

2. The file import page is not supposed to allow multiple files. However, the component was designed to handle both single & multiple uploads, based on a prop. Upon click and browse, it is handled, but I missed handling the scenario where multiple files are dragged and dropped when it is configured to single. That is why only the first file uploads, but the rest do not. I will handle this in an additional commit.

I also missed to format the file size for display. I will add it on the same commit. Thanks for the thorough review! :)

**Comment by pavish** [comment]
@zackkrida I've updated the PR with two additional commits:
* Handle file drop based on multiple flag: To handle drag and drop based on the multiple prop. In FileImport page, we only allow a single file.
* Format size to readable terms: Formats file size and displays it in readable terms.

**Review by kgodey — APPROVED** [review]
Looks good!

**Pull request merged**
