### PR TITLE
Add more `install.sh` fixes

### LINKED ISSUE #2599: Issues with installation process that connects an existing DB
- [x] Tester Marius reports (server credentials in Upwork)
  - [ ] It seems that even if you select existing database, it still tries to start a docker container for the database, creating a conflict?
- [x] Tester Mohammad reports an error as well ([details here](https://docs.google.com/document/d/15m9eZFocAsU1V9inLKxC6i_KQxMdu28snRrBPOrf5Hk/edit))

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #2599 
Related to #2593 

This PR:
- modifies `install.py` to quote DB names, thereby allowing more exotic characters.
- modifies `install.sh` to disallow using `localhost` as the host for preexisting databases.
- modifies `install.sh` to give more useful feedback if a connection to some needed artifact fails (related to #2593 )

**Technical details**

**Screenshots**

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@mathemancer I'm unable to understand the rationale behind disallowing localhost for the db connection. I have a postgres db on my local machine and I would like to be able to connect to it via Mathesar. What is the issue that's preventing this?

**Comment by mathemancer** [comment]
> @mathemancer I'm unable to understand the rationale behind disallowing localhost for the db connection. I have a postgres db on my local machine and I would like to be able to connect to it via Mathesar. What is the issue that's preventing this?

Docker doesn't allow it on all platforms (at least not easily) and we don't have time to figure which is which at the moment. If we end up with more time before release (for some reason) I agree it would be nice to allow it at least on platforms where it works. However, even on platforms where it _does_ work, you wouldn't input it as `localhost`, so that would still be incorrect.

**Comment by mathemancer** [comment]
JJ

> @mathemancer
> 
> > even on platforms where it does work, you wouldn't input it as localhost, so that would still be incorrect
> 
> Okay, you're right, that makes sense. Thanks.
> 
> Even in platforms that work, we'll have to specify it as `host.docker.internal`.

I figure if they're savvy enough to know that, let users try it as an undocumented feature for the moment. We can document it once we know the details / edge cases.

**Comment by mathemancer** [comment]
@silentninja To check the fix for exotic database names, you'll have to build an image locally from this branch and use that in `install.sh`.

**Review by silentninja — APPROVED** [review]
Nice work @mathemancer The changes work for me

**Pull request merged**
