### PR TITLE
Enable caddy compression and precompression

### LINKED ISSUE #2204: Compress static assets while serving
## Description
* Our frontend static assets are being served as is, in production mode. This leads to a higher loading time.
* They need to be served with gzip compression.
* ~For User-Agents that support brotli, they need to be compressed with brotli~ (branched off to a separate issue: https://github.com/centerofci/mathesar/issues/2411).

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #2204

Based on https://github.com/centerofci/mathesar/pull/2129. Might want to merge that first.

Enables precompression, i.e. will look for sidecar files compressed with Brotli, Zstd or Gzip (in that order), and will fall back to encoding in Zstd or Gzip (in that order).

To take advantage of precompression, we'll probably have to compress our files during Docker image builds (for Docker deployments) and whatever has to be done for Docker-less deployments.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@dmos62 Why are we compressing in Ztsd? As far as I know, not many browsers support it.

We need our frontend files served over http to be compressed in Gzip, which is supported by all browsers. The Brotli compression support needs to be checked on the fly based on the user-agent string, which is out-of-scope of this PR.

**Comment by dmos62** [comment]
@pavish we're preferring Zstd over Gzip because it's often better. Caddy is smart enough so that if an encoding is unsupported by the calling browser, it will not be used (that's why we specify a list of encodings).

Precompression (as configured via the `precompressed` directive) is about looking for precompressed sidecar files. They will probably be compressed during packaging or deployment. If a precompressed sidecar file is not found, the file will be compressed on-the-fly (as configured via the `encoding` directive).

The actual precompression will be setup in a separate PR (see the new issue that I branched off of the one being fixed by this PR).

Does this make sense?

**Comment by dmos62** [comment]
Btw, this is blocked on #2129, but can be reviewed now.

**Comment by pavish** [comment]
@dmos62 

> Caddy is smart enough so that if an encoding is unsupported by the calling browser, it will not be used (that's why we specify a list of encodings)

Okay, that sounds good, thanks. I'm unaware of caddy, but it seems from your description that it does what I expect out of the PR.

**Comment by dmos62** [comment]
Pushed some fixes, and ran `caddy fmt` to reformat the Caddyfile. Ready for review @silentninja.

**Review by silentninja — APPROVED** [review]
Thanks for the PR @dmos62. The compression works for me

**Pull request merged**
