### PR TITLE
bug: Close on overlay click -ModalRecordSelector

### LINKED ISSUE #3207: The "Record Selector" modal close when clicking on the overlay.
## Description
The "Record Selector" modal cannot be closed when clicking on the overlay. Currently, the only method to close the model is via the "cross" icon button of the modal. 

## Expected behavior
The "Record Selector" modal should close when clicking on the overlay. 

image

## Environment
 - OS: Windows
 - Browser: Chrome

## Additional context

Matrix Thread: [link](https://matrix.to/#/!vXLxAqmrJWsDMWPSpo:matrix.mathesar.org/$Tlts3aCa-53t6YBOYF3iOuoYl1dPvekwIMhbD1lh7yw?via=matrix.mathesar.org&via=matrix.org&via=t2bot.io)

### PR DESCRIPTION
**Pull request by FidalMathew**
Fixes #3207 

This PR fixes the on-click overlay issue for ModalRecordSelector. The issue is resolved using appropriate z-index values for components. 

**Screenshots**
CPT2309201127-1015x692

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by FidalMathew** [comment]
@seancolsen I created a new PR. Let me know if any changes are required.

**Review by seancolsen — CHANGES_REQUESTED** [review]
As you can probably tell, the Record Selector is quite complex. One important thing to point out is that it's designed to support "nested" selections, as demonstrated below (on the `develop` branch).

https://github.com/centerofci/mathesar/assets/42411/6062b511-98b6-4157-804b-cf0136b84832

The need to support nested selections is why the record selector doesn't use the plain modal system and instead uses lower-level primitives.

Here are some issues I have with your changes:

- The drop shadow of the window is no longer visible with your changes.
- The alignment of the nested selector with respect to its parent is incorrect.
- The nested selector does not close when clicking on the overlay, making the behavior inconsistent.

These are not exactly terrible problems. But I'd like these to be fixed before merging.

With the approach you've taken, I'm not sure how easy it will be to fix the above problems.

Another approach I'm considering is this:

1. When the root record selector opens, we'd add a `'click'` event listener on `window`.
1. For each click, we'd use DOM APIs to see if the click was within the bounds of the top-most record selector window. If so, do nothing. Otherwise, close the top-most record selector window.
1. When the root record selector closes, we'd remove that event listener on `window`.

I'm not certain this would be the best way to solve this problem, but it's one thing I thought of.

**Comment by FidalMathew** [comment]
@seancolsen I tried your approach to address this issue, the code is now working for nested selectors. Could you take a look at it?

**Comment by seancolsen** [comment]
Thanks @FidalMathew. I'll review this, but it may take me a couple weeks to get to it.

**Comment by FidalMathew** [comment]
@seancolsen when would it be possible for you to check out the PR?

**Review by seancolsen — APPROVED** [review]
@FidalMathew thanks for this! Your fix worked great.

From a code-cleanliness perspective, I didn't like the `newModalOpen` variable you added though. It wasn't clear to me why it was there. When I removed it, I realized its purpose &mdash; to prevent the event listener from firing as soon as the component mounts, and thus to avoid closing the modal immediately after it opens.

I added 4ca3ca3e210e7d874e2d046a25b7ce0e3aa2f8d4 with a different approach that I hope you will agree is cleaner. Instead of `on:click`, we use `on:click|capture`. This allows us to remove the `newModalOpen` variable.

Aside from that point, though everything else in this PR seems good, so I'm merging it.

**Comment by FidalMathew** [comment]
Thank you @seancolsen for taking the time to review the PR 😄.

**Pull request merged**
