### PR TITLE
Consistent 404 pages across client and server

### LINKED ISSUE #2442: Handle 404 pages throughout the app
## Description
* Client side routing: A non existent url results in a blank screen, or has obscure errors.
* Server side routing: A non existent url entered on the browser results in a 404, which returns a django 404 page.

## Expected behavior
* 404s should be clearly presented to the user in all valid cases.
* The 404 page should be consistent in appearance in both server side & client side routing.

### PR DESCRIPTION
**Pull request by rajatvijay**
Fixes #2442 

**Technical details**

Server-side
Screenshot 2023-02-21 at 6 28 43 PM

Client-side
Screenshot 2023-02-21 at 6 27 04 PM

Updated SS with a home button added
Screenshot 2023-02-22 at 9 05 32 PM

@kgodey I know we decided on the "Go to database page" title for the button but still, I used "Go to home" because technically I am not redirecting the user to the database but to the root('/') URL. To direct to the database page I would have needed the name of the database which wouldn't have made much sense in the generic `ErrorPage` component. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
We need some sort of way for the user to navigate away from the 404 page.

**Comment by rajatvijay** [comment]
The user can always use the browser's back button. But I'll also add a Home button just in case back is not possible when he landed directly on that URL from an external place.  @kgodey

**Comment by kgodey** [comment]
Thanks @rajatvijay

**Comment by rajatvijay** [comment]
@kgodey checkout my comment in the description.

**Comment by kgodey** [comment]
Could we make it "Go home" or "Go to homepage" instead? "Go to home" sounds odd. @seancolsen Since you're reviewing, feel free to change and merge.

**Review by seancolsen — APPROVED** [review]

**Pull request merged**
