### PR TITLE
Common Header typographies, Fixes part issue #2416

### LINKED ISSUE #2416: Make header css common
## Description
* We have a fair share of typography related css which are placed in components, which leads to inconsistencies across the app.
* We'll need a set of global typography related css classes which we can use.
* For eg.,
  *  Refer [this comment](https://github.com/centerofci/mathesar/pull/2390#discussion_r1092323637) for inconsistencies in headers across pages due to per-component css.
  * We also have headers in table page and exploration pages.
  * We'll need a set of global css classes for headers, which we can then use within the components.
* ~~Whoever takes this up **should also go through the product for other places with the same issue as the headers**, mention them in the comments, get approval from maintainers, and fix them in their PR.~~ This part can be taken up individually as issues are raised. 

Update:
* This issue is limited to headers, and typography related changes can be taken up incrementally as we make our design system more concrete.

### PR DESCRIPTION
**Pull request by Hatilar420**
Fixes #2416 

1. Adds common Typography CSS for common header styles.
2. Resolves part typography inconsistencies related to header tags in almost all files. 

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@Hatilar420 I've edited the PR description to say "related to" instead of "fixes" since this doesn't address everything in #2416

**Comment by Hatilar420** [comment]
Thanks for updating it @kgodey  :)

**Comment by Hatilar420** [comment]
ping @pavish

**Comment by Hatilar420** [comment]
Thanks for the review @pavish, will implement the changes soon.

**Comment by Hatilar420** [comment]
Hey @pavish, i am very sorry it is taking some time to implement the suggested changes, as i am busy with some college assignments..Will soon implement the said changes.

**Comment by rajatvijay** [comment]
@Hatilar420 sure.

**Comment by Hatilar420** [comment]
Hey @rajatvijay @pavish, Can you please look at the requested changes?
I am sorry for this delay with the changes. I was busy with college assignments and the GSOC proposal.

**Review by pavish — APPROVED** [review]

**Pull request merged**
