### PR TITLE
Adds more space at the bottom of the Schema Page

### LINKED ISSUE #2367: Add more space at the bottom of the Schema Page
On the Schema Page, when the viewport is short enough to require vertical scrolling, we should have some more space between the bottom of the tables list at the bottom of the viewport.

image

### PR DESCRIPTION
**Pull request by IamEzio**
Fixes #2367 

Adds spacing at the bottom of tables list in Schema overview and Tables tab.

**Screenshots**

*Before and After video*

https://user-images.githubusercontent.com/89375125/223046912-9e4cd70a-8275-42ba-9671-ef3b7d49224f.mp4

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by IamEzio** [comment]
Hi @rajatvijay, a friendly ping :)

**Comment by Anish9901** [comment]
@IamEzio Please look at https://github.com/centerofci/mathesar/pull/2420#issuecomment-1429413339.

**Review by rajatvijay — CHANGES_REQUESTED** [review]
@IamEzio Giving padding-bottom to the table list container won't work since there might be cases when there are no tables in the schema but due to the viewport size the explorations section goes to the bottom and there again is no space available in the bottom. See the SS attached. 
Screenshot 2023-03-02 at 3 21 37 PM

Also, please use `rem` instead of `px`.

**Comment by IamEzio** [comment]
Thanks @rajatvijay. I have updated the PR and the PR description now. PTAL

**Review by rajatvijay — APPROVED** [review]
Good Job @IamEzio 🚀

**Pull request merged**
