### PR TITLE
Added user API, allows CRUD on users.

### PR DESCRIPTION
**Pull request by kgodey**
Related to #1673 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by mathemancer — CHANGES_REQUESTED** [review]
I can't get this to work locally, and I'm not sure why. Steps I followed:

- pull this branch
- knock out `.volumes` and `.media`
- `docker-compose up`
- run `make initial_setup`
- `POST http://localhost:8000/api/ui/v0/users/` with 
  ```json
  {
    "username": "alice",
    "email": "alice@example.com",
    "password": "password",
    "short_name": "Alice",
    "full_name": "Alice Jones"
  }
  ```
Response was `500`. Here's the cut-n-paste
```
  Environment:


Request Method: POST
Request URL: http://localhost:8000/api/ui/v0/users/

Django Version: 3.1.14
Python Version: 3.9.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /usr/local/lib/python3.9/site-packages/rest_framework/templates/rest_framework/horizontal/form.html, error at line 2
   'ReturnList' object has no attribute 'get'
   1 : {% load rest_framework %}
   2 :  {% for field in form %} 
   3 :   {% if not field.read_only %}
   4 :     {% render_field field style=style %}
   5 :   {% endif %}
   6 : {% endfor %}
   7 : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 696, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 493, in get_rendered_html_form
    return self.render_form_for_serializer(existing_serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 372, in render
    return template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 167, in render
    values = list(values)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 531, in __iter__
    yield self[field.field_name]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 536, in __getitem__
    error = self.errors.get(key) if hasattr(self, '_errors') else None

Exception Type: AttributeError at /api/ui/v0/users/
Exception Value: 'ReturnList' object has no attribute 'get'
```
I think this is the error with the error handler we've spoken of previously.

@silentninja any insight on this?

**Comment by silentninja** [comment]
I am not able to reproduce it, can you attach the request headers and parameters? When I sent the request it succeded, I got the following errors when I sent incorrect errors

1. Without CSRF - 
```
[
    {
        "code": 4004,
        "message": "CSRF Failed: CSRF token missing or incorrect.",
        "details": {
            "exception": "CSRF Failed: CSRF token missing or incorrect."
        }
    }
]
```

2. Existing username - 
```[
    {
        "code": 3001,
        "field": "username",
        "message": "A user with that username already exists.",
        "detail": {}
    }
]
```

**Comment by kgodey** [comment]
@mathemancer I'm able to reproduce your error using the DRF browseable API. However, this appears to be a bug with the browseable API feature, not with our code. See [this StackOverflow answer](https://stackoverflow.com/a/41871991/287415) and this DRF GitHub issue https://github.com/encode/django-rest-framework/issues/6084#issuecomment-407387989

**Comment by mathemancer** [comment]
After talking in other channels with @silentninja and doing some debugging, this appears to be caused by a mismatch of types.

Our `MathesarErrorMessageMixin` changes the type of the `errors` property of every serializer where it's used from a `dict`-like (I.e., one that implements the `get` method) to one that is `list`-like (and so has no such method). However, something about the templating engine for DRF seems to expect a `get` method for the `errors` property.

Big picture: In principle I think overriding the `errors` property of serializers in a way that modifies the interface with a breaking change is probably a bad idea. In fact, given the complexity of Django, I think overriding any property of _anything_ in a way that introduces a breaking change to its interface is a bad idea. At the moment, the only place it's biting us (that we know of) is in the DRF template, but it wouldn't surprise me if this is a problem in other places too.

Small picture: This isn't specific to this PR, so I suppose we should merge this and change the relevant mixin somewhere else.

**Review by mathemancer — APPROVED** [review]
As discussed in comments, let's handle the problem I raised with a separate PR.

**Pull request merged**
