### PR TITLE
Truncate group header to fit virtual sheet

### LINKED ISSUE #2376: Don't scroll group header rows horizontally
## Current behavior

- Horizontally scrolling a table page with group header rows looks pretty weird.

    image

## Desired behavior

- The group headers use `position: sticky; left: 0;` to prevent horizontal scrolling.

- The tricky part then becomes dealing with group headers that are wide to fit within the viewport. For example:

    image

    We would need to figure out some way to making these shrink responsively, using `Truncate`, similarly to how I've done within the navigation header. I suspect that even just getting the group header row to fit the width of the sheet bounds will be a little tough. If we didn't have a table inspector we could size it via `width: 100vh;`, but that won't work when the table inspector is visible. I might consider reaching for Svelte's `bind:width` feature here, thereby determining the width of the sheet bounds via JS and then passing that width into the group header row.

@ghislaineguerin @pavish @rajatvijay Does this sound okay to you? If so we can un-draft this and apply a "help wanted" label.

### PR DESCRIPTION
**Pull request by dauinh**
Fixes #2376 

Implement `Truncate` on group header to fit virtual sheet (so user don't have to scroll horizontally to see group header content).

**Technical details**

Apply the same truncating logic with `BreadcrumbItem`.
Pass width of `SheetVirtualRows` via CSS.

**Screenshots**

https://user-images.githubusercontent.com/62679553/228635882-18197c2b-cdab-4a71-bdf6-aad05d289c2a.mov

**Bug**
- Group header stops truncating after a certain screen size
- `text-overflow: ellipsis;` doesn't apply
- Group item count is truncated as well (Do I set `--view-width` to be a little smaller?)

@seancolsen I'm not really sure how to fix these bugs. Can you give me more guidance on this?

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dauinh** [comment]
Hi @seancolsen 

Thank you so much for your feedback. I tried applying width constraint with `group-header` class, but it created this behavior.

Screenshot 2023-05-02 at 9 38 47 AM

I realize the counter is cut off because of the right padding. Is it a better approach to apply width constraint on `groups-data` with right padding same as `group-header`?

**Comment by seancolsen** [comment]
@dauinh Sorry, but the core team doesn't have the capacity to provide this much assistance with small PRs like this. You're going to need to figure it out on your own from here. I'll be happy to spend more time reviewing your work if you can get it to a point yourself where you feel that it's done.

**Comment by dauinh** [comment]
Hi @rajatvijay @seancolsen 

I have marked this PR ready and I'd like to request a review. I'm sorry for not mentioning this after marking

**Review by seancolsen — CHANGES_REQUESTED** [review]
@dauinh This is getting closer. Can you make it so that the group header rows don't scroll horizontally when the table scrolls?

**Pull request closed without merging**
