### PR TITLE
Set "shift" + "delete" as keybind to set null

### PR DESCRIPTION
**Pull request by KasukabeDefenceForce**
Related to #936

Added a case for the shift + delete key. 

**Technical details**
I made changes in the "SteppedInputCell.svelte". The file had a function to handle other keybinds so I added in an extra case for delete key. Within the case, it checks whether the "shift" key is pressed along with "delete" key or not and the edit mode is off. If both conditions are satisfied it sets the value to null.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AbhinavOhri** [comment]
I have only set the "shift" + "delete" keybind. I am still working on the note null constraint and the toast message.

**Comment by kgodey** [comment]
Thanks @AbhinavOhri. Please let us know when the PR is ready for review or if you need additional help.

**Comment by AbhinavOhri** [comment]
I am having some issues with this PR:
1.) I used this file "https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte" as a reference while writing the function. I defined the column in the same manner as in the "ColumnOptions.svelte" but am getting the error "column is undefined".
2.) I am unable to style the toast message with the Null component. I looked through all the uses of toast in the code base but could not find a similar one. 

I was looking through the code that is why I was stuck on this for the past few days. Please help me with this.

**Comment by rajatvijay** [comment]
@KasukabeDefenceForce thanks for your contribution, there are a couple of problems with it: 

1. This feature is not concerned with the nullability of the column, but with setting the value of the column as null. 
2. Instead of separately implementing the shortcut in each and every cell type, I think it will make more sense to do this in `RowCell`.

I have made a [PR](https://github.com/centerofci/mathesar/pull/2922) with the fix, just in case you wanna take a look.

**Pull request closed without merging**
