### PR TITLE
Add live demo movie dataset

### PR DESCRIPTION
**Pull request by mathemancer**
Related to #1906 

This adds a large, and fairly complex Movie Collection data set to the live demo data.

**Technical details**

Some interesting features of this set are that there are multiple linking paths between a given movie and a given person, based on whether they're cast, crew, both, or if they have multiple cast or crew credits for the movie. It also makes a lot of use of more 'many-to-many' mapping tables than our other demo sets.

It's much larger than the Library data set. This actually works better than I thought (after the initial load) at this scale:
- around 13k movies, 
- over 150k movie-related people,
- multiple many-to-many mapping tables with over 100k rows

The movie set was sanitized by checking titles, taglines, and descriptions against https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words . This was quite aggressive, and deleted many movies from the data set that probably could have stayed. However:
- this is just test data
- I ran out of time budget for hand-sanitizing the data.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
Note to the reviewer: To actually look at the data in this PR, you'll have to unzip the SQL file locally.

**Comment by kgodey** [comment]
I've got a lot to do today so I'm just going to merge this, deploy it, and look at it on the live demo server. We can make changes in later PRs if needed.

**Comment by kgodey** [comment]
I merged and deployed this to the demo server and it looks great! We do need to add some pre-configured explorations.

**Comment by mathemancer** [comment]
> Also, what is the best way to wipe out old sessions?

I've been doing it manually on occasion. Truncate the mathesar sessions Django table, and knock out all non-default user DBs.

**Pull request merged**
