### PR TITLE
One SQLAlchemy operation per function

### LINKED ISSUE #1096: Reduce db functions to one SQLAlchemy operation per function
## Problem
We have decided to use `attnums` when passing a column reference as arguments but most of the SQLAlchemy operations use column name, so we need to fetch the column name before an SQLAlchemy operation, this can lead to referencing a wrong column in case there are multiple SQLAlchemny operations within a single function and one of those happens to change a column name.

## Proposed solution
Each function should use only one SQLAlchemy operation so a column name altering operation won't have any effect on other operations.

### PR DESCRIPTION
**Pull request by Anish9901**
Related To #1096

This PR reduces each function to have only one SQLAlchemy operation.

**Technical details**

Currently, in the function `_batch_alter_table_columns` in `db/columns/operations/alter.py`, there are two SQLAlchemy operations. This might cause referencing a wrong column. So this PR  splits the function `_batch_alter_table_columns` to separate functions with only one SQLAlchemy operation.
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by mathemancer — CHANGES_REQUESTED** [review]
Great work on this. 

This could be merged in its current state, but I'm not comfortable claiming that it "Fixes #1096 " without a test to verify that. Writing such a test is likely to be pretty technical. If you feel up to it, I encourage you to write such a test. Otherwise, please change the description to say "Related to #1096 " so that the issue stays open until we write the appropriate test.

**Comment by Anish9901** [comment]
@mathemancer I'll try to write some test cases.

**Comment by silentninja** [comment]
@mathemancer Can you give a rough idea of how the test should work or be implemented. I can only think of a test case that is fairly complex which involves mocking and inferring mocked calls.

**Comment by silentninja** [comment]
I agree with @mathemancer comment. Other than that the PR looks good to me

**Comment by mathemancer** [comment]
> @mathemancer Can you give a rough idea of how the test should work or be implemented. I can only think of a test case that is fairly complex which involves mocking and inferring mocked calls.

I'd agree on the single test case. I suppose it could be method by method, but I'd want those individual "cases" to be generated to ensure we don't forget to make a new one when we make a new method. The way I imagine it would be to use the `ast` module to parse each source file (or maybe you could go for top-level imports; not sure if `ast` will go into the files imported or not) for function definitions and imports. Catch any import from `sqlalchemy.*` or `alembic.*`, and then look for `Call` objects with one of the imported names within function definitions, making sure there's at most one per `def`. 

As I said, this will be quite technical, and even the version I described doesn't take branching within functions into account; it's fine if some function has more than one SQLAlchemy call, as long as they're in mutually-exclusive logical branches within the function.

The goal would be for the test to fail if any function calls more than one unwrapped SQLAlchemy method, and as a bonus, would list the offending functions.

**Comment by Anish9901** [comment]
@mathemancer I have updated the PR description as "Related To" we can work on the tests later.

**Review by mathemancer — APPROVED** [review]
This looks good with the modified description.

**Pull request merged**
