### PR TITLE
Test Cases to Ensure that we can set, get, and delete default values for all types

### LINKED ISSUE #1064: Ensure that we can set, get, and delete default values for all types
## Problem

We need to make sure that we can set, get, and delete default values for all supported DB types.

## Proposed solution

Ensure that tests exists for this functionality for all supported DB types, write new ones if needed.

## Additional context

If support for any DB types are not yet complete by the time this issue is complete, then responsibility for writing tests for those types falls on the person implementing the type.

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #1064 

Adds test cases to verify if defaults values for all supported DB type work.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Additional Context
- Blocked by #1157 

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by silentninja** [comment]
@mathemancer I am having a problem with getting the proper default value for `DateTime` types.

 The default value from the cast string is of the correct format(using `db.columns.operations.select.get_column_default`) but, when using `db.tests.columns.utils.get_default` returns a `datetime` object instead of a string. An example test case is `db.tests.columns.operations.test_select.test_get_column_default`.

 Can you have a quick look and see if I am missing something

**Comment by mathemancer** [comment]
The problem is that you are doing tests that seem to avoid using the engine with the added custom types. If you don't inject the custom (python) types, it won't do the processing that formats the date/time/interval values correctly.

What are you hoping to achieve with those tests?

**Comment by silentninja** [comment]
> What are you hoping to achieve with those tests?

I am trying to test if the default values are stored correctly and returned correctly when mathesar custom types are installed as well as when they are not installed. 

>   If you don't inject the custom (python) types, it won't do the processing that formats the date/time/interval values correctly.

`column_test_dict_with_engine` is a tuple of `engine` and expected output for that engine. For example
```
('engine_with_schema', <class 'db.types.datetime.DATE'>, {'start': '1999-01-15 AD', 'set': '1999-01-18 AD', 'expt': datetime.date(1999, 1, 18)})
('engine_email_type', <class 'db.types.datetime.DATE'>, {'start': '1999-01-15 AD', 'set': '1999-01-18 AD', 'expt': '1999-01-18 AD'})
```
In the first case, the test passes as the column `default SQL string cast == db.tests.columns.utils.get_default`
But in the second case when using an engine that has mathesar installed by running `install_mathesar_on_database`.  The response from the `db.tests.columns.utils.get_default` is still the same `datetime` object instead of `string` which we get from the default SQL string cast

**Comment by mathemancer** [comment]
> > What are you hoping to achieve with those tests?
> 
> @mathemancer I am trying to test if the default values are stored correctly and returned correctly when mathesar custom types are installed as well as when they are not installed.

The engine being used defines which _python_ types are available to the engine, not what's installed on the DB. It's two separate things. The date/time/interval formatting doesn't depend on anything being installed on the database (I went to a lot of trouble to ensure that :smile:). It _does_ depend on the `ischema_names` map containing the custom python types, since those do all the formatting. We should always use the engine with the updated `ischema_names`. Hope that clears things up.

**Review by mathemancer — APPROVED** [review]
Okay, this looks good to me.

**Comment by mathemancer** [comment]
@silentninja I'll leave this to you to merge until the previous PR is merged.

**Pull request merged**
