### PR TITLE
Removed the rows which are common in savedRecords and newRecords

### LINKED ISSUE #1287: Deleting existing rows duplicates newly added rows
## Description
* Open a table with few rows so that there is only one page of rows. Say 10 rows.
* Add a few new rows. Notice the new rows highlighted in green.
* Delete a few existing rows, notice that the rows get refreshed and new rows are loaded in place of deleted rows.
* Notice that the previously added new rows which are duplicates do not get removed.

Resulting in this state:
Screenshot 2022-04-15 at 12 25 24 AM

## Expected behavior
Duplicates from the newly added rows should get removed.

This was one of the cases previously handled, there might have been a recent regression. Anyone working on this issue must add integration tests for this scenario.

### PR DESCRIPTION
**Pull request by nk183**
Fixes   #1287 

Removes the duplication of new added rows on deletion any row of the table

**Technical details**

Removed the rows which are common in savedRecords and newRecords

**Screenshots**

https://user-images.githubusercontent.com/58779460/166448742-847d43d9-5562-469b-bc7c-1b4f0a66ff01.mp4

https://user-images.githubusercontent.com/58779460/166448753-bc24c656-f313-476f-b8ad-5b0e07513b96.mp4

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by nk183** [comment]
hi @pavish  I have created this draft PR, Please review

**Comment by pavish** [comment]
@nk183 Your changes would break the functionality mentioned in [Scenario 2 of the comment on the issue](https://github.com/centerofci/mathesar/issues/1287#issuecomment-1109844135).

We shouldn't be removing the existing logic which is in place to handle removing of duplicated entries. There is a bug in this logic causing the issue, which should be analyzed and fixed.

**Comment by nk183** [comment]
hi @pavish can you review the pr

**Review by seancolsen — APPROVED** [review]
Looks good, @nk183. I added one commit with some minor code cleanup and I'm setting this PR to merge on pass.

**Pull request merged**
