### PR TITLE
Stop proxying, put version in common_data

### LINKED ISSUE #2492: Stop proxying Github Release API (and put current release tag name in common_data)

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #2492

Adds the current release tag name to `common_data`: https://github.com/centerofci/mathesar/pull/2493/files#diff-4bdc06f60f579b8afb7fe1df437fdc953964e741b95e91e6ccdd085bac7955faR113

Redefines the `/api/ui/v0/version/current/` endpoint to only return the current release tag name.

Removes the `/api/ui/v0/version/latest/` endpoint.

Removes all logic related to querying Github Releases API: https://github.com/centerofci/mathesar/pull/2493/files#diff-f7b264c426cd99e5dbaae9240266d1fda5a8c14c1b7cdddfd092c2efc7dbd2d0L18

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dmos62** [comment]
@seancolsen I said I'll link to how I was querying Github Releases API. Here's that code (it's being removed by this PR): https://github.com/centerofci/mathesar/pull/2493/files#diff-f7b264c426cd99e5dbaae9240266d1fda5a8c14c1b7cdddfd092c2efc7dbd2d0L18

**Comment by dmos62** [comment]
Tested.

**Review by seancolsen — APPROVED** [review]
I have been working on top of this and would like to merge it. I can see the tag name is in common-data, although it's hard for me to test comprehensively until we have a release which corresponds to a tag name that the back end is setting in common-data. But in any case, I think we ought to merge this and keep moving forward.

**Comment by kgodey** [comment]
@seancolsen I set it to merge. @silentninja, please review retroactively.

**Pull request merged**
