### PR TITLE
API support for Moving columns between related tables

### LINKED ISSUE #1431: Add API support for moving columns
## Problem
Add support for moving columns between related tables.
## Proposed solution
We already have db functions that handle the logic for moving columns between related Tables, we need to create a new Django API that builds on top of those functions.

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #1431 

Adds API support for moving columns between related tables. 

Note: The PR does not convert the parameters of the `move_columns_between_related_tables` function to use database identifiers like `oid` and `attnum` instead of `names` due to a lot of changes required in functions like `move_columns_between_related_tables` that make use of `move_columns_between_related_tables` I will be addressing the conversion from name to oid in a different PR.

**Technical Details**
The API schema for moving columns between related tables

```typescript
// POST /tables/{id}/move_columns/
interface MoveColumnRequest {
        'move_columns': number[],
        'target_table': number,
}

// returns 201

```

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by silentninja** [comment]
This PR uses some utility function from PR #1431, so I am marking it as a draft until the parent PR gets merged. But it can be reviewed even if it is blocked

**Review by mathemancer — APPROVED** [review]
I think this looks good, though I think we should consider combining these action endpoints in a future PR (as previously discussed).

**Review by seancolsen — CHANGES_REQUESTED** [review]
## Issue 1 -- response status code

- I see that the HTTP response status code is 201 but I think 204 would be more appropriate since there is no content in the response body. What do you think about changing it?

## Issue 2 -- echos of a terrible and elusive bug which has been haunting me for months until only now I am finally able to reproduce!!!

Bear with me here. This bug may be only be tangentially related to this PR, but it's important because when it presents itself, it renders Mathesar completely inoperable even after restarting Docker. The only way I have found to recover from this bug is to wipe my `.volumes` folder and re-install Mathesar.

Here are the steps to reproduce, using the code in this PR:

1. **Begin with a fresh installation of Mathesar.**

    Sorry for the inconvenience, but I'm going to great pains to make the reproduction steps as deterministic as possible, given the difficulty I've had in isolating this bug in the past. This time, I've been able to reproduce it twice in succession on my machine using the steps below. Plus, with a fresh installation, all the requests in my reproduction steps can be sent verbatim with the ID values I used too.

1. Use the UI to load `books_sim.tsv` and view the table.

1. Use a REST client to extract the author's first and last name columns.

    ```http
    POST http://localhost:8000/api/db/v0/tables/1/split_table/
    Content-Type: application/json

    {
      "extract_columns": [4, 5],
      "extracted_table_name": "extracted_author",
      "remainder_table_name": "books_remainder",
      "drop_original_table": false
    }
    ```

1. Load http://localhost:8000 to view the new tables in the UI.

1. Click on `books_remainder` to open the table in a Mathesar tab.

1. Click on `extracted_author` to open the table in a Mathesar tab.

1. Use a rest client to move the author's website column from `books_remainder` to `extracted_author`.

    ```http
    POST http://localhost:8000/api/db/v0/tables/3/move_columns/
    Content-Type: application/json

    {
      "move_columns": [6],
      "target_table": 2
    }
    ```

1. Send

    ```http
    GET http://localhost:8000/api/db/v0/tables/2/records/?limit=500&offset=0
    ```

    Observe this [error response](https://gistpreview.github.io/?13c63c2786ef1d1a20d05fe025da25b5).

1. Send

    ```http
    GET http://localhost:8000/api/db/v0/tables/2/constraints/?limit=500
    ```

    Observe this [error response](https://gistpreview.github.io/?245f1e2f0657eacac531db4d58e50ca1).

1. Load the UI via http://localhost:8000/

    Observe this [error response](https://gistpreview.github.io/?12e47ee169fd93f5178454aa7ddc009b). This is the main symptom of the bug that I've been encountering periodically over the past several months.

    > get() returned more than one Column -- it returned 2!

Godspeed. I really hope someone from the backend team is able to reproduce this because steam shoots from my ears whenever I see that error message above. I'm attaching my [`.volumes` directory](https://github.com/centerofci/mathesar/files/8960790/volumes.zip) in case it helps to reproduce.

I'm open to moving this conversation to a dedicated ticket (outside of this PR) if people think that would aid discussion.

**Comment by silentninja** [comment]
Looks like we forgot column when fixing #876. We need to add unique constraint to columns just like how #1293 does it for tables

**Comment by mathemancer** [comment]
> Looks like we forgot column when fixing #876. We need to add unique constraint to columns just like how #1293 does it for tables

This is correct. @silentninja , given that it's a 4-line change, do you want to put it in this PR or just create a separate issue?

**Review by seancolsen — APPROVED** [review]
This is working for me now! Woohoo!

It would still be nice to change the HTTP response code, but I think it's fine to merge without that change.

**Comment by mathemancer** [comment]
I think I'm fine with this PR. @silentninja go ahead and merge when ready, unless you specifically want me to look at something.

**Pull request merged**
