### PR TITLE
Add default display names for summarization output aliases 

### LINKED ISSUE #2063: Better names for backend default summarization aliases
Related: #1812

Expectations described here: https://github.com/centerofci/mathesar/issues/1812#issuecomment-1343349433

Below is my summary; note, I replaced mentions of `initial_column` with `input_alias`, also, removed mention of count aggregation, because backend does not create such aliases:

> Grouped columns: <input_alias_display_name> group
> Array aggregation: <input_alias_display_name> list

Some technical details:

Backend currently does not provide default display names (when it's finishing specifying a summarization); it only provides default aliases. So the aliases will stay the same, but backend will create above-specified display names.

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #2063

Adds default display names into `display_names` for:

- Initial column aliases, based on originating column names;
- Summarization grouping-generated aliases, based on input alias' **display name** with ` group` suffixed (e.g. `Author id group`);
- Summarization aggregation-generated aliases, based on input alias' **display name** with
  - ` list` suffixed, in the case of `aggregate_to_array` function (e.g. `Article list`);
  - ` count` suffixed, in the case of `count` function (e.g. `Article count`).

Note, this implies that if the input alias of a, say, grouping-generated output alias does not have a display name, backend will not generate a display name for the grouping-generated output alias. Also, if the grouping-expression input alias is also an input column alias, the output alias will always get a default display name, because the input column alias will always have a display name.

For an illustration, see [here](https://github.com/centerofci/mathesar/pull/2078/files#diff-692d8111c4d1c54debeb716940fb6945fd2904c2767e3e680a1c36db593ac439R159) how in the resulting query all aliases (2 initial column aliases and 2 summarization output aliases) have display names, even though no display names were specified in the request.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dmos62** [comment]
Draft, until I add/fix some tests.

**Comment by dmos62** [comment]
@silentninja or whoever eventually will review this code; how do you feel about moving the bulk of new code from `mathesar/models/query.py` into something like `mathesar/models/query/default_display_names.py`?

**Review by silentninja — APPROVED** [review]
Looks good to me

**Comment by silentninja** [comment]
> how do you feel about moving the bulk of new code from mathesar/models/query.py into something like mathesar/models/query/default_display_names.py?

How are you planning to do it? Will you be extracting the private function to a different module and calling them from `mathesar/models/query.py`?

**Comment by dmos62** [comment]
> > how do you feel about moving the bulk of new code from mathesar/models/query.py into something like mathesar/models/query/default_display_names.py?
> 
> How are you planning to do it? Will you be extracting the private function to a different module and calling them from `mathesar/models/query.py`?

Yes. I think I'll merge this and create a more general issue/s to split up our model logic into more files.

**Pull request merged**
