### PR TITLE
Update documentation styles for active and hover

### PR DESCRIPTION
**Pull request by ghislaineguerin**
This PR addresses @seancolsen comments on [#documentation](https://github.com/centerofci/mathesar/pull/2907) regarding on hover and active states for navigation and table of contents.

### CODE REVIEW

**Comment by kgodey** [comment]
I only have one thing to add to @seancolsen's review, which is that on dark mode, the "current page" styling is the brightest thing on the page and draws my attention too much. It looks like the primary action item on the page, whereas it should just be a subtle indication of "you are here".

Screen Shot 2023-06-12 at 5 22 41 PM

**Review by kgodey — CHANGES_REQUESTED** [review]
Please see main comment in thread.

**Review by seancolsen — APPROVED** [review]
Looks good! Thanks.

**Review by kgodey — APPROVED** [review]
Looks great, @ghislaineguerin!

**Pull request merged**
