### PR TITLE
Prefetch SQLAlchemy Table when fetching a list of Django Tables

### PR DESCRIPTION
**Pull request by silentninja**
Related to #802 

PR improves performance when fetching multiple tables by prefetching the underlying SqlAlchemy tables in bulk instead of fetching each table object during serialization. 

**Technical details**
I have added a modified version of the `django-prefetch` library which is serving as a temporary duct tape for prefetching. I would be replacing most of that code in future PR, so the review can be skipped for the `utils/prefetch.py` file

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@silentninja if you're including code from a third-party package, you'll need to include the appropriate license. See https://github.com/centerofci/mathesar/blob/master/THIRDPARTY, you can follow that format.

**Review by kgodey — DISMISSED** [review]
Please see comment about license

**Comment by silentninja** [comment]
> @silentninja if you're including code from a third-party package, you'll need to include the appropriate license. See https://github.com/centerofci/mathesar/blob/master/THIRDPARTY, you can follow that format.

I made the necessary changes, thanks

**Review by dmos62 — APPROVED** [review]
Good work! As instructed, didn't review `mathesar.utils.prefetch`. I found the `Prefetcher(...)` instantiation a bit hard to understand, even having read `django-prefetch`'s README. The comments you added have been helpful! It would be great if you could add even more comments/docstrings in future PRs.

**Pull request merged**
