### PR TITLE
Added favicons to the platform by searching for the Font-Awesome icon…

### LINKED ISSUE #1520: Customize page favicons
## Current behavior

- All pages have the same favicon

## Desired behavior

- Our [Navigation Specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/navigation.md#navigation-via-page-url) require that we use distinct favicons for pages that represent different types of entities.

## Implementation

1. Review specs to see which entities require custom favicons.
1. Look in `src/icons.ts` to find the correct FontAwesome icons for those entities.
1. Generate custom favicons based on the FontAwesome icons. I like to follow [this guide](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) for favicons, but we could probably get away with just using the SVG. Which browser's don't support SVG favicons these days? It might be good to look.
1. Use `<svelte:head>` to modify the HTML `<head>` element from within components like `TablePage.svelte`

## See also

- #3605 which is simpler (just one static favicon) and higher priority

### PR DESCRIPTION
**Pull request by IyadElwy**
…s, downloading, encoding and saving their svg, then saving the favicon element as svelte components and inserting them as needed

Fixes #1520

**Technical details**

**Screenshots**

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by seancolsen — CHANGES_REQUESTED** [review]
Nice work on this, @IyadElwy. The end result seems to behave well in Firefox and Chrome.

I'd like to clean up some of this code before merging though...

Your use of `data:image/svg+xml` is clever, and I think this approach should work well, even though it's not quite what I had mind. I was thinking we'd save plain old `.svg` files that the browser would request. If that were to be the implementation strategy, then placing those `.svg` files within `static-assets` would be appropriate. However, since we are using `.svelte` components instead, placing them in `static-assets` would be unconventional.

Here's what I'd like to do instead:

- Make a new `Favicon` component which lives at `src/components/Favicon.svelte`

    - Just like our `Icon` component, the `Favicon` component should accept a `data` prop as follows:

        ```ts
        export let data: IconProps['data'];
        ```

    - Then, the `Favicon` component should render that `<link>` tag as you've set it up in your favicon files.
    
    - It should use logic similar to `Icon` to build the paths in the svg. Because it needs to build it all into one string, you can use template literals.
    
    - Then you can either replace the angle brackets with their escaped equivalent, or you can encode the whole string as base64.

- Delete your new files in `static-assets`.

- Where you currently have code like

    ```svelte
    <FaviconTable/>
    ```

    We'd instead use

    ```svelte
    <Favicon {...iconTable} />
    ```

    This makes the favicon system more composable, allowing us to make use of the icons that we have already defined in `src/icons/index.ts`, some of which are now custom.

- So after all those changes, your PR would end up adding only one new file (`src/components/Favicon.svelte`), and modifying the `*Page.svelte` files you've already modified. Are you up for making these improvements?

- Also, make sure to run the [code formatting](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/README.md#formatting) when you're done with your changes.

**Comment by IyadElwy** [comment]
Did you have something like this in mind ?

```svelte
<script lang="ts">
    import {IconProps} from "@mathesar-component-library/types";

    export let data: IconProps['data'];

    let path: String = '';
    $: [path] = data.icon;

</script>

<link rel="icon"
      href="{path}"
      type="image/svg+xml"/>


```

**Comment by seancolsen** [comment]
@IyadElwy 

> Did you have something like this in mind ?

Yes, something like that. Building the path will require some more work, but yes, you're on the right track.

**Comment by pavish** [comment]
@IyadElwy Are you still working on this PR?

There hasn't been any activity for over three months now and we might have to close this PR if we don't hear back from you. We'll wait for 3 more days (Monday, 2023-03-20 EOD Eastern Time) and close this PR if we don't receive further communication from you.

**Comment by pavish** [comment]
Closed due to inactivity.

**Pull request closed without merging**
