### PR TITLE
Throw targeted error message for columns not longer present in the Query

### LINKED ISSUE #1596: Provide targeted error messages when tables & columns involved in an exploration are no longer present
* Create a new exploration with a base_table and some initial columns
* Delete some of the columns in the table directly
  - Notice that the API responds with a 500 error code
* Delete the table which is the base_table of the query
  - The query also gets deleted
  - We need to show these in the warning message while prompting for user confirmation
* Delete a linked table whose columns we use as initial_columns in the query
  - The API responds with a 500

Expected:
* The frontend needs to show the columns and highlight the ones that are no longer present
* The API response needs to provide both the column structure and targetted errors

### PR DESCRIPTION
**Pull request by silentninja**
Related to  #1596 

The PR aims to fix the errors related to two of the scenarios
- The `base_table` gets deleted - Frontend should check if the Table has dependencies and ask the user to fix the related query before deleting the Table.
- A column in `initial_columns` is deleted - Error is thrown along with the query and the `column id`. I am not able to find a way to get the `column` property as it needs the actual column object which is not possible once the column is deleted. 

**Technical Details**

The response for 
`GET` request to `/tables/<id>/ui_dependents/` is
```
{
    {
        'queries': [
            query_id: int
        ]

    }
```

The error response when an initial column is deleted is
```
 {
  'query': # Same as query object sent by the frontend
  'column_id': int //missing column id
}
```
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by silentninja** [comment]
@pavish Can you check if the response can be used for throwing the error message? The backend won't be able to return `output_column` or `column_metadata` as we need the actual `Column` object to construct those properties which is not possible with a deleted Column.

**Review by dmos62 — COMMENTED** [review]
I don't have technical comments.

**Comment by pavish** [comment]
@silentninja We will be able to construct the error message with this response. However, it looks like we can only show the first missing column based on your response. Is my assumption correct, or is there a way to get all the missing columns, when there are multiple `initial_columns` missing?

**Comment by pavish** [comment]
@silentninja Is this waiting on me? I have provided my [comment above](https://github.com/centerofci/mathesar/pull/1905#issuecomment-1312766996), and I would like the response to return all the missing columns instead of the first one.

**Comment by silentninja** [comment]
> We will be able to construct the error message with this response. However, it looks like we can only show the first missing column based on your response. Is my assumption correct, or is there a way to get all the missing columns, when there are multiple `initial_columns` missing?

You are right, the error response would contain only the first missing column. I see this PR as a temporary fix, long term I would want the user to figure out what to do with these dependents using the dependency API, which is a much better UX.

When a column has been deleted the query that uses the column does not make sense, in most cases queries are created with a context related to the columns. For example, If I had a query for "Books with a name starting with 'A'" and the column `name` gets deleted, then the query is meaningless. 

I would prefer a proper use case before going too deep into this as it would slightly complicate how things are done on the backend.

**Comment by pavish** [comment]
@silentninja 

> I would prefer a proper use case before going too deep into this as it would slightly complicate how things are done on the backend.

I am confused by this. I agree that the query is meaningless, the idea is to show the user information for them to fix the query.

The UX we have is that when columns are missing, we indicate to the user that the columns are missing and we provide an option to them to delete those intial_columns from the query. The above error with only the first missing column would not satisfy the UX.

Reference: [Figma link](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1616%3A26083)

**Comment by dmos62** [comment]
@silentninja @pavish I feel like a sync call is warranted.

**Comment by silentninja** [comment]
@pavish We agreed upon showing errors for a single column during the weekly meeting. If you are satisfied with the response can we merge this PR?

**Comment by pavish** [comment]
@silentninja Yes please, I wasn't aware this was waiting on me.

**Review by pavish — APPROVED** [review]

**Pull request merged**
