### PR TITLE
Add autoincrement to existing integer primary key column of an import

### LINKED ISSUE #2144: ID sequence isn't being created for tables
## Description

I cannot add a new record to a new table because the ID does not have a default value. I set up this table by:
1. Importing [library_books.tsv.zip](https://github.com/centerofci/mathesar/files/10273401/library_books.tsv.zip) as "Items"
2. Pulling "Author First Name" and "Author First Name" into an "Authors" table
3. Moving "Author Website" to "Authors" table
4. Pulling "Publishers" into a "Publishers" table
5. Pulling "Title", "Publication Year", "ISBN", "Authors_id", and "Publishers_id" into a "Books" table

## Expected behavior

I should be able to add a new record!

## To Reproduce

~Try adding a new record on https://library.mathesar.org/mathesar_tables/4/tables/34/~

I needed to nuke this table since it was blocking my work. To reproduce, follow the steps under Description.

## Additional context

This seems related to
- #2116 
- #1356

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #2144 

Removes disabling `autoincrement` when a dataset contains a default `id` column,  instead always update the default 
 pk column sequence to the max value of the column when exporting.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by mathemancer — CHANGES_REQUESTED** [review]
This will break if the user's ID column non-integer, e.g., ISBN, UUID, Dewey, URI, etc.

I suggest a different approach:

If the user uploads a CSV with an `id` column, and it's not an integer, rename it to `id_old` (or something) and create our usual ID column. I see no reason to assume an `id` column of sequential integers will be the norm for user-provided data.

**Comment by kgodey** [comment]
@silentninja @mathemancer what's the status of this PR?

**Comment by silentninja** [comment]
I don't like the idea of changing the `id` field to `original_id`
1. It modifies the imported data without informing the user.
2. The user might want the existing `id` column from the imported data to be the actual primary key for various reason. For example, if the CSV files are relation, I would want to use the existing `id` column, so the references in other imported csv files are intact.

Alternate solutions that I can think of are
1. Revert back to calling the primary key column as `mathesar_id`. This prevents all the unnecessary problem
2. Have a toggle button that lets the user choose if we should use existing foreign key column or create a new one.

I considered other options but those are not feasible given our time constraints

**Comment by silentninja** [comment]
> If the user uploads a CSV with an id column, and it's not an integer, rename it to id_old (or something) and create our usual ID column

@brent the problems mentioned by you can still happen with `INTEGER` column, for example, Dewey can be represented as INTEGER column.

**Comment by kgodey** [comment]
@silentninja I don't think it's a problem to add a new `original_id` field. We are not deleting any user data. If the user wants to use their original column as the primary key, they can configure it that way after import.

Responses to your solution:
> 1. Revert back to calling the primary key column `mathesar_id`. This prevents all the unnecessary problem

This means that if they use their data outside of Mathesar, it will still have the "mathesar" name. That's worse.

> 2. Have a toggle button that lets the user choose if we should use the existing foreign key column or create a new one.

We'll need additional UX and frontend work for this, which will delay release further. This is not something critical enough to delay release on.

**Comment by kgodey** [comment]
@silentninja The user can use the constraints modal to add/remove constraints. I'm not sure if we support adding/removing primary key constraints yet, but if not, we can add that in the future.

**Comment by silentninja** [comment]
Okay, I will make the necessary changes.

**Comment by silentninja** [comment]
@mathemancer On checking further, the behaviour you proposed seems to be the existing behaviour. Our current behaviour is 
1. We create an empty Table based on the csv dataset
2. If the created Table contains an `id` column Replace the `id` column with an `INTEGER` column
3. Try inserting the data
4. If it fails remove the Table and create a new Table with `id_original` column.

**Comment by kgodey** [comment]
@silentninja If we already have this behavior, why do imported CSVs with the `id` column not have the sequence set correctly?

**Comment by silentninja** [comment]
> "This will break if the user's ID column non-integer, e.g., ISBN, UUID, Dewey, URI, etc.

> I suggest a different approach:

> If the user uploads a CSV with an id column, and it's not an integer, rename it to id_old (or something) and create our usual ID column. I see no reason to assume an id column of sequential integers will be the norm for user-provided data."

@kgodey My reply was to the alternate behaviour mentioned above by @mathemancer. We already rename the existing `id` column to `original_id` if the column does not have a integer data

**Comment by kgodey** [comment]
@silentninja Okay, thanks. This PR isn't ready for review yet, right?

**Comment by silentninja** [comment]
> Okay, thanks. This PR isn't ready for review yet, right?

This PR does not need any changes so I changed the tags to review, sorry for not doing it earlier.

**Comment by kgodey** [comment]
Okay thanks @silentninja

**Comment by mathemancer** [comment]
> @mathemancer On checking further, the behaviour you proposed seems to be the existing behaviour. Our current behaviour is
> 
> 1. We create an empty Table based on the csv dataset
> 2. If the created Table contains an `id` column Replace the `id` column with an `INTEGER` column
> 3. Try inserting the data
> 4. If it fails remove the Table and create a new Table with existing `id` column to `id_original` column and create a new `id` column
> 
> Edit: The only change this PR adds is to set a sequence in case the existing `id` column has `Integer` data values.

Cool, thanks for the info.

**Review by mathemancer — APPROVED** [review]
@silentninja is right; this already works as I suggested. Sorry for the confusion.

**Pull request merged**
