### PR TITLE
Improve front end docs

### PR DESCRIPTION
**Pull request by seancolsen**
- @pavish [suggested](https://github.com/centerofci/mathesar/issues/880#issuecomment-1000097399) we put some of the "writing tests" content from a [comment of mine](https://github.com/centerofci/mathesar/issues/880#issuecomment-999808482) into our front end README file. This PR does that.
- This PR also adds some other content from recent discussions and does some clean up of the README too.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
I'm wondering if some of this would make sense in our wiki instead. We have some [backend specific guidance](https://wiki.mathesar.org/engineering/code-review/backend,) already there as well as [code review guidelines](https://wiki.mathesar.org/engineering/code-review) and [engineering decisions](https://wiki.mathesar.org/engineering/decisions). You could also update documentation there without requiring a PR.

I don't have a specific suggestion for what to move, I only wanted to bring up the wiki in case you hadn't considered it.

**Comment by seancolsen** [comment]
@kgodey I did consider that. I don't have an opinion on where it should go. I just wanted to improve the content we had and this is where it was so I kept it here. I'm fine with moving it to the wiki. If you'd prefer it to be on the wiki feel free to close this PR and I'll open a new PR which moves this sort of content to the wiki and points readers there.

**Comment by kgodey** [comment]
@seancolsen I don't have a preference, I'll leave it to you and @pavish. I'd err on the side of improving the content first, we can always move stuff to the wiki later.

**Review by pavish — APPROVED** [review]
@seancolsen Thanks! The updates looks great. I agree with @kgodey that we may want to move some of the detailed content to the wiki, but we can merge this PR now and get to that later.

**Pull request merged**
