### PR TITLE
Disable all inputs while the form is processing #2132

### LINKED ISSUE #2132: Modify form system to disable all inputs while the form is processing
- (A) When adding a new column, we have a small form in a dropdown (`NewColumnCell.svelte`). This form disables its inputs while loading. This pattern is nice and we should employ it at a lower level so it is used throughout the app.

- (B) On the Record Page, we use the form system to save field values for the record. This form does _not_ disable its inputs while the form is loading. It should.

- We should make changes within `src/components/form` so that (B) has the same user experience as (A) (disabled inputs while loading). Then we should remove the code from (A) which manually sets the inputs to disabled -- thereby giving (A) the same developer experience as (B) (no need to think about disabling inputs while the form is loading).

- Notice that on the Record Page the `id` field is disabled even when the form is _not_ loading. We should ensure that this behavior remains.

### PR DESCRIPTION
**Pull request by DanyaalMahmood**
Fixes #2132 

This PR changes the behavior of the form in the record page. When the form is loading the inputs are disabled. 

https://user-images.githubusercontent.com/110989303/223845785-9e749313-7e23-4b1f-b073-b40d339f7a36.mp4

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by DanyaalMahmood** [comment]
Hey @seancolsen could you please rerun the tests.

**Comment by seancolsen** [comment]
@DanyaalMahmood I've re-run them. You can also run them locally by following the instructions in our [README](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/README.md)

**Comment by DanyaalMahmood** [comment]
@seancolsen the tests are failing due to sqlalchemy throwing errors that there are too many clients already. I don't think it's related to anything that this PR changes. What should I do?

**Comment by seancolsen** [comment]
@DanyaalMahmood Don't worry about those. I'll have someone from the backend team take a look. Nothing else for you to do now other than to wait until I have time to review this. There are a number of other things ahead of this task in my queue. I'll probably get a chance to review it sometime next week.

**Comment by DanyaalMahmood** [comment]
Alright. Thanks

**Review by seancolsen — CHANGES_REQUESTED** [review]
Your approach of exporting a writable store here is not great.

```ts
export const disableInputs = writable(false);
```

This makes that property global, meaning that if one page has two forms, all inputs on both forms will be disabled when only one form is being submitted.

Instead, we should have a writable property as part of the form object.

**Comment by DanyaalMahmood** [comment]
@seancolsen I've made the changes you requested. I have given the form object a writable property for disabling inputs. Now only the inputs for the form being submitted will be disabled.

**Comment by seancolsen** [comment]
Thanks @DanyaalMahmood. I'll review this when I get a chance. Hopefully it will be this week.

**Comment by seancolsen** [comment]
@DanyaalMahmood You've done a good job with this PR. I spent some time looking at it but I wanted to take this in a slightly different direction. I'm closing this PR in favor of #2762.

I know I told you:

> we should have a writable property as part of the form object.

But once I took the time to get my head deeper into this problem, I realized that wasn't _exactly_ the cleanest way to do this. Your PR requires that we manually grab the `disableInputs` property out of the form object and pass it around as needed. This is some extra work at a high level that I'd rather handle automatically at a lower level to avoid mistakes.

In my PR, I am using a `disabled` store on each field object, and reactively updating that store when the form's `requestStatus` changes. From the perspective of consumers of the form system, very little is different from before. Consumers need not think about any disabled properties, so long as they're using the `<Field>` component because each field store now comes with the `disabled` property. I did need to ensure that forms without error handling were also updating the `requestStatus`, but this is something we would have needed to fix in your PR too. There were also a few input types that didn't properly respond to being disabled, so I had to fix that as well.

Apologies that I took over this work. You can still count this as a contribution for GSoC purposes.

**Pull request closed without merging**
