### PR TITLE
Added resize functionality to the side inspector view

### PR DESCRIPTION
**Pull request by RyanWalker277**
Related to #2362 

**Technical details**
I have added a new function named move and another named resize in the original code. The resize function, creates a grabber div element and adds it to the element passed to the function as an argument. It then attaches event listeners to the grabber for mousedown, mouseup, and mousemove events. When the mousedown event is fired, it sets the active variable to the target of the event, calculates the initial position and dimensions of the element, and adds the 'selected' class to the active grabber. When the mousemove event is fired, it calculates the difference between the current position of the mouse and the initial position and adjusts the width and/or height of the element accordingly. Finally, when the mouseup event is fired, it removes the 'selected' class from the active grabber and clears the active, initialRect, and initialPos variables.

**Problems**
The code is not working as expected. The blue line is just for refrence of the scroller area, will remove it in the final stages. I have attached the video for refrence.

[screen-capture.webm](https://user-images.githubusercontent.com/32684077/222057890-caea6f11-10da-463d-a0ee-327fb0d776cf.webm)

I am unable to wrap my head around it. Would appreciate some help.

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Tagging @seancolsen for help.

**Comment by seancolsen** [comment]
@RyanWalker277 Your approach seems to be pretty far off in a different direction from what I predict is needed to fix this issue. Here are some general tips

- Take a look at how the column resizing is done. See SheetCellResizer.svelte. I would not expect the sidebar resizing to be too much more complicated than the column resizing.

- Keep in mind we only need to support _horizontal_ resizing. I see things like `height` in you code. We shouldn't need to worry about any of that.

- We want to end up with a general-purpose component that has a middle area, plus optional left and right sidebars which can be resized. If I were building this, I'd probably begin by building that component in isolation. [We have Storybook set up](https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/README.md#storybook) for this purpose. You might find it easier and simpler to begin building your component in Storybook, though it will entail a small amount of setup/learning. Then you can build a `.stories.svelte` component. Search the codebase for other files like that and you can see how it works.

**Comment by pavish** [comment]
@RyanWalker277 Are you still working on this PR? Do you require any help?

We haven't heard from you on this PR/issue for a while now. If we don't get a response back from you by Monday E.O.D. Eastern time, we'll assume that you're not working on it, and would close this PR and unassign you from the issue.

**Comment by pavish** [comment]
Closing this PR based on the comment on the issue: https://github.com/centerofci/mathesar/issues/2362#issuecomment-1473821882

**Pull request closed without merging**
