### PR TITLE
Type configuration for Text, Number, Boolean, and all mathesar types with single associated db type

### PR DESCRIPTION
**Pull request by pavish**
Related to: 
* #254 
* #255 
* #256 
* #257 
* #258 

The PR handles the `database` options in the data type selection dropdown, for Text, Number, Boolean and all mathesar types with a single db type association.

Screenshot 2022-02-01 at 3 01 51 PM

The discussion [Dynamic Type selection & customization on the frontend #1035](https://github.com/centerofci/mathesar/discussions/1035) provides the declarative format and additional concerns. I advise the reviewers to review this PR after reading the discussion.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dmos62** [comment]
Hey @pavish, I found the title of this PR interesting, but would like to know more. Could you comment on why types with one-to-one type mappings require distinct configuration? I've not looked at the code.

**Comment by pavish** [comment]
@dmos62 Types with 1-1 mapping do not require a distinct configuration for showing a form and determining db type. They require it for showing what kind of input to use in the table cell, icons, validation of input etc., CellInput is not handled in this PR and would be a subsequent PR.

**Review by seancolsen — APPROVED** [review]
After playing with these changes, this PR doesn't appear to break any existing functionality. 

I've looked over the diff and don't see any glaring red flags.

So for the sake of moving fast, I'm merging this.

That said, there are some smaller concerns and questions with these changes that I plan to address through a combination of tickets, subsequent PRs, and sync conversations.

**Comment by pavish** [comment]
@seancolsen This PR does not handle saving the user entered input in the forms on the db yet eg., `Decimal places`, `Field Size limit`etc.,. I'll be raising a subsequent PR for that.

**Pull request merged**
