### PR TITLE
Return foreign key columns summary data when creating or retrieving a single record

### PR DESCRIPTION
**Pull request by silentninja**
The PR exposes the `settings` field for the table, which is needed for editing the summary template of the table as well as for showing the summary of a particular table record.

The PR also extends  #1404  by Adding the `preview_data` field introduced in #1404 to the `create`, `patch`, and `retrieve` methods of the `tables/<id>/records/` API. This is needed for the frontend to display a summary record of a **foreign key column** when a record is fetched individually.

### Technical Details

```json5
get request to any tables endpoint for example `/tables/<id>/` now returns

{
 "id": 1,
 "name": "Checkouts",
  "settings": 
      {
        "preview_settings": 
             {
                 "template": "{1}"
              }
       },
   ...
}
```

- The `get/patch` request to `/tables/<table_id>/records/<id>/`  and the `post` request to `/tables/<table_id>/records/`  will return the same response as `get` request to `/table/<table_id>/records/`.

```json5
//Example schema
{
  "count": 1393,
  "grouping": {},
  "preview_data": [
    {
      "column": 100, // "Items"."Publication Id" colum ID
      
      // The Publications summary template: "Title: {278}"
      // The Authors summary template is: "{280} {281}"
     //
     // `100` is the foreign key column id in the items table, it is constrained to column id `277` which is the `id` column of the Publication Table. Column `278` is the title column in the publication table which is part of the preview template of the Publication Table.
     
      "template": "Title: {100__277__col__278}",
      "data": [{"100__277__col__278": "Blink"}]
      }
   ],
  "results": [
    {"10": 1, "20": 3.50, "100": 23},
  ]
  
}
```

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by silentninja** [comment]
@seancolsen I fixed it, I don't know why the test cases didn't catch the error.

**Review by mathemancer — APPROVED** [review]
I think this looks good from the back end perspective.

**Review by seancolsen — CHANGES_REQUESTED** [review]
I have some minor changes to request for the sake of clarity within the API...

- On `/api/db/v0/tables/<id>/` can we change the `settings` property to be named `display_options` instead?

    Within that property...

    - Why is `id` present? Can we remove it for simplicity?
    - Can we change the `preview_settings` property to be named `record_summary` instead?
    - I've tried modifying the record summary template via a PATCH request, but the new value does not appear to save. If we're handling that via a subsequent PR, that's fine. But if you intend for that modification to work within this PR, then I need more help to understand how to do it.

**Comment by seancolsen** [comment]
Because this PR makes breaking changes to `/api/db/v0/tables/<table_id>/records/<record_id>/` it will need front end changes before merging. I'll take those up after the critique in my review is resolved.

**Comment by silentninja** [comment]
> On /api/db/v0/tables/<id>/ can we change the settings property to be named display_options instead?
> Can we change the preview_settings property to be named record_summary instead?

Is it okay if we can change the property names in a separate PR? I am afraid that it would end up making the PR hard to read or track

**Comment by silentninja** [comment]
> Why is id present? Can we remove it for simplicity?
 I've tried modifying the record summary template via a PATCH request, but the new value does not appear to save. If we're handling that via a subsequent PR, that's fine. But if you intend for that modification to work within this PR, then I need more help to understand how to do it.
 
 Table settings/display_options is treated as a separate resource and it has its own route as specified in #1391. The reason I have gone with a separate route is that it offers better extensibility and since we might be having user settings, it would be better for us to not tightly couple a specific `setting/display_option` to Table

**Review by seancolsen — APPROVED** [review]

**Comment by seancolsen** [comment]
@silentninja, Cool. That sounds fine. 

I've added the necessary front end changes and set this PR to merge on pass.

**Pull request merged**
