### PR TITLE
Import preview page

### LINKED ISSUE #296: Import status indicators
We need clear indication of current uploads, in a prominent manner (Similar to how google drive upload works?). Design spec needs to be revised to handle this.

  - Show current uploads prominently
  - Indicate loading on sidebar
  - Indicate users to not close the browser tab/window
  - Tests

### LINKED ISSUE #524: Switch open tables when schema is changed
As part of #362 and #525, a navigation menu and layout changes are to be implemented to facilitate switching between schemas.

As per our design specs, when schemas are switched, the open tables should change based on the selected schema. This issue is created inorder to track that behaviour.
* Should retain open table information and load based on selected schema
* tabs store needs to be refactored to depend on selectedSchema store

## Additional context
The [schemas design spec](https://wiki.mathesar.org/en/design/specs/schemas).

### LINKED ISSUE #548: Change in url by browser back/forward buttons do not change current db and schema
## Description
When the browser url changes using the back and forward buttons, the current db and schema do not change.

## Expected behavior
The current db and schema should be in two-way sync with the url.

### PR DESCRIPTION
**Pull request by pavish**
Related to #295 
Fixes #296 
Fixes #548 
Fixes #524 

This PR has:
* Refactoring of stores and pages to be schema centric, instead of db
* Preview page for file import
* Import status indicator
* Switches open tables when moving to other schemas/db

Note:
* This PR has all the UI changes needed for the preview page, but there are issues/changes needed with some backend apis.
* This leads to some features not working due to 500s from api calls.
  - Changing column names/types is not working for both:
     - Tried with tables PATCH, as mentioned on import wiki
     - Tried with columns API PATCH (Which is currently used)
  - Updating import_verified is not allowed (Not done at the moment)
* Does not focus much on styling. It will be done incrementally with future PRs.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by kgodey — COMMENTED** [review]
@pavish This looks good to me, but all columns are still showing up as `VARCHAR` instead of the inferred type. It doesn't look like you're looking at the `type_suggestions` endpoint for the table to get the appropriate types for the preview. I don't know if we actually documented that endpoint anywhere, sorry about that.

Do you want to fix that in this PR or a future PR?

**Comment by pavish** [comment]
@kgodey I was not aware of the type_suggestions endpoint. I've marked this PR as related to #295, and not as fixes.
We could create a separate issue for the type_suggestions and I'll pick that up.

**Comment by kgodey** [comment]
@pavish Okay, thanks. I'll create a separate issue for that and merge this PR.

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
I made #568 for the type suggestions work.

**Pull request merged**
