### PR TITLE
Baby steps towards record selector UI

### PR DESCRIPTION
**Pull request by seancolsen**
## Demos and verbal notes

- [Demo 1](https://www.loom.com/share/3eb4d2bd6ba144dcbe034c6c92c9d27f)
- [Demo 2](https://www.loom.com/share/e35efbecfcb241d89756931829a12b75)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@seancolsen I was going to say that you should be able to record videos over 5 min (after I upgraded your Loom account), but it looks like you realized that at the end. Also, nice work!

**Comment by mathemancer** [comment]
Overall, very cool! I have some comments regarding context when working with the record selector:
- It would be quite useful (maybe even crucial) to have the context of which row from the Publications table I'm working with when I've opened the record selector for Authors (as in your demo).
- It would also be quite useful (maybe even crucial) to have the context of what the entry was before when opening the Authors table from the Publications table (i.e., clicking on an already-filled entry in the fkey column should perhaps open a pre-filled record selector, or at least should open a blank one with the current record indicated by the fkey shown or highlighted in some way.

**Comment by seancolsen** [comment]
@mathemancer You've raised two UX design problems that have also been on my mind. I've opened #1446 to attempt further design work that will address these problems. If you have any specific design ideas to suggest, please weigh in by commenting on the ticket. For the sake of incremental development, I'd like to move this PR forward without attempting to resolve those design problems here.

**Comment by mathemancer** [comment]
> For the sake of incremental development, I'd like to move this PR forward without attempting to resolve those design problems here.

Completely agree. My intention was only to start the conversation here since the attached demo videos got me thinking, and do a good job of demonstrating the issues.

**Comment by Anish9901** [comment]
@seancolsen Very cool demos!

**Review by pavish — APPROVED** [review]
@seancolsen Looks good to me.

Apart from the UX questions posed already and the cell selection bug, I have a few minor UI comments/bugs:
* When the linked table is large, the modal fills the entire page's width. It would be better to fix the modal to a specific width.
* Screenshot 2022-07-01 at 12 55 03 PM
 * The date picker seems to open as soon as the modal opens. I assume it's due to the inputs being focused as soon as they are created. We need to disable auto focus here and only focus on the first input manually.
 * The height adjustment appears wonky when the modal first opens and loads. It would be better to fix the height of the modal.
 * We'll have to add a loading indicator.

I'm going to go ahead and merge this PR in. Feel free to raise a separate PR addressing these issues.

**Pull request merged**
