### PR TITLE
Improve UX for FK and PK cell interactions

### LINKED ISSUE #1689: Navigating from a Record Page to another Record Page doesn't work
I tested this using: https://staging.mathesar.org/mathesar_tables/5/44/1267

Mathesar_Home

I would expect that clicking where I highlighted would take me to the Record Page for the checkout. But it doesn't work, I instead have a mostly blank Items Record Page.

Screenshot 2022-09-16 at 17-49-01 Mathesar - Home

### LINKED ISSUE #1713: Improve UX for FK and PK cell interactions
- FK cell
    - Remove navigation link
    - Show a dropdown arrow on the right side, which opens the record selector
    - Remove the magnifying glass icon
    - Single click on active cell opens the record selector
    - Navigating to the linked record is performed via a context menu or a popover that displays on hover (like in Google Sheets)
- PK cell
    - Remove navigation link (place it in the row header instead)

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #1713
Fixes #1689

## Demo

https://user-images.githubusercontent.com/42411/192673946-ab3e3450-49b5-48b4-910c-5af33c08ea63.mp4

## Notes

- This PR introduces a minor regression for the Linked Record _Input_ (not Cell), where the magnifying glass icon to launch the record selector no longer appears. I plan to change it to use the dropdown arrow, but that work will be slightly easier after I've implemented the display of the record summary within the input. I've opened #1743 to track that work.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@kgodey @ghislaineguerin I invite you to look at the demo video in this PR and provide feedback on the design changes here, since these changes relate to a call we were all in. Keep in mind this is only for the PK and FK _cells_ -- it doesn't cover any of the behavior after the record selector is opened.

**Comment by ghislaineguerin** [comment]
- I like what you did with the ID field and I agree that the record page link should remain visible at all times.
- I'm not so sure about right-aligning the ID field. Have we considered a separate column for the record page link?
- The FK cell interactions make sense. I'm wondering if the down arrow could mislead the user into thinking a dropdown menu will show up. Maybe we could use a different icon like a link icon or a magnifying glass icon?

**Comment by seancolsen** [comment]
Thanks @ghislaineguerin.

- Nice idea with the separate column for the record page link instead of putting it in the PK cell. I'll work on that in this PR, and I'll put the PK value back to left-aligned.
- I'll try using the magnifying glass instead of the down arrow as well and see how that looks.

**Comment by seancolsen** [comment]
I added some more commits.

- Record page link in the row header

    > I agree that the record page link should be moved out of the ID column. During the meeting, I think we discussed moving it to the row header,

    Right. I meant to mention this in my demo video. I initially went this direction of putting the record page link in the row header, but I didn't like it for the following reasons:

    - The link felt like it was more associated with the row _index_ than it was with the PK value. Already, I think some users will be confused by the difference of the two numbers, especially since they appear directly adjacent, and will sometimes be identical. Putting the link in the row header felt to me like it would increase this confusion.

    - I also wanted to address the concern of click areas being too small in some cases. Being that we're also using the row header to select rows, it was tough fitting those two click interactions into the same small space.

- Record page link in a separate column

    Ok, so I started working on this today, but I have some more concerns that I'd like to discuss before proceeding.

    - For starters, it's not super straightforward to add a new column to the table. Possible of course, but it's not a quick thing I can easily try out. I got about half way there with a couple hours of work.

    - More importantly, I'm wondering how we might want to display record page links within the data explorer. I think it's worth giving this some thought from a design perspective. Not that we'd want to implement that functionality right away. But it might actually make sense to use the PK column for the record page link in the data explorer, in which case it would be nice to stick with the same design for the table page.

- I flipped the alignment of the PK cell content, and I think it looks a lot better.

    image


I'd like to get this PR merged without fiddling with the record page link anymore because I have lots of other things to work on, and my sense is that putting it in the PK cell is "good enough" for now. Is that okay with you, @ghislaineguerin and @kgodey?

**Comment by seancolsen** [comment]
Oh, and also, I'll keep the record selector trigger icon as a dowwards chevron for the time being since @kgodey prefers that.

**Comment by kgodey** [comment]
> putting it in the PK cell is "good enough" for now.

I agree, especially since we're also going to have the record page link in the table inspector, which will help with discoverability. I do think the alignment looks better.

>  might actually make sense to use the PK column for the record page link in the data explorer

I'm not sure this will make sense, because I don't expect most queries will use the PK column. I don't think we need to worry about this concern, though.

**Review by pavish — APPROVED** [review]
@seancolsen The code looks good. I haven't put thought into the usability but it seems everyone is in agreement and I see no major concerns.

**Pull request merged**
