### PR TITLE
Add authentication and login page

### PR DESCRIPTION
**Pull request by kgodey**
Related to #1673 

Once this PR is merged in, the app will use authentication. Locally, everyone will need to do the following:

```
docker exec -it mathesar_service bash
/manage.py createsuperuser --no-input --username admin --email admin@example.com
````

Alternately, destroy your local database and set it up following the README.

Then, go to `localhost:8000/auth/login/` and enter username `admin` and password `password`. You should then be able to use the app like usual.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
> Locally, everyone will need to do the following:

Would it make sense to add that info to `README.md`?

**Comment by kgodey** [comment]
> Would it make sense to add that info to `README.md`?

Yes, we should. I'll do it if I have time today, otherwise I'll leave it to @mathemancer.

**Comment by kgodey** [comment]
Creating the admin user happens as part of our initial setup script now, so `README` updates should be unnecessary. Anyone with an existing local Mathesar development setup should perform the manual user creation, though (unless they want to wipe their DB for some reason).

**Comment by mathemancer** [comment]
I went ahead and added login instructions to the README. Reviewers should double-check that the instructions are easy to understand (and that they work).

**Review by pavish — APPROVED** [review]
@kgodey @mathemancer Looks good!

I noticed that even without authentication, the frontend loads and contains preloaded data and only shows an error when an API request is made. I added a small commit https://github.com/centerofci/mathesar/pull/1742/commits/c0a236dee8e3c4962c25848a77d5bd169b879e78 to redirect all unauthenticated requests to views to the login page. 

Please take a look before merging.

**Comment by kgodey** [comment]
@pavish Thanks, good catch. I made a small commit that set the login URL as a setting so we don't have to repeat it for every view.

**Review by dmos62 — APPROVED** [review]
Approving, but would like to see authentication mechanism documented (or a documentation linked to) for accessing the API via HTTP.

**Comment by kgodey** [comment]
@dmos62 There's no API for login right now, so I'm not sure what there is to document. Could you add more information for what you'd like to see?

**Comment by dmos62** [comment]
@kgodey I see details for how to authenticate via a web browser (`localhost:8000/auth/login/`), but how do you do it via `curl`, for example? E.g. first google result for "django curl login": https://stackoverflow.com/questions/21306515/how-to-curl-an-authenticated-django-app

**Comment by kgodey** [comment]
@dmos62 I don't think we need special documentation for that, it's the same as any other Django app.

**Pull request merged**
