### PR TITLE
Introduce some filter aliases for time types

### LINKED ISSUE #1092: Implement filter name aliases for specific parameters
## Problem

We have filters that are quite generic and operate on various types. E.g. the filter `greater` can compare points in time, but its name is `x is greater than y`, which is not particularly well suited to describe the comparison of points in time. We'd prefer to have this filter's human-friendly name be something like `x is after y`, but only when comparing point-in-time types.

## Proposed solution

Create a scheme for assigning alias names to filters with a description of when that alias should be prefered. E.g. an alias `is after` for the `greater` filter's name (which is normally `is greater than`) that is preferred when first parameter of the filter is a `date`, `time` or `datetime`.

## Additional context
See following comment: https://github.com/centerofci/mathesar/issues/427#issuecomment-1047853291

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #1092

Alters filters endpoint output so that some filters declare aliases that are to be used with specific parameter types. E.g.:

```
  {                                                                                                                                                            
    "id": "lesser_or_equal",                                                                                                                                   
    "name": "is lesser or equal to",                                                                                                                           
    "aliases": [                                                                                                                                               
      {                                                                                                                                                        
        "alias": "is before or same as",                                                                                                                       
        "when": [                                                                                                                                              
          "datetime"                                                                                                                                           
        ]                                                                                                                                                      
      }                                                                                                                                                        
    ],                                                                                                                                                         
    "parameters": [                                                                                                                                            
      {                                                                                                                                                        
        "ui_types": [                                                                                                                                          
          "datetime",                                                                                                                                          
          "duration",                                                                                                                                          
          "money",                                                                                                                                             
          "number"                                                                                                                                             
        ]                                                                                                                                                      
      },                                                                                                                                                       
      {                                                                                                                                                        
        "ui_types": [                                                                                                                                          
          "datetime",                                                                                                                                          
          "duration",                                                                                                                                          
          "money",                                                                                                                                             
          "number"                                                                                                                                             
        ]                                                                                                                                                      
      }                                                                                                                                                        
    ]                                                                                                                                                          
  }, 
```

Note the `aliases` attribute. It says that when the first parameter is a `datetime`, use the alias `is before or same as` instead of the default name `is lesser or equal to`.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dmos62** [comment]
@pavish could you take a look and see if this makes sense to you?

**Comment by kgodey** [comment]
I think it would make sense to rename the `when` key to `ui_types` to make what is it a bit clearer. We've generally also been sticking to nouns for our API keys.

Also, why just `datetime`, why not `date` and `time` as well?

**Comment by pavish** [comment]
@dmos62 The structure looks good to me.

**Comment by dmos62** [comment]
@kgodey should be ready for merge.

> I think it would make sense to rename the when key to ui_types to make what is it a bit clearer. 

Renamed `when` to `ui_types` in JSON. 

> Also, why just `datetime`, why not `date` and `time` as well?

The [PR](https://github.com/centerofci/mathesar/pull/1093) that splits `datetime` into three types is based on this one.

**Review by kgodey — APPROVED** [review]

**Pull request merged**
