### PR TITLE
Allow the entire table card on the schema page to be clickable.

### PR DESCRIPTION
**Pull request by LFLATH**
I made a few changes in the HTML and CSS to allow the entire table card to be clickable.

Related to #1978 

These changes make the entire table card act as a link to the table.

Please let me know if anything I have done here it incorrect! I am still learning how this whole process works.

**Technical details**

I added a link tag around the header of the table card. This link goes to the same place as the Go to Table button. I then added some styles on hover. I also made a few changes to how the card is styled. I don't think these styles are correct. I added them more as a temporary fix to make this work.

**Screenshots**

image

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@LFLATH I've assigned this to you and updated to the status to indicate (as per your [comment](https://github.com/centerofci/mathesar/issues/1978#issuecomment-1332784947)) that you intend to make more changes to this PR before it's ready for review. When you're ready for me to review it, let me know by commenting here.

**Comment by LFLATH** [comment]
@seancolsen  Hello!, I thought I would give an update on my progress working on this issue. I haven't gotten very far but thought it wouldn't be right to stay silent. I am not very good at HTML and CSS but am enjoying learning. I have been struggling to join the visual behavior we are looking for with the actual programmatic behavior.  I can get to a solution similar to the one I put in my original PR, but this isn't correct. Sorry for the slow movement, it's finals season, so I will have more time to work in a little bit. I will upload my new code to the PR, and I would deeply appreciate any advice. Sorry for the delay!

**Comment by seancolsen** [comment]
@LFLATH somehow you've ended up with a bunch of other changes in this PR. Can you fix this? I see you've opened this PR from your own `master` branch. It would be a good idea to create a custom branch in your fork. Give your branch a name like `1978_table_card_hyperlink`. Then put your changes in that branch. You might want to start over with a new branch based on the most current `master` and then use `git cherry-pick` to put your changes into that branch. I'll continue my review once the commits are cleaned up.

**Comment by LFLATH** [comment]
@seancolsen I have redone the committing process and ran the necessary formatting checks. Sorry about the errors on the first one! This current code is definitely not ready yet, but I would love any critique/guidance. Thanks for the help!!!

**Comment by seancolsen** [comment]
@LFLATH unfortunately I don't have the available time to guide you towards the proper changes beyond the time it would take me to make those changes myself. Given the [guidance I already offered within the ticket](https://github.com/centerofci/mathesar/issues/1978#issuecomment-1332718513), it'll be up to you from here to make those changes yourself if you want. You may choose a different ticket to work on if you like, but note that we don't have many tickets right now that are super easy.

Given the behavior I'm seeing in the app with the changes in this PR...

image

...I can tell this PR is still not ready for review. Ping me here if you're able to add more changes that successfully address the problem.

**Comment by LFLATH** [comment]
@seancolsen Hello. I am sorry about the earlier code, it definitely wasn't adequate work. I have made some more changes that should be close to satisfactory. I think everything follows your specifications and the behavior is as desired. The one thing that still is a little off is the Go to Table text. This text has to be positioned above the link for its styling to work correctly, however, I couldn't get it to actually work as a link while positioned above the link. So instead, I positioned it above the link and then called a function that set the window link to the correct link. Thanks and sorry about the last commit.

**Comment by seancolsen** [comment]
Thanks for the additional changes, @LFLATH. We are pushing hard on some deadlines right now so I probably won't have time to review this for a couple weeks.

**Comment by LFLATH** [comment]
@seancolsen Perfect! Enjoy the holidays!!

**Pull request closed without merging**
