### PR TITLE
 issue 2736

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
[

Fixes #[issue number]

**Technical details**

**Screenshots**

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

https://user-images.githubusercontent.com/122200551/231168390-dc419832-a49e-49b7-85d2-39e2c472c328.mp4

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Sulochan-khadka** [comment]
one improvement is possible . once the table is deleted, the names of the table arranges itself. Is it a good thought? kindly let me know.

**Comment by rajatvijay** [comment]
Hi @Sulochan-khadka. The PR description is not properly formatted: 

1. Does not mention that issue is fixing
2. The video is not located in the proper place. 
3. The checklist is incomplete. 
4. The title of the PR is not descriptive enough. 

Please fix these problems before we can start reviewing this.

**Comment by rajatvijay** [comment]
@Sulochan-khadka really appreciate your efforts but there is already a PR pending for this issue #2736. I agree that this issue was not assigned to anyone until now but that was because we were maintaining a pool for the GSoC applicants. But now since the GSoC deadline has passed, I have assigned the issue to the contributor who already has a PR for this. Hence I will have to close this PR. 

I encourage you to look for other issues.

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka really appreciate your efforts but there is already a PR pending for this issue #2736. I agree that this issue was not assigned to anyone until now but that was because we were maintaining a pool for the GSoC applicants. But now since the GSoC deadline has passed, I have assigned the issue to the contributor who already has a PR for this. Hence I will have to close this PR.
> 
> I encourage you to look for other issues.

sir actually I had been given a time to create a pr and solve an issue so that my mentor confirms that i am well aware of the codebase of Mathesar. Therefore I had chosen this issue since it was unassigned.

**Comment by dmos62** [comment]
@Sulochan-khadka this PR does make you eligible for your proposal being evaluated. Thanks!

**Pull request closed without merging**
