### PR TITLE
fix(ui): fixes the DateTimeInput

### LINKED ISSUE #1769: Date input should close date picker when losing focus via Tab or Shift+Tab
## Steps to reproduce

1. Navigate to the Record Page for one Checkouts record.
1. Click on the "Checkout Time" input field to focus it.
1. Observe the date picker to appear (good).
1. Press Tab to focus on the Due Date input.
1. Expect the Checkout Time date picker to close.
1. Instead, observe the Checkout Time date picker remains open, even when the Due Date date picker has also opened.

https://github.com/centerofci/mathesar/assets/42411/e4d4f9d9-875c-4b0b-9c6c-d627653dcd78

https://github.com/centerofci/mathesar/assets/42411/e1c054a3-dec1-49d9-9362-2dc687949e74

CC @pavish

### PR DESCRIPTION
**Pull request by varun7singh**
fixes #1769

### CODE REVIEW

**Comment by varun7singh** [comment]
@rajatvijay  sorry for the earlier pr made the necessary changes

**Comment by varun7singh** [comment]
should i merge the latest changes from master into this branch?

**Comment by kgodey** [comment]
sure, you can always do that @varun7singh.

**Comment by rajatvijay** [comment]
@varun7singh can you please fix the failing checks before I can review the PR.

**Comment by varun7singh** [comment]
@rajatvijay  can you please review this

**Comment by rajatvijay** [comment]
@varun7singh the `typecheck` check is still failing. 

You can always run this check on your local before pushing the final code using: `npm run typecheck`. If the command does not run properly please make sure your development env is set up properly as the per guide [here](https://github.com/centerofci/mathesar/tree/develop/mathesar_ui#development-setup). 

I am also attaching a screenshot of the exact error from the `typecheck` check: 
Screenshot 2023-03-07 at 9 11 35 AM

**Comment by varun7singh** [comment]
@rajatvijay i fixed the error but i'm not too sure about my approach here can you please check it

**Review by rajatvijay — CHANGES_REQUESTED** [review]
@varun7singh sorry for the delay suggested a minor change.

**Comment by pavish** [comment]
@varun7singh I'm going to close this PR since this has been open for a long time without progress. Please feel free to open another PR if you're still working on this.

**Pull request closed without merging**
