### PR TITLE
Reflect db objects before rendering page

### LINKED ISSUE #365: DB syncing is not triggered when objects are fetched without involving the API
## Description

DB syncing currently is triggered by accessing the `SchemaViewSet`. However, schemas can be fetched without the API being involved. Our initial load of the frontend uses Django templates (and querysets) to fetch schemas and pre-render them without needing a network call. This should trigger DB syncing.

## Expected behavior

The DB should be synced when the Schema queryset is fetched, not when the API is called. This also applies to tables and databases.

## To Reproduce

Wipe your database and load the Mathesar UI. It won't load any schemas.

### PR DESCRIPTION
**Pull request by eito-fis**
Fixes #365

Reflects all db objects before rendering the requested page.

**Technical details**
Adds a call to `reflect_db_objects` in `mathesar/views/frontend.py` before schemas are retrieved, ensuring that the initial data will be up to date. I've confirmed locally that this resolves the issue detailed in #365.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by eito-fis** [comment]
Some questions:
* Do we need to worry about tests for this? Given the small scope I'm assuming its fine, but figured I should ask.
* How strict do we want to be about ensuring that db objects are reflected? A more principled approach might be to force the reflection anytime a queryset is generated using a custom [Django Manager](https://docs.djangoproject.com/en/3.2/topics/db/managers/#django.db.models.Manager) for our models. This would guarantee that our Django models are always up to date, but I imagine would also be much less efficient.

**Review by kgodey — CHANGES_REQUESTED** [review]
@eito-fis I think it would make the most sense to override the default queryset used while fetching schemas and tables so that we reflect DB objects whenever we look at schemas or tables. This would allow us to remove the API-specific code and it also means we don't have to keep adding the `reflect_db_objects` method to new views.

A quick Google led to https://stackoverflow.com/questions/19813375/override-what-objects-all-returns-when-using-passthroughmanager-in-django-mode, I'm not sure if that's the best question/answer for this problem, but it should at least lead you in the right direction.

**Comment by kgodey** [comment]
@eito-fis sorry, I missed your questions. I think a custom Django manager would work fine, I believe that the reflection method has a 5-min cache built in, which would help with efficiency.

I think it would be helpful to have tests for the queryset modification since it will be pretty fundamental to how we access objects.

**Comment by eito-fis** [comment]
Made changes:
* Moved all reflection functions into `mathesar/reflection.py` and updated references accordingly.
* Updated to use a custom manager for reflection. Now, db objects are reflected whenever the `.objects` attribute of the `Database`, `Table` or `Schema` model is used. 
* Also maintains a default manager that doesn't reflect db objects with the `.current_objects` attribute. Used for default Django operations and reflection operations.
* Added simple tests to verify that db objects are being reflected when the queryset is referenced.

**Review by mathemancer — COMMENTED** [review]
I think this looks good; let's wait for @kgodey to verify.

**Review by kgodey — APPROVED** [review]
Looks good. I wiped my DB locally and verified that this fixes the issue.

**Pull request merged**
