### PR TITLE
Backend crash prevention when ordering by a non orderable.

### LINKED ISSUE #2305: Ordering by a non-orderable column (implicitly or explicitly) causes a backend crash
## Bug

Brent [writes](https://github.com/centerofci/mathesar/pull/2253#pullrequestreview-1251718380):

> At one point, you note in a comment that there's a bug whenever we have internal columns of JSON type, and no primary key in a table. This bug is still present for _any_ non-orderable column type if there is no primary key in the table (e.g., if the user attaches to a preexisting DB). It's easy to figure out whether or not a type is orderable in PostgreSQL. See the [docs page for ORDER BY](https://www.postgresql.org/docs/current/queries-order.html#id-1.5.6.9.5.10) and the [docs page for Operator Classes](https://www.postgresql.org/docs/9.5/indexes-opclass.html).

Brent is referring to [this comment](https://github.com/centerofci/mathesar/blob/8c215b2efdd740da0d530b624763cf260e12ca90/db/records/operations/sort.py#L47).

The error message received upon such a crash is: `could not identify an ordering operator for type json` (`json` is the type of the unorderable column in this case.

## Solution

The solution is, as explained by Brent, to make sure that every column we order by (implicitly or explicitly) is orderable.

## Severity

Because of this, a JSON column (it's non-orderable), can make a query/table view unrenderable, but only when the table/query does not have a primary key, which cannot happen in a Mathesar-created table. It can only happen when Mathesar is used to access a pre-existing database.

### PR DESCRIPTION
**Pull request by Hatilar420**
Fixes #2305 

# Overview

- Makes sure every column we order by is orderable.
- Prevents backend crash when an unorderable type is requested.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dmos62 — CHANGES_REQUESTED** [review]
@Hatilar420 looks pretty good!

I'd like to see `_is_internal_column` preserved: even though it seems redundant since `__mathesar_group_metadata` is a JSON column and thus should be filtered out by `_is_col_orderable`, we would want to filter it out even if it was an orderable type (since it's a "hidden" column), and we might want to filter out additional internal columns in the future.

Please fix the tests too.

**Comment by Hatilar420** [comment]
Hey @dmos62 , i've corrected the code and the tests are running fine now. 
Should i remove the docstring comment entirely or change it ?

**Comment by dmos62** [comment]
@Hatilar420 hey, I was away for a few days. Sorry to notice this late in the review process, but a test needs to be added to make sure that this prevents backend crashes.

**Comment by Hatilar420** [comment]
sure, will add a few tests for this.

**Comment by Hatilar420** [comment]
Hi @dmos62, Just wanted to ask if there are any methods or classes in the codebase that can help me mock a Database without a primary key to test this ?

**Comment by dmos62** [comment]
@Hatilar420 I'm not aware of any. You might want to create a table directly via sqlalchemy or plain SQL.

**Comment by Hatilar420** [comment]
Hi @dmos62, Is any documentation available to help me write unit tests in Mathesar? I am unable to find methods that create a new DB via factory methods available in Mathesar

**Comment by Hatilar420** [comment]
Hi @dmos62, I have added a test. Please take a look and let me know if this test is appropriate(As we only have to test that the backend isn't crashing by ordering a non-orderable). If not, can you suggest some more tests that we can implement?

**Comment by dmos62** [comment]
@Hatilar420 There was a problem with the test: `get_records` had `fallback_to_default_ordering` set to `false` by default. I also simplified some things and updated docstrings. Here's the patch. You can apply it with `git apply`. Please do that and I'll merge this. Thanks for the contribution!

```diff
diff --git a/db/records/operations/sort.py b/db/records/operations/sort.py
index 2bcf2834b..9e51eaa61 100644
--- a/db/records/operations/sort.py
+++ b/db/records/operations/sort.py
@@ -44,11 +44,8 @@ def _build_order_by_all_columns_clause(relation):
     To be used when we have failed to find any other ordering criteria,
     since ordering by all columns is inherently inefficient.
 
-    Note the filtering out of internal columns. Before applying this fix, psycopg was throwing an error
-    like "could not identify an ordering operator for type json", because we were trying to
-    sort by an internal column like `__mathesar_group_metadata`, which has type `json`, which
-    requires special handling to be sorted. The problem is bypassed by not attempting to sort on
-    internal columns.
+    Note the filtering out some columns, namely internal columns and non-orderable columns. See
+    their docstrings for details.
     """
     return [
         {'field': col, 'direction': 'asc'}
@@ -60,12 +57,19 @@ def _build_order_by_all_columns_clause(relation):
 
 def _is_internal_column(col):
     """
+    Columns that Mathesar adds for its own devices and does not expose to the user. We don't want
+    to sort by these.
+
     Might not be exhaustive, take care.
     """
     return col.name == '__mathesar_group_metadata'
 
 
 def _is_col_orderable(col):
+    """
+    Some columns are not orderable (or at least don't have a non-ambiguous way to define order
+    without additional logic). We only want to order by orderably columns.
+    """
     data_type = col.type
     non_orderable_type = ['Binary', 'LargeBinary', 'PickleType', 'ARRAY', 'JSON', 'JSONB']
     return str(data_type) not in non_orderable_type
diff --git a/db/tests/resources/json_without_pkey.sql b/db/tests/resources/json_without_pkey.sql
index 3f7e813ef..6ed549ba9 100644
--- a/db/tests/resources/json_without_pkey.sql
+++ b/db/tests/resources/json_without_pkey.sql
@@ -1,7 +1,7 @@
 CREATE TABLE "json_without_pkey" (
-    "json_object" mathesar_types.mathesar_json_object
+    "json_object" json
 );
 
 INSERT INTO "json_without_pkey" VALUES
-('{"name": "John", "age": 30}'::mathesar_types.mathesar_json_object),
-('{"name": "Earl James", "age": 30}'::mathesar_types.mathesar_json_object);
\ No newline at end of file
+('{"name": "John", "age": 30}'::json),
+('{"name": "Earl James", "age": 30}'::json);
diff --git a/db/tests/transforms/test_json_without_pkey.py b/db/tests/transforms/test_json_without_pkey.py
index 0a113da51..2ce417e8e 100644
--- a/db/tests/transforms/test_json_without_pkey.py
+++ b/db/tests/transforms/test_json_without_pkey.py
@@ -1,24 +1,7 @@
-import pytest
-from db.transforms.operations.apply import apply_transformations
-from db.transforms import base as transforms_base
 from db.records.operations.select import get_records
 
 
-@pytest.mark.parametrize(
-    "transformations, expected_record_length",
-    [
-        [
-            [
-                transforms_base.Order(
-                    spec=[],
-                )
-            ],
-            2
-        ]
-    ]
-)
-def test_transformations(json_without_pkey_table_obj, transformations, expected_record_length):
+def test_default_ordering(json_without_pkey_table_obj):
     table, engine = json_without_pkey_table_obj
-    relation = apply_transformations(table, transformations)
-    records = get_records(relation, engine)
-    assert len(records) == expected_record_length
+    records = get_records(table, engine, fallback_to_default_ordering=True)
+    assert len(records) == 2
```

**Comment by Hatilar420** [comment]
Hi @dmos62, Thanks for the suggested patch. Applied it

**Review by dmos62 — APPROVED** [review]

**Pull request merged**
