### PR TITLE
Fix toast message when deleting rows

### LINKED ISSUE #2233: Don't show success toast message when failing to delete records
## Steps to reproduce

1. Go to the Table Page for a table that another table references. (E.g. "Publications" is referenced by "Items").

1. Use the row header context menu to delete a record that another record references. The server will respond with an error when making the delete request.

1. Expect no toast message.

1. Observe a success toast message.

image

## Implementation notes

- This will require some refactoring within `RecordsData.deleteSelected` to make callers of that function aware of the failure scenario. Note that the function is designed to delete multiple rows with separate requests, so it's possible that some will fail and some will succeed.

### PR DESCRIPTION
**Pull request by DanyaalMahmood**
Fixes #2233 

This PR fixes the toast message showing success when rows are not deleted successfully. Now the toast message correctly indicates if a row was not deleted successfully or if some of the selected rows were not deleted successfully.

Before:
211829542-d981ea61-166e-4ef6-8452-8f1dc1369f4e

After:

https://user-images.githubusercontent.com/110989303/222566150-619c9caf-a83e-4ce8-90ba-84aeffe4830e.mp4

https://user-images.githubusercontent.com/110989303/222564863-26c0e914-e5fc-4abd-b707-9b6265f6724d.mp4

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by DanyaalMahmood** [comment]
Hey @rajatvijay I fixed the linting issues, could you please approve the workflows.

**Comment by DanyaalMahmood** [comment]
@rajatvijay I think the issue is fixed, can you review the PR.

**Comment by kgodey** [comment]
@DanyaalMahmood It's on our queue, please be patient!

**Review by rajatvijay — APPROVED** [review]
LGTM 🚀

**Pull request merged**
