### PR TITLE
Cell-level errors

### LINKED ISSUE #1045: Gracefully handle new API error structure in toast messages
## Reproduce

1. Use the front end
1. Attempt to disallow duplicates for a column that contains duplicate values.
1. Observe a toast message:

    > Unable to update "Allow Duplicates" of column "Flighted". {"code":4208,"message":"This column has non-unique values so a unique constraint cannot be set","field":null,"detail":null}.

1. Using dev tools, observe that the server is responding with the following JSON which is why we see "[object Object]" in the toast message.

    ```json
    [
      {
        "code": 4208,
        "message": "This column has non-unique values so a unique constraint cannot be set",
        "field": null,
        "detail": null
      }
    ]
    ```

1. Expect a toast message:

    > Unable to update "Allow Duplicates" of column "Flighted". This column has non-unique values so a unique constraint cannot be set. [4208]

## Solution

We should handle this at a low level automatically so that Svelte components don't need to care about how the API error is received. The implementer should explore various approaches and improvise one or comment here with a proposal.

## Additional context

- [API Error Standards](https://wiki.mathesar.org/en/engineering/architecture/api-standards)

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #1045

Works towards #775

## Demos

- [Demo 1 -- Updating cells](https://www.loom.com/share/b4b634f0e38b455bb1108d486afeb510)
- [Demo 2 -- Adding/Deleting rows](https://www.loom.com/share/fa0cbf793d344e308163934802a121a0)
- [Demo 3 -- Failure to update a cell within a successfully added row](https://www.loom.com/share/ee08f6ae12f9491f9221d11e8afde974)

## Issues

- Cell background when row is hovered or selected or newly-added takes precedence over cell background as determined from edits. Before making further adjustments to this behavior, I'd ideally like to get some input from @ghislaineguerin on how cell background should work. We're using background color to communicate a lot of things at once. I've started #1282 for further discussion.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
I don't understand why this E2E test is failing. It seems to be timing out. 

> locator_assertions.to_be_visible with timeout 5000ms

The listed timeout is not what I'd expect. It should be 30000ms because we have [overridden](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#override-a-fixture-on-a-test-module-level) the `page` fixture.

@silentninja any ideas here?

**Comment by seancolsen** [comment]
Note: I merged changes from #1286 (which is set for auto-merge into master) into this PR in an attempt to get the CI to pass.

**Comment by pavish** [comment]
@seancolsen The PR looks good. I noticed a couple regressions we need to fix before merging this in:
* Skeleton does not show when there is a sheet level loading action - initial load, refresh, pagination, applying sorting etc., It should be visible in these scenarios.
* Skeleton shows during a cell update. It should not be visible during this scenario.

We can figure out cell background behavior later.

**Review by pavish — CHANGES_REQUESTED** [review]
@seancolsen The PR looks good. I noticed a couple regressions we need to fix before merging this in:
* Skeleton does not show when there is a sheet level loading action - initial load, refresh, pagination, applying sorting etc., It should be visible in these scenarios.
* Skeleton shows during a cell update. It should not be visible during this scenario.

We can figure out cell background behavior later.

**Comment by seancolsen** [comment]
@pavish I've added 5a13e3f3b10c8913c7104aff18fdf323531954fc which should address your feedback. Ready for re-review now.

**Review by pavish — APPROVED** [review]
@seancolsen Nice work on this!

I do see another regression:
* When rows are deleted, we re-fetch data for the entire page.
* The skeleton indication is now shown for the entire sheet for this. It should not be shown.

I'm going to merge this in. I'll add a separate issue for this.

**Comment by pavish** [comment]
Created https://github.com/centerofci/mathesar/issues/1289

**Pull request merged**
