### PR TITLE
Documentation for installing Mathesar on Debian and Ubuntu

### LINKED ISSUE #2427: Allow users to install Mathesar without Docker (on Debian)
## Deployment Type 3
This is a 'bare-metal' (more likely, VPS) installation. They'll end up with Mathesar running directly on their machine. There'd be either a PostgreSQL db running on the same machine, or a different one.

This installation user flow is much more documentation-oriented in order to allow for the needed flexibility to deal with a number of different systems. 

#### Preliminaries
- We'll only document installing on Debian 11 for now.
  - If we have time, we can add documentation for installing on other systems (e.g. Ubuntu 22.04, Fedora, CentOS, etc.)
- We'll use the steps in our existing Ansible playbook https://github.com/centerofci/mathesar-ansible to create the documentation.

### Installation User Flow
On `docs.mathesar.org`, there will be an "Installation > Install on Debian" page that contains a guide like this: https://www.natrius.eu/dokuwiki/doku.php?id=digital:server:matrixsynapse. This will walk the user through setting up Mathesar on a VPS server with Debian 11 already installed.

### Installation Flow Tasks
- [ ] Create documentation for installing Mathesar on Debian 11 on `docs.mathesar.org`

## Notes
- This was moved from https://github.com/centerofci/mathesar/issues/2034.

### PR DESCRIPTION
**Pull request by mariusdebeer**
Fixes #2427 

This is the documentation for installing Mathesar on various versions of Linux.

The stack used is the same as our Docker Compose file.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Thanks for working on this @mariusdebeer!

I see there's no issue linked – the issue for this is #2427. Please also double check the formatting of the checklist in the PR.

**Comment by rajatvijay** [comment]
@mariusdebeer Can you please do the following: 

1. Fix the formatting of the checklist in the PR's description. 
2. Fix the conflict.

**Comment by pavish** [comment]
@silentninja Could you please co-ordinate with @mariusdebeer to speed the process of getting this PR ready?

**Comment by seancolsen** [comment]
Hey I just want to chime here and mention that @mariusdebeer reached out to me last week with some questions about docs editing and PR workflow. I explained a bit about how things work, aiming to get Marius up to speed with _local_ docs editing (instead of editing via the GitHub web interface). We were very close to getting a new PR opened from a feature branch (instead of `master`) so that Marius can continue other work and more easily resolve conflicts -- but our time got cut short. I'm happy to help more on this however I can.

**Comment by pavish** [comment]
@silentninja @mariusdebeer What is the current status of this PR?

**Comment by mariusdebeer** [comment]
Good day

This is still in progress

**Comment by silentninja** [comment]
I replaced the `Nginx + certbot` reverse proxy setup(originally used by @mariusdebeer) with `Caddy` as it was easier to configure.

**Review by seancolsen — APPROVED** [review]
@silentninja I didn't have quite as much time as I'd like to review this today, but I wanted to submit an approval since I know you need this ASAP. I might take another look at it post-merge. I mostly reviewed for language and formatting, without looking too closely at the content.

- We need to resolve the conflicts.

- I find `<working-directory>` and `<virtual-env-directory>` to be confusing. Should these be the _same_ directory? Would they both typically be `/etc/mathesar`? I think we should change all the commands to use `/etc/mathesar` and mention up front that the reader can choose a different directory if they like. The angle brackets mess up copy-paste, and I think most readers would want to follow our recommended directory anyway. We can resolve this in a follow-up PR if needed.

- We should add an "Uninstall" section to the page.

**Comment by silentninja** [comment]
Thanks for the review @seancolsen 

> I find <working-directory> and <virtual-env-directory> to be confusing. 

Unlike `node_modules`, python modules are installed in a separate directory as a convention(usually `/opt/virtualenvs/`), should we explain these directories?

> I think we should change all the commands to use /etc/mathesar and mention up front that the reader can choose a different directory if they like
 I didn't want to specify a directory due to the issues mentioned in #2865. Do you think we should specify a opinionated directory?
 
> The angle brackets mess up copy-paste, and I think most readers would want to follow our recommended directory anyway.

I had a look at [Mkdocs placeholder plugin](https://mkdocs-placeholder-plugin.six-two.dev/usage/) to make it easy to copy and paste the code. I will create an issue to address it later and just use a default directory

**Comment by silentninja** [comment]
I addressed your concerns in subsequent commits

> I find <working-directory> and <virtual-env-directory> to be confusing

I replaced the `<virtual-env-directory>` to be the same as the `<working-directory>`.

> The angle brackets mess up copy-paste

 I removed place holder and replaced it with the home directory path.


> We should add an "Uninstall" section to the page.

Added an uninstall section

**Pull request merged**
