### PR TITLE
Alter library dataset to use DROP ... CASCADE

### LINKED ISSUE #2316: InternalError while running the install script for demo mode
## Description

While executing the `load_datasets(engine)` module of the install.py script of the demo app, the following error occurs: 
```
InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop schema Library Management because other objects depend on it
DETAIL:  table "Library Management"."Authors" depends on schema Library Management
table "Library Management"."Books" depends on schema Library Management
table "Library Management"."Checkouts" depends on schema Library Management
table "Library Management"."Items" depends on schema Library Management
table "Library Management"."Media" depends on schema Library Management
table "Library Management"."Patrons" depends on schema Library Management
table "Library Management"."Publishers" depends on schema Library Management

```
## Expected behavior

We should be able to execute `load_datasets(engine)` without any errors.

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #2316 

The `_load_library_dataset` method was lacking `CASCADE` in the SQL statement which was causing an InternalError while dropping the existing Library Management schema this PR fixes that. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@Anish9901 please set assignee and review label when an issue is ready for review. I did it for this one.

**Comment by Anish9901** [comment]
@kgodey can you review and merge this?

**Comment by kgodey** [comment]
@Anish9901 is it blocking something? If not, I have a bunch of other priorities at the moment.

**Comment by Anish9901** [comment]
> @Anish9901 is it blocking something? If not, I have a bunch of other priorities at the moment.

Not really, but the change is small enough that it doesn't really require a review.

**Review by mathemancer — COMMENTED** [review]
Looks good, thanks.

**Pull request merged**
