### PR TITLE
Fixes #1197 - raised the playwright page default from 5sec to 10 sec

### LINKED ISSUE #1197: Raise the default Playwright page timeout value
## Problem

- Some E2E tests are failing intermittently. For example, [here](https://github.com/centerofci/mathesar/runs/5605572101?check_suite_focus=true) is a CI job that failed but passed when re-ran.
- I'm theorizing that we're hitting Playwright's default 5-second timeout on some operations that take longer.

## Solution

- I think we should raise the timeout value globally.
- Playwright has a [set_default_timeout](https://playwright.dev/python/docs/api/class-page#page-set-default-timeout) method that we can run on the `page` object.
- We need to figure out where in our E2E testing stack is appropriate to call this function so that it applies everywhere.
- I think we should set it to 10 seconds.

## Tips

- If you're working on this, I'd suggest the following. In order to test that your fix works, first set the timeout to something very small, like 50ms, and verify that you see some tests which fail (giving you an indication that your setting has been correctly applied). Then tweak the setting to 10 seconds.

## Additional context

- [Discussion on Matrix](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$xZcuhHRDrvqO7cBYXODdqs1tmRxuWcPlHmxobSR_beo?via=matrix.mathesar.org&via=matrix.org)

### PR DESCRIPTION
**Pull request by Cronus1007**
Fixes #1197 

**Technical details**
raised the playwright page default from 5sec to 10 sec
**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by aviwad** [comment]
why did you increase timeout in test_import_from_clipboard? because aside from that our PR is identical haha

**Review by seancolsen — CHANGES_REQUESTED** [review]
@Cronus1007 Thanks for this PR. It's not quite what I had in-mind though when I wrote #1197. From the ticket:

> we should raise the timeout value **globally**

and 

> figure out where in our E2E testing stack is appropriate to call this function so that it applies **everywhere**

(emphasis added)

As I said in the ticket, I don't know how to raise the timeout value globally, because I'm new to Playwright (as is everyone else on our team). But I'm confident there is a way. The PR should specify the 10 second value in only _one place_, and that value should apply to _all_ E2E tests.

Because the steps to resolve this issue are somewhat unknown (at least to me), I was initially hesitant to apply the "Good first issue" label, but someone else on the team suggested it. If you want to move on to another ticket that's fine. (Just let us know so that we can un-assign you). Or if you want to keep working on this one you'll probably need to do a little research into configuring Playwright.

**Comment by Cronus1007** [comment]
@seancolsen Sure this is just an initial stage where I wanted to reflect those tests which would need a timeout.
Plus I would like to make an addition to the problem statement that this where [this workflow](https://github.com/centerofci/mathesar/runs/5605572101?check_suite_focus=true) failed at the expect statement which has a default timeout of 5s so we need to set the default timeout in  config in this manner 
`config = { expect: { timeout: 10000 } }`

This is my solution for this problem. Shall I proceed it in this manner.

**Comment by seancolsen** [comment]
@Cronus1007 I don't understand what you're proposing in your last message. Sorry.

> Can you please tell me where the config file has been placed in the codebase?

No, because I don't know. Figuring it out is part of what's required to close this issue. If you want to move to another issue that's fine. Just let us know.

**Comment by Cronus1007** [comment]
@seancolsen 

> @Cronus1007 I don't understand what you're proposing in your last message. Sorry.
> 
> > Can you please tell me where the config file has been placed in the codebase?
> 
> No, because I don't know. Figuring it out is part of what's required to close this issue. If you want to move to another issue that's fine. Just let us know.

No I would work upon this issue. Since I am little bit familiar with playwright with javascript I guess I would figure it out. What's your opinion about the 

> Plus I would like to make an addition to the problem statement that [this workflow]
> (https://github.com/centerofci/mathesar/runs/5605572101?check_suite_focus=true) failed at the expect statement which has > a default timeout of 5s

**Comment by Cronus1007** [comment]
@seancolsen Have a look at this [documentation](https://playwright.dev/docs/test-timeouts). This one is related to the playwright javascript since I am unable to find out the such sort of documentation for the playwright python. As per the documentation we need not to worry about the global timeout since it has no default timeout. For solving this issue we only need to increase the expect timeout from 5s to 10s. For a particular expect statement it can be done in this manner 
`
{expect(locator).toBeVisible({ timeout: 10000 })}
`
I am raising an issue at the microsoft/playwright-python since in the [documentation](https://playwright.dev/python/docs/intro) of playwright python they had no such guide which deals with the configuration and timeouts in playwright python.

**Comment by pavish** [comment]
@Cronus1007 @seancolsen 

I'd like to jump in to provide a suggestion here. The python configuration of playwright differs significantly from it's Node.js equivalent, as in there is no config file. We use the `pytest-playwright` plugin, which provides us with a `page` fixture.

This also gives us more freedom. Inorder to use global page configurations, all we have to do is create a new fixture, maybe `global_page` (I'm terrible at names) and use that fixture instead of `page` everywhere. This `global_page` fixture can return a page object with the timeout set to 30s.

**Comment by Cronus1007** [comment]
@pavish @seancolsen 
We can use it in this manner
def new_global_page_fixture(playwright):
    browser = playwright.chromium.launch(channel="chrome")
    context = browser.new_context()
    global_page = context.new_page()
    global_page.set_default_navigation_timeout(30000)
    browser.close()

with sync_playwright() as playwright:
    new_global_page_fixture(playwright)

**Comment by silentninja** [comment]
@Cronus1007 Take a look at this issue https://github.com/microsoft/playwright-pytest/issues/23 and see if it works

**Comment by Cronus1007** [comment]
@silentninja @seancolsen I am increasing the default timeout value to 20 sec. Since while setting up the context's default timeout at 10 sec few tests were failing so the most optimum timeout value to which I reached was 20sec.

@silentninja They have not implemented their fixtures feature until now.

**Comment by pavish** [comment]
@Cronus1007 @silentninja

This context timeout is not the timeout of locators but rather the timeout for launching the browser. This is different from the page locator timeout.

Please override the page fixture instead.

**Comment by Cronus1007** [comment]
@pavish @silentninja @seancolsen This approach of mine is working since here I have created a new instance of page object from Page class and that function gave an additional property regarding the page's default navigation timeout value to be 20 sec. 
When I reduced the timeout to 2sec the tests failed. Also if we wanted to override the new timeout settings to a test we need to pass the new_default_timeout function to the test.

**Comment by Cronus1007** [comment]
@pavish I guess this is what you intent to tell because locally by running the command 
`docker exec mathesar_service pytest --browser webkit  --no-cov mathesar/tests/integration`
I am able to reslve this issue. Can you please approve [this workflow](https://github.com/centerofci/mathesar/actions/runs/2036456199)  for a final check?

**Comment by Cronus1007** [comment]
> @Cronus1007 @seancolsen
> 
> I'd like to jump in to provide a suggestion here. The python configuration of playwright differs significantly from it's Node.js equivalent, as in there is no config file. We use the `pytest-playwright` plugin, which provides us with a `page` fixture.
> 
> This also gives us more freedom. Inorder to use global page configurations, all we have to do is create a new fixture, maybe `global_page` (I'm terrible at names) and use that fixture instead of `page` everywhere. This `global_page` fixture can return a page object with the timeout set to 30s.

Shall I increase it from 10s to 30s. Since locally I was able to complete the entire job in 10s.

**Comment by pavish** [comment]
@Cronus1007 We could actually only add this fixture:

```
@pytest.fixture
def page(page):
    page.set_default_navigation_timeout(30000)
    yeild page
```

This way we don't have to modify usages of the page fixture everywhere.

**Comment by Cronus1007** [comment]
@pavish I have done the required changes.

**Review by seancolsen — APPROVED** [review]
This looks good. 

@pavish thank you for suggesting a clean solution here that only requires minimal changes.

I tested this locally and reduced the timeout setting to 100ms to verify that it is indeed taking effect. The default of 30s seems fine. The large timeout does have a downside of slowing down the process of confirming that a test _fails_ during development, but I think that's okay.

I added a commit which fixed a misspelling of `yeild` to `yield`. This misspelling seems to have likely originated in the code that Pavish suggested. A misspelling like this seems perfectly reasonable in the context of a code suggestion comment. However @Cronus1007 the misspelling in your committed code does make me wonder if you tested the changes locally before committing and pushing them. I can't imagine you would have been able to run those changes locally with success. That's fine if the PR is still in draft state and not yet ready for re-review. But your latest comment communicated to me that you consider this code ready for re-review. For your future PRs, the review process would be easier for us if you could put in the effort ahead of time to make sure the code is working locally for you.

**Comment by Cronus1007** [comment]
> But your latest comment communicated to me that you consider this code ready for re-review. For your future PRs, the review process would be easier for us if you could put in the effort ahead of time to make sure the code is working locally for you.

@seancolsen Sure I would keep it in mind. Sorry for the inconvenince caused.

**Pull request merged**
