### PR TITLE
Updated schema page to show correct number of skeletons while loading

### LINKED ISSUE #2351: When loading the Schema Page, show the correct number of loading skeletons
## Current behavior

- On the Schema Page we show nine loading skeletons [relevant code](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/pages/schema/TableSkeleton.svelte#L4)

## Desired behavior

- The Schema Page loads a number of skeletons equal to the number of tables in the schema.

## Implementation notes

- We actually already have the number of tables in the schema in the [num_tables](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/AppTypes.ts#L18) property of `SchemaEntry`, so it should just be a matter of connecting some dots.
- When I played around with this briefly, I was able to get it working when loading the Database Page (i.e. http://localhost:8000/mathesar_tables/ ) then navigating to the Schema Page. But the skeleton count was incorrect when navigating from a Schema Page to a different Schema Page (via the ) switcher dropdown in the navigation header. Make sure to get that working too.

### PR DESCRIPTION
**Pull request by IamEzio**
Fixes #2351 

Passes the number of tables as a prop to `TableSkeleton` so that the Schema Page loads a number of skeletons equal to the number of tables in the schema.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by rajatvijay** [comment]
@IamEzio the lint GitHub check seems to be failing, can you fix that before the review starts

**Comment by IamEzio** [comment]
Done @rajatvijay. PTAL. Thanks!

**Comment by IamEzio** [comment]
Hi @rajatvijay! A friendly ping :)

**Comment by Anish9901** [comment]
Hi @IamEzio, everyone in the team is currently working to get the product ready for the launch which is in a couple of weeks. So, there will be some delays in the PR reviews. Hope you understand. Thanks.

**Comment by IamEzio** [comment]
> Hi @IamEzio, everyone in the team is currently working to get the product ready for the launch which is in a couple of weeks. So, there will be some delays in the PR reviews. Hope you understand. Thanks.

Ah ok. Thanks!

**Comment by IamEzio** [comment]
@rajatvijay done!

**Comment by rajatvijay** [comment]
@IamEzio the `format` check is still failing.

You can always run this check on your local before pushing the final code using: `npm run format`. If the command does not run properly please make sure your development env is set up properly as the per guide [here](https://github.com/centerofci/mathesar/tree/develop/mathesar_ui#development-setup).

I am also attaching a screenshot of the exact error from the `format` check:
Screenshot 2023-03-07 at 9 24 35 AM

**Comment by IamEzio** [comment]
Thanks for the help @rajatvijay. I have updated the PR now. PTAL

**Comment by kgodey** [comment]
@IamEzio Our Python tests are a little flaky right now, see #2596. I tried re-running, hopefully that fixes it.

**Comment by IamEzio** [comment]
Ah ok. Thanks!

**Review by rajatvijay — APPROVED** [review]
LGTM 🚀 

Added a minor commit c674e9d5d to fix the type.

**Pull request merged**
