### PR TITLE
Record summary UI

### LINKED ISSUE #1544: Record summary UI for foreign key columns
## Problem
Foreign key columns should show their summary instead of the foreign key value

## Proposed solution
Replace foreign key value with the summary data fetched from the API

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #1544

Shows the record summary of the referent table for a foreign key column UI. This PR also removes the parameter `fk_preview` from the record's API and `show_fk_preview` which got carried over from previous iterations and is not needed anymore according to the spec

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@silentninja I have a number of review comments, but before I get too far down the road, I'd like to test this with transitive summaries. Loading the "Checkouts" table should do just that, but I get the following error from the records API.

image

Would you expect this PR to work with transitive summaries? Are you able to reproduce the above error? Is it possible to fix within this PR so I can continue my review?

**Comment by seancolsen** [comment]
@silentninja the names you picked for types, variables, and properties were really hard to decipher. I pushed a commit which improves the names and adds code comments further explaining them.

| Old name               | New name                          |
| ---------------------- | --------------------------------- |
| SummaryResult          | RecordSummaryInputData            |
| FkSummary              | DataForRecordSummariesInFkColumn  |
| FkColumnSummary        | DataForRecordSummariesInFkColumns |
| fkColumnSummary        | dataForRecordSummariesInFkColumns |
| FkColumnsSummaryRecord | DataForRecordSummariesInRow       |
| fkColumnsSummaryRecord | dataForRecordSummariesInRow       |
| FkSummaryRecord        | DataForRecordSummaryInFkCell      |
| fkSummaryValue         | dataForRecordSummaryInFkCell      |

**Review by seancolsen — APPROVED** [review]
This works for me!

I realized the error I was getting was with the transformed schema. When I switched to using Brent's data set, I no longer got the error and was able to see that transitive summaries are working great! Exciting! I'll open a separate ticket for that error where hopefully we'll be able to reproduce it.

**Review by mathemancer — APPROVED** [review]
I think the back end changes look good. I didn't consider the front end changes.

**Pull request merged**
