### PR TITLE
Fix SQL Syntax error while summarizing `Money, URI, Email` column

### LINKED ISSUE #2908: `AbstractType: Money, URI, Email` columns throw error when summarization is applied
## Description
`Money` columns can not be aggregated based on some other grouping column. 
(There won't be any problem, if `Money` column is the grouping column)

## Expected behavior
Users should be able to aggregate `Money` column based on another grouping column. 

## To Reproduce
- Create a table, add two columns, one of them should be `Money` column.
- Go to **Data Explorer**, Select the other column first, then add `Money` column.
- Then go to `Transformation Step` and `Summarize`.

Not every table will produce this error. (refer to **Additional Context**)

Screencast:

https://github.com/centerofci/mathesar/assets/64671908/518006d9-2c5c-4a19-b935-54e0714c4ccf

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29
 
## Additional context
**The folowing table will not produce the error.**

image

**While this modification will produce the error**.

image

### PR DESCRIPTION
**Pull request by Aritra8438**
Fixes #2908 

While summarizing (specifically listing) `Money`, `URI` and `Email`, The UI throws a syntax error. This PR fixes the same.
More details can be found in [this](https://github.com/centerofci/mathesar/issues/2908#issuecomment-1574076938) comment thread. 

## Technical details

It seems like there is a better fix than what I did earlier. 

If we apply `_maybe_downcast` before `Distinct`, it will cast to `NUMERIC`, and then `Distinct` will be called. That prevents `ArrayAgg` class from calling `downcast_to_underlying_type` again.
 
**The resulting SQL query becomes:**
```sql
array_agg(DISTINCT CAST(anon_1."Test Sum Function_Money" AS NUMERIC))
```

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Aritra8438** [comment]
This PR might fix the issue but 
`DistinctArrayAgg` does not comply with the return type of `DBFunctionPacked` **(which should return a** `DBFunction`)

**The main problem is to squeeze** `DISTINCT` **in between the** `ARRAY_AGG` **and** `CAST` **, which I did by overriding the** `to_sa_expression` **method and returning an sa expression.** 

When some `column_expr(s)` (Money) have `underlyingType` (Numeric), the ArrayAgg joins `ARRAY_AGG` and `CAST` sequentially (so, they can't be separated?)

**Review by mathemancer — CHANGES_REQUESTED** [review]
Great work on this. Please add a minimal API test for the fix, and let's get this merged.

**Comment by Aritra8438** [comment]
@mathemancer, I have added the tests.

**Review by mathemancer — APPROVED** [review]
Fantastic, great work!

**Pull request merged**
