### PR TITLE
fix: Extracting columns that aren't orderable into a different tables results in incorrect data

### PR DESCRIPTION
**Pull request by ShailRT**
Fixes : [1490](https://github.com/centerofci/mathesar/issues/1490)

Resolves:

- This will assert an error whenever the column data type is one of the `non_orderable_type`

**Technical details**

I have used `InvalidGroupType` error class from `mathesar/db/records/exceptions.py` for raising exception

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ShailRT** [comment]
@rajatvijay @silentninja do I need to fix something?

**Comment by dmos62** [comment]
@ShailRT please add a test that reproduces the problem and demonstrates that it's fixed by your changes.

**Comment by ShailRT** [comment]
@dmos62 can you advise me on how to reproduce this error

**Comment by dmos62** [comment]
@ShailRT create a table with unorderable columns and extract those columns to a different table.

**Comment by ShailRT** [comment]
Screenshot from 2023-04-14 05-47-33
@dmos62 Sorry for taking so much time on this small issue I think this shows the changes but I think we also have to change the `_build_order_by_all_columns_clause` to resolve this failure in the test

**Comment by ShailRT** [comment]
it can be fixed by this 
```
def _build_order_by_all_columns_clause(relation):
    """
    To be used when we have failed to find any other ordering criteria,
    since ordering by all columns is inherently inefficient.

    Note the filtering out some columns, namely internal columns and non-orderable columns. See
    their docstrings for details.
    """
    order_result = []
    for col in relation.columns:
        try:
            if _is_col_orderable(col) and not _is_internal_column(col):
                order_result.append({'field': col, 'direction': 'asc'})
        except InvalidGroupType:
            continue
    return order_result
```
fix result 
Screenshot from 2023-04-14 06-35-50

**Comment by dmos62** [comment]
@ShailRT you'll want to submit a PR, so that we can properly review, have the checks and tests run, etc.

**Comment by rajatvijay** [comment]
@ShailRT I am closing this PR since there has been no activity for some time. If you wish to work on this again, feel free to open a new PR.

**Pull request closed without merging**
