### PR TITLE
Toasts styling

### PR DESCRIPTION
**Pull request by pavish**
Related to #2105 

**Technical details**
* This PR updates styling for the toast system, without changing any internals.
* The PR also adds/updates toast messages required for the demo video:
   - After extracting columns
   - After creating new link using link modal
   - After moving columns to existing table

**Details for reviewers**
* I've made the default backgrounds opaque for toasts, based on the figma spec, and I think we need to rethink that detail. For the purpose of getting this done on time for the demo video, I've removed opacity.
* I propose we make title mandatory for all toasts. For the time-being, it is still optional, but the updated layout assumes that the title would be present.
* We need to update all toasts in our app to ensure there's a compact title and actionable message. I'll create an issue for it.
* I need someone to review the copy of the text for the toasts needed for the demo. @seancolsen, @kgodey.

**Screenshots**

Screenshot 2022-12-23 at 1 49 02 AM

Screenshot 2022-12-23 at 1 50 12 AM

Screenshot 2022-12-23 at 1 50 45 AM

Errors:
Screenshot 2022-12-23 at 1 52 43 AM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@kgodey Can you review the copy of the text shown?

**Comment by kgodey** [comment]
- column extraction copy looks fine
- Moving column copy should be "Column X has been moved to table Y" or "Columns X, Y have been moved to table Z"
- Creating link is fine for now – eventually we should have different messages for the different types of links.

**Review by rajatvijay — APPROVED** [review]
LGTM - can merge once the comment from Kriti is resolved.

One minor design thing: The progress bar at the bottom is not properly visible. Ghislaine might need to look into some color contrasting there.

**Comment by pavish** [comment]
I'm merging this PR in, I'll make the mentioned review changes in my upcoming PR.

**Pull request merged**
