### PR TITLE
Add support for multiple databases

### LINKED ISSUE #310: User should be able to configure multiple databases in settings
**Problem**

Currently, the user can only configure one Mathesar database in the settings. They should be able to configure as many databases to connect to Mathesar as they want.

**Proposed solution**

The user should be able to configure multiple databases in the `.env` file.

**Additional context**

We might want to use `python-decouple`'s [built in CSV helper](https://github.com/henriquebastos/python-decouple/#built-in-csv-helper) for this.

Ideally, the user would be able to associate the database key with the connection information directly using a tuple or something like that.

### PR DESCRIPTION
**Pull request by eito-fis**
Fixes #310

Adds support for multiple mathesar tables databases.

**Technical details**
Updated `settings.py` to handle comma separated strings for the `MATHESAR_DATABASE_KEYS` and `MATHESAR_DATABASE_URLS` env variables.

Note, after merging this PR everyone will have to re-copy their `.env` files.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by eito-fis** [comment]
What should testing look like for this? / Do we need tests for this?

Given the small size of the change and the fact that everything is still running it seems fine as is to me - let me know if I should add some.

**Comment by kgodey** [comment]
I don't think we need tests for this, although you could add a second database to the testing environment to make sure that it works.

It would be ideal if the settings format was tuples of database keys and URLs so that you could see which key was associated with which URL without having to rely on order. It would also ensure that the number of keys was the same as the number of URLs. You can imagine that the current formatting would get confusing if you were adding 10 databases to Mathesar.

**Comment by eito-fis** [comment]
@kgodey Updated to use a tuple like format. Unfortunately can't use normal tuples since `decouple` naively splits on commas, so instead made tuples with `|` as the delimiter. Also, I didn't change the django db variables since the tuple format seems to imply multiple values, but if we want to keep things consistent I'm happy to convert that too.

**Review by kgodey — APPROVED** [review]
Looks good to me. Please add a comment somewhere in the code explaining why you're using a pipe instead of a comma before merging. It'll be useful to have the context in case someone wonders about it a year from now.

**Comment by kgodey** [comment]
I think it's fine to leave the Django DB format as is.

**Pull request merged**
