### PR TITLE
DB function to get rows with duplicate values

### LINKED ISSUE #515: DB function to get rows with duplicate values
## Problem

The ["Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns) adds a filter for duplicate values for a column, to assist users with resolving non-unique values when they want to set a unique constraint for a column.

## Proposed solution

We need to add a way to get columns with duplicate values in our `db` module. Please see #501 for relevant discussion about how to achieve this.

## Additional context

- API issue: #501
- Frontend issue: #499
- Design issue: #324 
- Design discussion: #436

### PR DESCRIPTION
**Pull request by eito-fis**
Fixes #515, #501

Implements a DB function to get rows with duplicate values.

**Technical details**
The columns to filter on are passed as part of the `filter` parameter, and should be of the form
```
{'field': '', 'op': 'get_duplicates', 'value': ['column', 'names', 'to', 'filter', 'on']}
```
Passing more than a single instance of a `get_duplicates` op or passing it nested in another condition will raise a `BadFilterFormat` error.

The column names to filter on are used to construct an additional `WHERE` statement, which is executed alongside all other parameters passed to `get_records`. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by eito-fis** [comment]
Note that I'm also marking this as closing #501 - since we're just adding an additional `filter` option the API shouldn't require any changes.

**Review by kgodey — CHANGES_REQUESTED** [review]
I tested this locally and it seems like it works well, although the query is a little slow. That's fine for now.

We should do some error checking on the API to make sure that the columns passed in are valid. Specifying `['Pizza']` in the column name (for a table that doesn't have that column) currently returns an unfiltered list of records instead of an error.

**Comment by eito-fis** [comment]
Updated to add extra handling for invalid column names and for `get_duplicates` appearing in a nested condition.

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
Looks great, thanks!

**Pull request merged**
