### PR TITLE
docs: fix install commands

### LINKED ISSUE #3224: install.py is not working after upgrading to latest version
## Description
I upgraded to latest version (from master) and when I try to run 
python db/install.py I get the following error:

```
(venv) [serafeim@imp-uat mathesar]$ python db/install.py
Traceback (most recent call last):
  File "/home/serafeim/mathesar/mathesar/db/install.py", line 1, in <module>
    from psycopg.errors import InsufficientPrivilege
  File "/home/serafeim/mathesar/venv/lib/python3.9/site-packages/psycopg/__init__.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.9/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/usr/local/lib/python3.9/re.py", line 124, in <module>
    import enum
  File "/usr/local/lib/python3.9/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/home/serafeim/mathesar/mathesar/db/types/__init__.py)
```

## Expected behavior
install.py should work fine

## To Reproduce
Fetch latest version and try running `python db/install.py`

## Environment
 - Centos 7
 - Python 3.9

## Additional context
Please notice that the instructions here are also wrong: https://docs.mathesar.org/installation/build-from-source/ 

They mention running python install.py but there's no install.py file.

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #3224

This fixes invalid commands for running `install.py` from the build from source section of the docs. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Anish9901** [comment]
@mathemancer this pr is ready for review but the CI pipline is breaking due to ModuleNotFound error.

**Comment by mathemancer** [comment]
@Anish9901 What happens if you use a newer version of mkdocs?

**Review by mathemancer — APPROVED** [review]
Looks good; let's wait for the pipeline to go through and merge it.

**Comment by mathemancer** [comment]
O

> @Anish9901 What happens if you use a newer version of mkdocs?

That brought other bugs, btw. So, I fixed the python version to 3.11.

**Pull request merged**
