### PR TITLE
Add docs for connecting mathesar to local db

### LINKED ISSUE #2571: Make Deployment Type 2 work with DBs on localhost

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #2571

Documentation about how to connect Mathesar to a Postgres DB running locally on a host machine (i.e. DB outside the docker container).

There doesn't seem to be an elegant approach we can take for connecting Mathesar to a host db without fiddling around with a bunch of internal Postgres files on the host system namely the `postgresql.conf` & `pg_hba.conf`. If someone really wants to connect Mathesar to their local db the steps are clearly documented in this PR.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by mathemancer — APPROVED** [review]
I think this looks good. Thank you!

**Comment by seancolsen** [comment]
I happened to notice that this new docs page is in in the guide but not in the guide's nav menu. @Anish9901 can you edit `docs/mkdocs.yml` and add a link to this new page somewhere within `nav`? @mathemancer It would be good to check for this when reviewing PRs too.

**Comment by Anish9901** [comment]
@seancolsen it was actually @mathemancer suggestion to not put the guide in the nav menu as it might confuse users and might lead them to not be able to install using the install script which is a requirement for following the steps suggested in this guide.

**Comment by seancolsen** [comment]
Oh sorry -- I should have read his comment before making mine. Interesting. Having a page in the guide which is not in the nav menu feels very weird to me. Like, if you navigate to that page, you should be able to use the nav menu to understand your current context within the rest of the documentation and to navigate back to other pages. Publishing it outside the nav turns the page into a sort of dead end. It also makes the page harder for reader to find.

Having read Brent's comment a few times, I still don't understand the reason for not putting this in the nav -- I think maybe because I don't understand the docs content well enough. @mathemancer could we address your concerns by placing some sort of disclaimer at the top of this page?

**Pull request merged**
