### PR TITLE
add cell tab in table inspector for showing cell content

### LINKED ISSUE #2342: Show cell content in table inspector Cell tab
## Current behavior

- The Table Page has a table inspector with tabs for "Table", "Column", and "Record".

    image

- The inspector on the Exploration Page also has a tab for "Cell" which shows the cell content.

    image

    This is nice for cells that have longer content

## Desired behavior

- The inspector on the Table Page has a "Cell" tab which behaves similarly to the "Cell" tab on the Exploration Page.

### PR DESCRIPTION
**Pull request by raunak-dev-edu**
Fixes #2342

This Pull request will add a cell tab in the table inspector in the table page that will show cell content similar to the inspector in Exploration Page.

**Screenshots**

Like this - 

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dmos62 — CHANGES_REQUESTED** [review]
Fix the lint and format check failures.

Also, you've based this on an abandoned PR and implemented the changes requested in that PR: https://github.com/centerofci/mathesar/pull/2385

This is the second PR you're basing off of someone else's work, without saying that. As I said on the other PR, that looks pretty bad.

**Comment by raunak-dev-edu** [comment]
> Please, fix the lint and format check failures.
> 
> Also, you've based this on an abandoned PR and implemented the changes requested in that PR: #2385
> 
> This is the second PR you're basing off of someone else's work, without saying that. As I said on the other PR, that looks pretty bad.

I'd like to apologize once again. I raised my PR after thoroughly reviewing #2385 and discovering that there had been no response to the suggested review. My intention was to help resolve the issue as quickly as possible. However, I realize that I made a mistake by not referencing the PRs and failing to comment on this matter when I submitted my own PR. I'm truly sorry for any confusion or inconvenience caused by my oversight.

**Comment by rajatvijay** [comment]
@raunak-dev-edu there are some failing link checks.

**Comment by rajatvijay** [comment]
@dmos62 I am going to start the review on this since the lint checks are now passing.

**Review by seancolsen — APPROVED** [review]
Thanks @raunak-dev-edu. I added a few commits to clean up some small things.

**Pull request merged**
