### PR TITLE
Restrict common data based on user permission

### LINKED ISSUE #2311: common_data should not contain content the user does not have access to
## Description
* Our templates render a `common_data` json that contains the following:
  * `current_db`
  * `current_schema`
  * `schemas`
  * `databases`
  * `tables`
  * `queries`
  * `abstract_types`
  * `live_demo_mode`

The `databases`, `schemas`, `tables`, and `queries` properties of this list have to be provided taking into account the user's permission levels. Currently, then contain everything.

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #2311 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by pavish — CHANGES_REQUESTED** [review]
@silentninja I have a few comments:

* When user has no access to databases, we have `databases: []` and `current_db: mathesar_tables`. In this case, `current_db` should be `null`.
* When `current_db` is `null`, the default redirection to the db page should not happen. The url should be the root url after logging in: `/`.


This is a question/suggestion for @kgodey. When user has no access to dbs, we are currently greeted with an error page saying `No databases found`. I think we can show a simple info box with a message saying 'You currently do not have access to any databases. Please contact your admin`. We can handle this in the users & permissions frontend PRs.

**Comment by kgodey** [comment]
@pavish If a user has access to only particular schemas, they should still see the DB page, but with only the schemas they have access to visible. They would still have `databases: []` in that case, I think.

The info box idea is fine if they have access to no databases or schemas.

**Comment by pavish** [comment]
@silentninja 

Based on Kriti's comment, I might have another requirement. Within common data,

> If a user has access to only particular schemas, they should still see the DB page, but with only the schemas they have access to visible
> They would still have databases: [] in that case, I think

if a user has access to atleast one schema from a database, that database should be included in this list. The frontend requires that inorder to show the DB page.

Note: This is only the list within common data which is used by the frontend to know which routes to show, and has nothing to do with roles specified in the users & permissions APIs.

**Comment by silentninja** [comment]
> if a user has access to at least one schema from a database, that database should be included in this list. The front end requires that in order to show the DB page.

This is making me slightly anxious. Isn't this like giving read access to the database object without any hierarchical read access to other schemas in the database? If that is true, would this be the case for other objects like Tables, and Schemas? For example, if I only have access to a Table, I can also read the Schema object to which the Table belongs.

**Comment by kgodey** [comment]
@silentninja How do you expect it to work?

**Comment by silentninja** [comment]
@pavish I made the requested changes, can you review it again?

**Comment by silentninja** [comment]
> Do you have a different proposal to make?

@kgodey Nothing that I can think of right now.

**Comment by pavish** [comment]
@silentninja 

When I login with a user with no access to databases or schemas, I get the following assertion error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 3.1.14
Python Version: 3.9.16
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 55, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"

Exception Type: AssertionError at /
Exception Value: .accepted_renderer not set on Response
```

**Comment by silentninja** [comment]
@pavish I fixed the error and was able to get the scenario running locally. Can you confirm if it is fixed?

Also, in case the user does not have any access to the database, we return a plain page with the message "'You currently do not have access to any databases. Please contact your admin". We would need to style this page, can you add that to the current PR

**Comment by pavish** [comment]
@silentninja 

> Also, in case the user does not have any access to the database, we return a plain page with the message "'You currently do not have access to any databases. Please contact your admin". We would need to style this page, can you add that to the current PR

Can you return the same index.html for this, with `databases: []`. I can handle this on the Svelte side of code. The user should still be able to access their profile even if they have no access to databases.

**Comment by silentninja** [comment]
> Can you return the same index.html for this, with `databases: []`. I can handle this on the Svelte side of code. The user should still be able to access their profile even if they have no access to databases.

Done!

**Comment by pavish** [comment]
@silentninja I'm getting the following error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/mathesar_tables/

Django Version: 3.1.14
Python Version: 3.9.16
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/mathesar/views.py", line 184, in schemas
    database = get_current_database(request, db_name)
  File "/code/mathesar/views.py", line 119, in get_current_database
    current_database = get_object_or_404(permitted_databases, name=db_name)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /mathesar_tables/
Exception Value: get() returned more than one Database -- it returned 2!
```

Note, I've run my local setup in live demo mode, so there's an additional DB here. I'm sure this problem will occur when running in live demo mode.

**Review by pavish — APPROVED** [review]
@silentninja Looks great! Thanks!

**Pull request merged**
