### PR TITLE
Search through tables in sidebar

### LINKED ISSUE #207: Searching through schemas & tables
We need to provide an option to search and filter schemas and tables on the frontend, based on the design spec.

Currently we fetch all schema and table data on the frontend, so the filtering can be done on the frontend, however we need to keep it easily extensible for when we will have to switch to filtering/searching by an API call later on.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #207 

### This PR:
* Adds search option to the left sidebar, to search through tables
* Components: TextInput

### Note:
This PR does not make API calls for filtering the tables. Currently, the schemas and their table names are fetched in a single API call upon load (preloaded), and it reloads when there is an import. Since we have all the data, it didn't make much sense to call the API for searching through them, instead it is handled on the frontend itself. The APIs will be essential when we have a search across the whole DB functionality.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@pavish do we fetch all schemas and tables even if the API has multiple pages of them?

**Comment by pavish** [comment]
@kgodey The current UX requires all the schemas to be fetched for the left pane, so we fetch them. (The table names are present in the schema response, and we use the same). This is something I've brought up before (also mentioned it on the Format of design spec discussion #279 today, and I think that we need to take into account the cases where the count is higher than 50, and how the UI would behave.

**Comment by kgodey** [comment]
@pavish per Matrix conversation, @ghislaineguerin will figure out a design for large numbers of tables/schemas in milestone 5. I figure we should go with your approach for now, and redo it/maybe use the API for search when we get to implementation of milestone 5. Thoughts?

**Comment by pavish** [comment]
@kgodey Sounds good to me

**Comment by kgodey** [comment]
I'll give this a day for @zackkrida and @dhruvkb to have a chance to review and review on Monday. @pavish I assume you're not blocked and you can branch off this branch for upcoming work if needed?

**Comment by pavish** [comment]
@kgodey My current branch is taken off this branch. It will not block any development work, but the frontend PRs being raised will be blocked, which I guess is okay.

**Review by zackkrida — APPROVED** [review]
Looks good. My only question is a minor stylistic one. 
Are the underlines on hover of tables necessary? It seems off to me, especially in the case below where the active table is hovered and the underline appears. It seems to imply some action will occur when clicked on, even though the table is already active.

CleanShot 2021-06-25 at 15 09 35@2x

**Comment by pavish** [comment]
@zackkrida I agree that they are not necessary. We have not started focusing on styling yet. As of now, we are only working on the layout and functional/behavioural aspects of the UI. In the meanwhile, @ghislaineguerin is working on a design system, color schemes etc.,

These styling issues will be covered when we pick that up.

**Review by dhruvkb — APPROVED** [review]
Looks good!

**Review by kgodey — APPROVED** [review]
Looks good!

**Pull request merged**
