### PR TITLE
Add hyperlinks to Record Pages within PK and FK cells

### PR DESCRIPTION
**Pull request by seancolsen**
This PR adds small icon-based hyperlinks to PK cells and FK cells which point to Record Page URLs.

## Demo

https://user-images.githubusercontent.com/42411/184432663-5a7497d8-0559-4572-9525-a8c4ca9ce6c2.mp4

## Notes

- The mockups within [the Record Selector specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/record-selector.md#mockup-of-cells-and-inputs) required the link to be _inside_ the FK pill. This PR puts the link _outside_ the pill. Notably, @kgodey originally [wanted the link outside the pill](https://github.com/centerofci/mathesar-wiki/pull/50#issuecomment-1201734366), so I think she'll like this design alteration. I ended up going with "outside-the-pill" because Kriti was right -- "inside" did feel a bit funky once I saw it in the page. The "inside" approach also made it difficult to achieve visual consistency with the link in the _PK_ cell, which I hadn't considered until working on this.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
The video looks good. I think it might make sense to left-align PK values and have the link right aligned to be consistent with FKs (so all values that are some sort of key have the same behavior, regardless of data type). That doesn't necessarily need to happen in this PR, though.

**Comment by seancolsen** [comment]
@kgodey 

> left-align PK values

That's easy to do. Here, let's see how it looks with GIF. _(Press the play at the top right.)_

Peek 2022-08-12 16-56

I'm not sure which I prefer, PK cells left aligned or PK cells right aligned @ghislaineguerin @pavish @rajatvijay do you have an opinion? I'll keep a commit locally with the change that left-aligns them and I'll push it if we decide to go with that.

**Comment by kgodey** [comment]
I do like that better. Also, I thought we had an issue somewhere to disable digit grouping separators by default for ID columns? I can't find it but I remember some sort of proposal about that from you, @seancolsen. I think that would be good to do in Cycle 3 or 4.

**Comment by seancolsen** [comment]
@kgodey I pushed 776fe0cf95ed5d5207c8dc7c8892448f3b44fd99 to left-align the values, and I created #1527 to track the small task of removing the grouping separators.

**Comment by kgodey** [comment]
Thanks @seancolsen. I dug up the proposal from you that I was thinking of and made a comment in #1527.

**Review by pavish — APPROVED** [review]

**Comment by pavish** [comment]
@seancolsen Feel free to merge this PR once the merge conflicts are resolved.

**Pull request merged**
