### PR TITLE
Made minor Padding Changes , to fix inconsistency for issue #2200

### LINKED ISSUE #2200: Implementing consistent padding for fixed width page header and content
### Problem
Fixed width pages, such as database and schema pages, have an inconsistency in padding between the header section and the content, resulting in misalignment of elements within those sections. 

### Proposed Solution
We need to implement a consistent padding that ensures proper alignment at the edge of the page. 

See example:
> image

_Originally posted by @ghislaineguerin in https://github.com/centerofci/mathesar/issues/2146#issuecomment-1369580831_

### PR DESCRIPTION
**Pull request by reachaadrika**
Fixes #2200 

This PR removes the inconsistency caused by padding and addresses the problem.

**Technical details**

Provided some extra padding .

**Screenshots**

image
image

## Checklist
 
- [ x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x ] My pull request targets the `develop` branch of the repository
- [ x] My commit messages follow [best practices][best_practices].
- [ x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
> Sure , I will update this and add a new container div with extra padding ? Right ?

Right, it should use the same variable.

**Comment by reachaadrika** [comment]
Yes @ghislaineguerin !

**Comment by reachaadrika** [comment]
Also this UI Lint test is failing , what changes are required to be made into the code , changes like spacing and all ?

**Comment by rajatvijay** [comment]
Hi @reachaadrika 

The formatting checks are failing. You can run the format script (`npm run format`) on your locally to see the exact places where the formatting is off. Alternatively, you can make sure your local setup for formatting as per the [docs](https://github.com/centerofci/mathesar/tree/develop/mathesar_ui#formatting)

**Comment by reachaadrika** [comment]
image
have a look @ghislaineguerin

**Comment by ghislaineguerin** [comment]
@reachaadrika Thanks. Can you push the updated code so that I can review?

**Comment by reachaadrika** [comment]
Also , I found one more inconsistency , as you can see this description is not aligned and looks a bit different , I tried to fix it but it not working 
image

**Comment by ghislaineguerin** [comment]
@reachaadrika Without seeing code it's hard to review. Can you push what you have so far?

**Comment by reachaadrika** [comment]
Hi I have pushed the updated code in a new PR

**Comment by rajatvijay** [comment]
>I have pushed my code , but  by mistake , many changes were committed too , how can I revert back these commits that I made ?

@reachaadrika while I do not understand completely what you mean here but if you have mistakenly pushed some extract changes here are your options: 

1. If there is a commit with just the non-required changes, you can [drop that commit ](https://stackoverflow.com/questions/1338728/how-do-i-delete-a-commit-from-a-branch). 
2. If the commit has required as well as non-required changes then you will have to revert them manually line by line. 

PS: I also see some checks failing, could you please take care of that too? Thanks!

**Comment by pavish** [comment]
I'm closing this PR since this page was modified and padding related issues were fixed as part of https://github.com/centerofci/mathesar/pull/2847

**Pull request closed without merging**
