### PR TITLE
Demo video 'must-haves', general improvements

### LINKED ISSUE #1925: Improve serialization & de-serialization of Data Explorer query instance
The PR https://github.com/centerofci/mathesar/pull/1850 introduces some changes to serialization & de-serialization of a query instance to and fro to a hash url param. [This review comment](https://github.com/centerofci/mathesar/pull/1850#discussion_r1020532971) on the PR needs to be handled.

> I would like this function to be re-written.
> 1. We should not parse this as TerseSummarization, we should have a new TerseQueryModel, which can contain summarization.
> 2. I would like to avoid using Mutable here (and preferably anywhere in the codebase). Use the types of properties directly to construct each property and return a single UnsavedQueryInstance at the end.

### LINKED ISSUE #2010: Able to add the data type when creating a column.

### LINKED ISSUE #2021: Use ModificationStatus component within the Table Page.
Use the ModificationStatus component to render the status UI within the actions pane on the Table Page.

### LINKED ISSUE #2113: Fix summarization when redirected from table page after grouping
## Description
* Group a table
* Notice a help message asking user to summarize
* Click on it and notice an error in Data Explorer
* The data sent from the table page is invalid. This seems to be a regression.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #2010 
Fixes #2113 
Fixes #2021 
Fixes #1925 
Related to #1812 
Related to #1800
Related to #2079

**This PR also contains the additional general changes:**
* Implements SelectionList component, which is used by the type selection dropdown
* Fixes ModificationStatus component bug to not show up twice when `requestStatus` changes without `hasChanges` set to `true`
* Removes Icon for Cancel button
* Fixes cell borders not showing up while loading
* Fixes header being cut-off in record page table widgets during scroll.
   - Still has the pre-existing issue of header control cell not remaining static, but it is minor enough to take up later. Will create an issue for this.

**Notable UX changes**
* Add column dropdown
   * The dropdown has a cancel button, which isn't present in figma. Having a cancel button is consistent with every other operation in Mathesar, and since I'm using the same component, I decided to have it here as well to avoid modifying the component.
   * The background color & padding of the list options during hover/selection is currently the same as the ones in Select menus throughout the product, which is different from figma. This should be updated as part of https://github.com/centerofci/mathesar/issues/2105, I see that there's a point that ensures `All form fields have consistent styles`, which should cover this.
   * The text says 'Add' instead of 'Create', since add seems more suitable for a new column. I can change this if required.
   * | Figma | Implemented |
      |---|---|
      |Screenshot 2022-12-20 at 9 17 39 AM|Screenshot 2022-12-20 at 9 17 02 AM|
* Icon for cancel button
   * The back icon does not accurately represent the button's behaviour, and it provides little value. I tried replacing it with a times (i.e and 'x' icon), but it didn't look visually great. Our figma designs did not use any icons for Cancel buttons, so I decided to remove them.
   * Having an icon only for the proceed button, makes the button more prominent, which is good.
   * This change reflects everywhere a Cancel button is present.
   * | Before this PR | After this PR |
      |---|---|
      |Screenshot 2022-12-20 at 9 28 46 AM| Screenshot 2022-12-20 at 9 28 54 AM|

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@kgodey I'd like your review on the 'Notable UX changes' mentioned in the description.

**Comment by kgodey** [comment]
UX changes seem fine to me, @pavish.

**Review by kgodey — APPROVED** [review]

**Review by seancolsen — CHANGES_REQUESTED** [review]
This is mostly looking great!

Changes requested:

- Setting the column type while creating a column is not working for me. Here's a demo:

    https://user-images.githubusercontent.com/42411/208680867-9d8cdb1e-ac49-477d-90a8-49868f317ad0.mp4

Comments;

- I pushed 1f2f383ef7b656c9177427bd174aa944053e5feb to utilize the `form.reset` function built into the form system. This simplifies the code a tiny bit.

- Also, in `NewColumnCell.svelte` I see that you're setting inputs to disabled when the form is processing. This is a pattern I'd like to employ throughout the app using the form system. I'd had this in mind for a while, so I just created #2132 to track that work.

- I only gave a cursory glace over the diff in `src/systems/data-explorer/urlSerializationUtils.ts` because that code is very unfamiliar to me and I don't quite understand what's going on here. I trust that it works well enough for now.

**Comment by pavish** [comment]
@seancolsen Thanks! This commit https://github.com/centerofci/mathesar/pull/2125/commits/c549086851c326c278ae924ed738705099faa64f should fix the issue you've reported. The bug existed for types which do not have default db types associated with them, and boolean was one among them. 

> I only gave a cursory glace over the diff in src/systems/data-explorer/urlSerializationUtils.ts because that code is very unfamiliar to me and I don't quite understand what's going on here. I trust that it works well enough for now.

You can test this by grouping columns on the table, and clicking the summarize button which redirects them to the Data Explorer.

**Review by seancolsen — APPROVED** [review]
Working great now :sunglasses:

**Pull request merged**
