### PR TITLE
Add cell tab to show cell content in table inspector

### LINKED ISSUE #2342: Show cell content in table inspector Cell tab
## Current behavior

- The Table Page has a table inspector with tabs for "Table", "Column", and "Record".

    image

- The inspector on the Exploration Page also has a tab for "Cell" which shows the cell content.

    image

    This is nice for cells that have longer content

## Desired behavior

- The inspector on the Table Page has a "Cell" tab which behaves similarly to the "Cell" tab on the Exploration Page.

### PR DESCRIPTION
**Pull request by SumeetHaryani**
Fixes  #2342 

**Technical details**

- Create `CellMode` component and update the ` TableInspector` component to support the cell tab
- Add `wrapConditionally` prop to wrap cell content

**Screenshots**

image
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by SumeetHaryani** [comment]
@seancolsen when for the `CellFabric` component `isIndependentOfSheet` prop value is kept as false. It truncates for long cell values and able to view id column content as well 
image
image
when the `isIndependentOfSheet` prop value is kept as true. 
image
image

**Comment by SumeetHaryani** [comment]
sorry about that @seancolsen, I was trying to ask do we need to show content for the id column content here as well?
if yes, what would be the correct approach since internally the truncation is been controlled by `multiLineTruncate` and `isIndependentOfSheet` props

**Comment by seancolsen** [comment]
@SumeetHaryani 

- We _do_ need to show the value for the id column.
- Values should get wrapped, not truncated.

Sorry but I don't have time to offer more detailed assistance on implementation

**Comment by SumeetHaryani** [comment]
> @SumeetHaryani
> 
> * We _do_ need to show the value for the id column.
> * Values should get wrapped, not truncated.
> 
> Sorry but I don't have time to offer more detailed assistance on implementation


@seancolsen This PR is ready for review

**Review by seancolsen — CHANGES_REQUESTED** [review]
Nice progress @SumeetHaryani 

- I'm a bit uneasy about adding a new prop to `CellFabric` as you've done with `wrapConditionally`. The `CellFabric` component is one of our most complex components because it composes many other components dynamically. Whenever we add a new prop to `CellFabric`, we need to make sure we add it to all the other components it composes too. I wouldn't expect that we'd need a new prop here since the Data Explorer is able to display the cell already as we want it to display. Did you try utilizing the `isIndependentOfSheet` prop? It seems like that's how the Data Explorer is accomplishing the wrapping. See code [here](https://github.com/centerofci/mathesar/blob/5590b4c6950258e68b2d1fc8a22f6f0f67add619/mathesar_ui/src/systems/data-explorer/exploration-inspector/CellTab.svelte#L41).

- The CI is failing because this PR contains some type errors. Can you fix these? You can check for these locally by running:

    ```
    docker exec -w /code/mathesar_ui mathesar_service npx svelte-check --incremental --tsconfig tsconfig.json --threshold error . 
    ```

**Comment by SumeetHaryani** [comment]
> Nice progress @SumeetHaryani
> 
> * I'm a bit uneasy about adding a new prop to `CellFabric` as you've done with `wrapConditionally`. The `CellFabric` component is one of our most complex components because it composes many other components dynamically. Whenever we add a new prop to `CellFabric`, we need to make sure we add it to all the other components it composes too. I wouldn't expect that we'd need a new prop here since the Data Explorer is able to display the cell already as we want it to display. Did you try utilizing the `isIndependentOfSheet` prop? It seems like that's how the Data Explorer is accomplishing the wrapping. See code [here](https://github.com/centerofci/mathesar/blob/5590b4c6950258e68b2d1fc8a22f6f0f67add619/mathesar_ui/src/systems/data-explorer/exploration-inspector/CellTab.svelte#L41).
> * The CI is failing because this PR contains some type errors. Can you fix these? You can check for these locally by running:
>   ```
>   docker exec -w /code/mathesar_ui mathesar_service npx svelte-check --incremental --tsconfig tsconfig.json --threshold error . 
>   ```

@seancolsen In the table view, we have an id column when `isIndependentOfSheet` is `true` we are not able to view the id column content and when `isIndependentOfSheet` is `false` we are able to view the cell content but it does not get wrapped that's why have added the prop to handle this. Let me know if there is a better approach to handle this...
I have fixed the type errors. Thanks for the command it helped... 
Do let me know, if any changes required
Refernce: https://github.com/centerofci/mathesar/pull/2385#issuecomment-1406959489

**Comment by SumeetHaryani** [comment]
@seancolsen any update here?

**Comment by kgodey** [comment]
@SumeetHaryani We're running behind on PR reviews since we're focused on our upcoming release. It may take up to a couple of weeks to review.

**Comment by pavish** [comment]
@SumeetHaryani 

> In the table view, we have an id column when `isIndependentOfSheet` is `true` we are not able to view the id column content and when `isIndependentOfSheet` is `false` we are able to view the cell content but it does not get wrapped that's why have added the prop to handle this. Let me know if there is a better approach to handle this

`isIndependentOfSheet` needs to be `false`, the purpose of this prop is for being able to render the CellFabric out of a cell.

As @seancolsen mentioned, it's not a good idea to have an additional prop `wrapConditionally`. The actual issue is that the id column, which is of `PrimaryKeyCell` type, does not wrap with `isIndependentOfSheet:false` when placed out of the context of a cell. The fix must be made with the css within the `PrimaryKeyCell.svelte` file, and not with the use of additional props.

I hope this provides enough direction for you to proceed. Let us know if you require further assistance.

**Comment by pavish** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
