### PR TITLE
Move cell selection to Newly created Record's first Non primary cell

### LINKED ISSUE #2348: Scroll sheet all the way down and select first non-pk cell when clicking the New Record button
## Steps to reproduce

1. Identify a table with lots of records, and load its Table Page from scratch.

1. Press "New Record" button.

1. Expect to see the empty record row

1. Instead, observe that the sheet has been scrolled down, but not all the way.

    image

    This is likely to confuse new users

1. Expect the active cell (and cell selection) to move to the cell within the new record and within the first column which is not a primary key. This way, I can start entering new data quickly.

1. Instead, observe that the active cell is still the first cell in the table.

    It's possible that fixing the cell selection problem may also fix the scrolling problem, which is why I've lumped these problems into the same ticket. But I'm not sure, so feel free to split this ticket into two during implementation if needed.

### PR DESCRIPTION
**Pull request by Sukshan**
Related to #2348 

### Overview

- Adding new record moves the cell selection to first non primary cell of the record

**Screenshots**

[Screencast from 19-02-23 03:39:56 AM IST.webm](https://user-images.githubusercontent.com/71199418/219902214-5812a458-cdee-4b50-879c-ace113aec1da.webm)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Sukshan** [comment]
@seancolsen even after moving the cell selection to the first cell of the new record did not fix the scrolling issue, i tried to figure out what is wrong with it but was unsuccessful.

**Comment by kgodey** [comment]
Thanks for the PR, @Sukshan. It will take us a few days to get to reviewing this, since the core team is focused on getting our initial release out.

**Comment by Sukshan** [comment]
👍 sure, will work on some other issue till then.

**Comment by Anish9901** [comment]
@Sukshan Can you please refactor your changes to make sure all the CI tests pass?

**Comment by seancolsen** [comment]
@Sukshan I pushed a commit which should fix the problem identified in CI. The code was not formatted correctly. See https://github.com/centerofci/mathesar/blob/master/mathesar_ui/README.md#formatting

I'm continuing to review this PR now.

**Review by seancolsen — CHANGES_REQUESTED** [review]
Thanks for this PR @Sukshan. Some comments:

- The ticket describes two problems: a selection problem and a scrolling problem. This PR only seems to attempt to address the selection problem. It's fine to address these problems one at a time, but we'll need to make sure we don't close the ticket and lose track of the remaining work. As such I've removed `Fixes #2348` from the PR description, adding `Related to #2348` instead. This way the ticket will not auto-close when the PR is merged.

- In the ticket I said:

    > It's possible that fixing the cell selection problem may also fix the scrolling problem

    I can see from this PR that fixing the cell selection problem does _not_ fix the scrolling problem. That's good to know!

- There are some TypeScript errors that we'll need to fix before merging.

- Also, there are two buttons two add a new record:

    image

    We should handle this cell selection modification for both of those buttons, ideally without duplicating much code.

**Comment by Sukshan** [comment]
Thanks for the detailed review sean, I will make the necessary changes

**Review by seancolsen — APPROVED** [review]
Looks good, @Sukshan I added 15f30b82266dc3f4c4e8e2b461b582a86fca9350 which gives that new method a slightly better name.

**Pull request merged**
