### PR TITLE
E2E test for renaming a table

### LINKED ISSUE #1124: Add E2E test for renaming a table
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "renaming a table" works as-expected. Here's a visual demo of what the test should do:

Peek 2022-03-02 16-44

## Tips

- Assert that the modal closes, that the tab title updates, and that the entry in the sidebar updates

### PR DESCRIPTION
**Pull request by A1O**
Fixes #1124

E2E test for renaming a table

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dmos62 — APPROVED** [review]
I approve the general code style. Didn't examine the actual UI interaction logic, I hope @seancolsen is ok with reviewing that.

Quick note. We don't use type annotations in Mathesar. The few `page: Page` littered here and there is fine, I'd say, but that's something to keep in mind.

**Comment by kgodey** [comment]
Re: type annotations, we had a conversation about (not) using them in E2E tests here: https://github.com/centerofci/mathesar/pull/1062#issuecomment-1049915758

I'm working on the Python style guide for our codebase now and I'd like to understand more about how type annotations are helpful while writing E2E tests. @seancolsen had some thoughts in the other PR, but if anyone writing E2E tests has more to add to that, let me know.

**Comment by kgodey** [comment]
We decided in https://github.com/centerofci/mathesar/pull/1062#issuecomment-1049915758 not to use type annotations for now, I think we should follow that for now. My question is unrelated to this specific PR.

**Comment by A1O** [comment]
I found an E2E test with type annotation and started to use it.
I going to remove type annotation which I have added to avoid misunderstandings in the future.

**Comment by seancolsen** [comment]
> I found an E2E test with type annotation and started to use it.

That's probably my fault. Sorry! I opened #1195 in an attempt to help mitigate that problem going forward.

**Comment by A1O** [comment]
Done. No type annotation.

**Review by seancolsen — APPROVED** [review]

**Pull request merged**
