### PR TITLE
Display options groundwork & config for boolean, number

### PR DESCRIPTION
**Pull request by pavish**
Related to: #257,  #258 

## This PR:
* implements groundwork for display options configuration
* detaches form validation from component layer dependency
* implements display options for Boolean Mathesar type
* implements display options for Number Mathesar type
* reorganizes type configuration components

### Boolean display options
Screenshot 2022-03-27 at 1 11 24 AM

## Number display options
Screenshot 2022-03-27 at 1 11 46 AM
* The formats listed here are as per conversations over the past week in the Matrix channels.

## Validation
* Encountered an UX issue:
   - The user enters an invalid value in one of the tabs, say in Display options tab.
   - The error message appears only below the input. We disable the Save button.
   - User switches the tab to Database options.
   - The Save button will still be disabled, but the user may not know where the error lies, since the error message lies within the Display options tab.
* This PR improvises a design to handle that:
* User enters invalid value in Display options tab:
  - Screenshot 2022-03-27 at 1 12 01 AM
  - Error indication is displayed in the input and also the tab header.
* User switches tab:
   - Screenshot 2022-03-27 at 1 12 12 AM
   - Tab header indicates some error is present in Display options

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- x ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
I'm stacking this over https://github.com/centerofci/mathesar/pull/1240, to avoid merge conflicts.

**Comment by seancolsen** [comment]
I'll review this, but I want to wait until we resolve #1243 first

**Comment by pavish** [comment]
@seancolsen This PR is mostly groundwork on display options. The whole number configuration is one file: `mathesar_ui/src/stores/abstract-types/type-configs/number.ts`.

I added both boolean and number display options in this PR, so that we can view the usage on the product. Even tests haven't been added yet and will be added as part of each individual data types issue.

If #1243 takes longer, I'd suggest merging this one. If we decide on something else, we can make that change in the Number type implementation issue.

**Review by seancolsen — APPROVED** [review]
This looks good. The validation stuff (and behavior with respect to the tabs) is very slick. Nice work!

**Pull request merged**
