### PR TITLE
Backend text filtering

### LINKED ISSUE #406: Implement filtering options for Text types.
## Problem
We need to ensure that records that include columns of all Text types support the following filters via API: 
- contains {x}
- is {x}
- is not {x}
- starts with {x}
- ends with {x}
- does not contain {x}
- does not start with {x}
- does not end with {x}
- is empty
- is not empty

This involves:
- Implementing the filters in the backend
- Updating the `/api/v0/databases/<id>/types/` endpoint to store available filters on this type
  - Filter information should include the number of parameters needing to be passed in (e.g. `contains` needs 1 parameter, `is empty` needs 0)

## Additional context
- We're using our fork of `sqlalchemy-filters` to provide filtering. See: https://github.com/centerofci/sqlalchemy-filters.
- This issue is blocked by implementation of Text types: 
  - #404 
  - #405 
  - #407
- #557 provides some context on storing filters.

### PR DESCRIPTION
**Pull request by dmos62**
Fixes #406

Depends on previous filtering PR: #837 

Introduces `StartsWith`, `EndsWith` and `Contains` predicates for text types. These predicates accept a `case_sensitive` setting (defaults to `True`).

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by silentninja** [comment]
Updated to the status to blocked, since it is blocked by #837

**Comment by dmos62** [comment]
Here's what the new entries in the `/filters` endpoint look like:

```
GET /api/v0/databases/1/filters/

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    ...,
    {
        "identifier": "or",
        "name": "Or",
        "position": "branch",
        "parameter_count": "multi",
        "ma_types": [
            "boolean",
            "datetime",
            "duration",
            "email",
            "money",
            "number",
            "text",
            "uri",
            "other"
        ],
        "settings": null
    },
    {
        "identifier": "starts_with",
        "name": "Starts with",
        "position": "leaf",
        "parameter_count": "single",
        "ma_types": [
            "email",
            "text",
            "uri"
        ],
        "settings": {
            "case_sensitive": {
                "default": true,
                "type": "bool"
            }
        }
    },
    {
        "identifier": "ends_with",
        "name": "Ends with",
        "position": "leaf",
        "parameter_count": "single",
        "ma_types": [
            "email",
            "text",
            "uri"
        ],
        "settings": {
            "case_sensitive": {
                "default": true,
                "type": "bool"
            }
        }
    },
    {
        "identifier": "contains",
        "name": "Contains",
        "position": "leaf",
        "parameter_count": "single",
        "ma_types": [
            "email",
            "text",
            "uri"
        ],
        "settings": {
            "case_sensitive": {
                "default": true,
                "type": "bool"
            }
        }
    }
```

Notice:
    - Every entry has a `settings` field; it can be null: I opted to always include it for consistency;
    - The new predicates `starts_with`, `ends_with` and `contains` declare that they accept a `case_sensitive` setting, that defaults to `true` and is a boolean.

The settings are provided like this:

```
{"starts_with": {"column": "col1", "parameter": "a start", "case_sensitive": false}}
```

The architecture around how we deal with predicate settings, like case-sensitivity in this case, is minimalistic and fluid at the moment since requirements aren't clear yet. We're currently working from simple cases to more complex ones, so I expect refinement to take place in future PRs when more interesting predicates are explored.

**Comment by kgodey** [comment]
@dmos62 I made this PR a draft so we don't accidentally merge it. I think it's fine for the `status` to be `review`.

**Comment by dmos62** [comment]
@kgodey [this last commit](https://github.com/centerofci/mathesar/pull/879/commits/94513e022ff73a42ea465baa00639da77310a0e7) makes internal nomenclature changes you requested: super type -> position, type -> id. It makes some other significant changes too; I forgot to commit before making other changes.

**Comment by dmos62** [comment]
> @kgodey [this last commit](https://github.com/centerofci/mathesar/pull/879/commits/94513e022ff73a42ea465baa00639da77310a0e7) makes internal nomenclature changes you requested: super type -> position, type -> id. It makes some other significant changes too; I forgot to commit before making other changes.

I reflected on this a bit and decided that introducing changes only to the last PR when they are relevant to a series of PRs is not a good idea. Next time, I'll commit to the oldest PR and merge the older PR into the newer PRs.

**Comment by kgodey** [comment]
> I reflected on this a bit and decided that introducing changes only to the last PR when they are relevant to a series of PRs is not a good idea. Next time, I'll commit to the oldest PR and merge the older PR into the newer PRs.

Agreed, I assumed it was because the other PR was based on a fork and this is a branch. I do think it's always better to make it on the older PR.

**Comment by kgodey** [comment]
@dmos62 Can we close this issue since it's pretty out of date?

**Pull request closed without merging**
