### PR TITLE
issue-1134 Insert newlines in TextAreaCell only via keyboard shortcut

### LINKED ISSUE #1134: Insert newlines in TextAreaCell only via keyboard shortcut
## Current behavior

(When column has Mathesar Type of "Text" and TextAreaCell is displayed)

- If the Text data type is configured without a field size restriction or with a higher limit, a textarea is displayed. Pressing `Enter` in edit mode on the textarea will insert a newline.

## Desired behavior

- Pressing `Enter` with any combination of the following modifier keys inserts a newline at the users cursor position:

    - `Ctrl`
    - `Alt`
    - `Meta` (aka "Cmd" on Mac OS)

- Pressing `Enter` (without any modifiers), or `Shift+Enter`, or `Shift` + any of the above modifiers + `Enter` saves the cell and transitions from edit mode to select mode.

## Additional context

- #1119

### PR DESCRIPTION
**Pull request by nk183**
Fixes #1134 

### 
**Technical details**

**What this pr does**
Pressing Enter with any combination of the following modifier keys inserts a newline at the users cursor position:

    Ctrl
    Alt
    Meta (aka "Cmd" on Mac OS)

**ToDo** 

Currently after inserting new line using keyboard,the textarea field focus losses 

**Screenshots**

https://user-images.githubusercontent.com/58779460/159457522-f33b5244-6a96-409b-bdf9-5ba9d5dc1936.mp4

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by nk183** [comment]
Hi @pavish  can you please help me with this 
The textarea losses it focus after insertion  of newline using shortcut keys 
I have applied focus on textarea Reference after dealing with key shortcuts.

**Comment by pavish** [comment]
@nk183 The changes required here are mostly on the `TextAreaCell` component and the `SteppedInputCell` components.

`Enter + (ctrl/shift/cmd)` controls would be dispatching Enter keydown events, which in this case also switches the mode from edit to select. This is the cause for the loss of focus.

I'm marking this PR as draft since it is still being worked upon.

**Comment by nk183** [comment]
hi @pavish it is working as required, but I think code can be made more clean can you please guide me.
I am working on making a `enterBehavior`  as a property can you tell how can I write [this](https://github.com/nk183/mathesar/blob/8d6a75f4cb0bcfe0adacfa6418631edd35817da8/mathesar_ui/src/components/cell/cell-types/common/SteppedInputCell.svelte#L39), this seems redundant.

**Review by pavish — CHANGES_REQUESTED** [review]
We had a discussion over one of our office hours over this PR, where we discussed an alternate approach. I've added it here to keep track.

@nk183 
1. Create an optional boolean prop in `TextArea` component which decides whether or not to handle _meta+enter_, _ctrl+enter_ and _alt+enter_. Eg., `export let addNewLineOnAllEnterKeyCombinations = false`.
1. Move the keydown event handler within `TextArea` and handle adding new line based on the above prop.
1. Fix all linting errors.

**Comment by nk183** [comment]
hi @pavish

**Comment by nk183** [comment]
hi @pavish I have addedthe required changed.

**Comment by pavish** [comment]
@nk183 Thank you for your work on this PR! The changes look good to me.

I've been holding off on merging this PR since there are considerable changes in related components in parallel PRs. I'll add commits to this PR to handle the changes and merge it in the upcoming week.

**Review by pavish — APPROVED** [review]

**Pull request merged**
