### PR TITLE
Improved fkey referenced row deletion error

### PR DESCRIPTION
**Pull request by mathemancer**
Related to #1813 

This enhances the error message produces when attempting to delete a record referenced by a foreign key.

**Technical details**

The HTTP status of this error is now `400`.

The new error raised also has details giving the Django ID of the constraint violated, and the relevant columns. Example:

```json
[
  {
    "code": 4212,
    "message": "Key (id)=(10) is still referenced from table \"Items\".",
    "field": null,
    "detail": {
      "constraint": 2,
      "constraint_columns": [12],
      "constraint_referent_columns": [19]
    }
  }
]
```

It may be that the front end would want to some how use the constraint info.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@pavish The only review requested from you is that the response has all info you'd want, in an acceptable format.

**Review by silentninja — APPROVED** [review]

**Comment by pavish** [comment]
@mathemancer It looks good. We can make use of the constraint id to identify the information needed. It'll still be great if the error message contained constraint_referent_table, since it already contains all the other essential details.

**Review by pavish — APPROVED** [review]

**Comment by mathemancer** [comment]
@pavish I marked it as "fixed" since it does make a much more human-friendly error message already. I consider the front end changes optional (but feel free to do them if you have time).

**Comment by mathemancer** [comment]
> @mathemancer It looks good. We can make use of the constraint id to identify the information needed. It'll still be great if the error message contained constraint_referent_table, since it already contains all the other essential details.

@pavish I added the referent table as requested: #1862

**Pull request merged**
