### PR TITLE
Sorting and Grouping

### LINKED ISSUE #343: Implement Grouping in the UI
## Problem
The user would want to group data when viewing a table.

## Proposed solution
We should implement these options per the [design spec](https://wiki.mathesar.org/design/specs/filter-sort-group)

### LINKED ISSUE #344: Implement Sorting in the UI
## Problem
The user would want to sort data when viewing a table.

## Proposed solution
We should implement these options per the [design spec](https://wiki.mathesar.org/design/specs/filter-sort-group)

### PR DESCRIPTION
**Pull request by pavish**
Fixes #343 
Fixes #344 

This PR:
* Adds sorting option to the spreadsheet
* Adds grouping option to the spreadsheet
* Adds table display properties pane, as per the UX

Note:
* The UI for grouping is different from the design spec, since the layout is changed to spreadsheet based layout. The styling for the group headers are not detailed in this PR.
* I would like @ghislaineguerin to take a look and use Mathesar after the PR is merged (hopefully, the client build would be ready and staging would be up soon), revisit the UX, and see if changes are required.
* Displayed group count would be improper due to https://github.com/centerofci/mathesar/issues/352

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
This looks good to me overall and seems to work well. Some of the styling looks clunky, but that was noted in the PR description and I assume we'll update it in future iterations.

A couple of behavioral changes that I'd like to see:
- If there are multiple sorts or groups applied, and I add a new sort/group to a column, I would expect that it would be the first sort/group applied, not the last. I'm not sure if I'm explaining this well, so let me know if it's unclear.
- It would be nice to be able to minimize/expand groups so that I only see the group header and count. We can make a separate issue for this if needed, I realize it wasn't in the design.

**Comment by pavish** [comment]
@kgodey 

I agree the styling is clunky. Our current UX prototypes and our UI focuses mostly on the functionality and layout, and we have not been giving importance to styling yet.

I think after 'Working with Schemas' milestone (which will have layout changes on the frontend), we can take some time to finalize the layout and everything that was developed till then. We could then focus on the styling and looks. 
@ghislaineguerin I would also love to see some colors by then. :)

Regarding the behavioural changes:
* I agree that it makes sense for the latest sorting to apply first. But for grouping, I think latest has to be last. Could we discuss on this further with the team?
  - Also, we could create a new issue for this, once we finalize on the behaviour. This is a minor change, making it a good first issue. So, we could assign this to new contributors.
* I structured the layout to support minimizing/expanding groups. It was on my mind during development, but I needed to come up with an approach for fetching data based on the group's state, which will take some time, so I didn't proceed with it. We can create a new issue for this. I can pick this up later.

**Comment by kgodey** [comment]
@pavish I talked to @ghislaineguerin about styling updates today, we were thinking that it made sense to pause work on designing functionality to work on styling after milestone 11 (user management) since at that point, all the major database pieces will be in place. That's just for design work, you can start implementing it sooner, of course.

I'll merge this issue and make separate ones for the two behavioral issues I mentioned. We can discuss the intended behavior in the relevant issue comments.

**Comment by kgodey** [comment]
@zackkrida I'd also value your retroactive review on this one if you have some time.

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
Issues relevant to discussion that were created:
- #473 
- #474 
- #475

**Pull request merged**
