### PR TITLE
Escape behavior has been altered in cells

### LINKED ISSUE #1116: Esc key should cancel edits instead of saving
## Steps to reproduce

1. Begin editing a text cell.
1. Modify the contents.
1. Press the Esc key.
1. Expect the cell to transition to select mode, restoring the value before you began making your edits.
1. Observe the cell to transition to select mode, saving the value you entered.

## Expected behavior
1. For stepped input columns (all string based columns, number etc.,) which contain an edit mode, "Esc" key in edit mode should revert the value to what is present in the DB and cancel unsaved edits.
1. For all other columns, "Esc" key would essentially do nothing since value change is based on different interactions.

## Additional context

- The current behavior was established in #1080.
- "Save of Esc" is consistent with AirTable.
- "Cancel on Esc" is consistent with LibreOffice and Google Sheets

### PR DESCRIPTION
**Pull request by chidam333**
Fixes #1116

**Escape behavior has been altered for 5 cells :**
**- number**
**- textarea**
**- textbox(email)**
**- uri**
**- money**

This time i have tested things properly and it doesn't break anything to my notice i would make required changes if it does 

**Technical details**

Altered File locations : /mathesar/mathesar_ui/src/components/cell-fabric/data-types/components/

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by chidam333** [comment]
@seancolsen package-lock.json shows some anomaly , please delete it if there is something wrong in there . Everything else is perfect

**Review by seancolsen — CHANGES_REQUESTED** [review]
Here are some issues with this PR:

1. You have variable names like `datafromdbcopyhelper`. To follow our [Front end code standards](https://wiki.mathesar.org/en/engineering/standards/frontend), that should be `dataFromDbCopyHelper`.

1. Names like `dataFromDbCopyHelper` and `dataFromDb`, though in lowerCamelCase, are still problematic though because they do a poor job at communicating intent. It's hard for me to tell what's going on just from reading the names alone.

1. You have duplicated almost the same code across five files. We should try to make this change in one place to avoid that duplication.

1. The PR should not include any changes to `package-lock.json`.

I recommend trying to make changes within `SteppedInputCell`.

**Comment by chidam333** [comment]
✌️ i will fix it soon !

**Comment by seancolsen** [comment]
@chidam333 are you still working on this? If we don't see any updates to this PR by then end of the month, I'll be closing it so that our PR queue stays up to date.

**Comment by chidam333** [comment]
I was off track for last month i will be back working on it soon will proly be done by this week.

**Pull request closed without merging**
