### PR TITLE
Stale demo db reset

### LINKED ISSUE #2223: Live demo server often shows "502 bad gateway" error
Refreshing sometimes fixes it, but not always.

### LINKED ISSUE #2225: Add script to reset DBs created during live demo

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #2225  and also fixes #2223

Adds an API endpoint to the demo view which would delete databases created during the live demo.

The API can also be called using the DRF API UI
```
POST /api/demo/v0/delete_stale_db/

It takes in optional parameter:
{
   "force": false, //force database deletion even if it is in use
   "max_days": 3 //delete database older than 3  days by default, changed based on requirements
 }
 ```

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@silentninja why does this need to be an API? Who is expected to call this API?

I would make it a Django management command instead and set up a cronjob in the Ansible repo to call it.

**Review by kgodey — CHANGES_REQUESTED** [review]
See comment in main thread.

**Comment by kgodey** [comment]
Also, how does this fix https://github.com/centerofci/mathesar/issues/2223?

**Comment by silentninja** [comment]
> I would make it a Django management command instead and set up a cronjob in the Ansible repo to call it.
My next PR would be adding that. I wanted to fix the issue for the time being and set up a cron in the upcoming issue

**Comment by kgodey** [comment]
@silentninja that doesn't answer my question about why this needs to be an API.

**Comment by silentninja** [comment]
> Also, how does this fix https://github.com/centerofci/mathesar/issues/2223?

@kgodey It's not a reflection bug, rather it is the reflection process itself. Instead of the database used in the request we loop through all the available databases when reflecting, which takes a lot of time and results in gunicorn timeout. 

An ideal solution would be to reflect just the database used in the request, but that would take some time to implement as our current reflection triggers don't have a reliable way to find out about the database that will be used

**Comment by silentninja** [comment]
> @silentninja that doesn't answer my question about why this needs to be an API.

I added an API as a convenience.

**Comment by kgodey** [comment]
I don't understand why it needs to be an API. we can SSH in and run a command on the command line as easily as making an API request. APIs should be for things that API clients (i.e. the frontend) need.

**Comment by silentninja** [comment]
Closing in favor of #2239

**Pull request closed without merging**
