### PR TITLE
Text type & basic Boolean type frontend implementation

### LINKED ISSUE #254: Frontend implementation for text data types
Blocked by #234 and #244. Details will be added once those issues are closer to completion.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #254 
Related to #257 
Related to #928 

**Features**
* Adds text type frontend support
  - Choosing db type based on field size limit
    - length: null, field size restricted -> VARCHAR
    - length < 255, field size restricted -> CHAR
    - field size un-restricted -> TEXT
  - Cell input & size changes based on dbType and length property
    - Input is textarea for TEXT
    - Input changes to textarea for VARCHAR when length > 255 and textbox otherwise
    - Input is textbox for CHAR
    - The issue description mentions:
      - > columns with large amounts of text should expand when selected
      - This is currently done based on dbtype and type_options.length
      - If content exceeds a line, it expands to two lines on selection
      - When content is edited, it opens up the textarea which is resizable
      - Note:
        - Implementation slightly varies from the Figma design
        - Expanding based on exact content length instead of type_options.length is tricky and we can consider that later
* Adds basic boolean type frontend support
  - Only supports checkbox for now

**Regressions**
* Null placeholder is no longer shown when in edit mode. This is a regression we need to handle in upcoming PRs, after we implement other types.

**Improvements/Changes**
* Cell value only gets saved when user is done editing. However, escape does not reset to old value like spreadsheets.
* Some naming improvements based on conventions.
* TextInput component is made leaner, events such as enter, esc etc., are removed and parent components check them using keydown.

**UX discussions required**
* New row now contains empty checkbox if one of the columns is a boolean column. We need a UX reconsideration for the new row placeholder.
* Interactions differ widely for each cell type, we need to analyze and hash out the interaction specs.

**Backend issues**
* Responses for CHAR columns with fixed length contains empty space to fill for the entire length. While this is expected behaviour of the DB, this results in bad UX.
* Changing types to boolean from text fails with a 500 error. This is because the request contains `type_options: null` while boolean type does not accept any type_options. However considering that type_options is a property of Column, null value should be accepted, and any other value should throw an error.
* I will create issues for these later.

**E2E tests**
* This PR does not contain any e2e tests. I will add them in upcoming PRs when the essential types are implemented. I expect more refactoring to take place as more types are implemented and it would be better to write solid tests once the component structure suits all requirements.

**Video**
<a href="https://www.loom.com/share/ec2d03b57aa043c4a226774322dbf877">
    <p>Text type and basic boolean type frontend implementation - Watch Video</p>
    
  </a>

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
I watched the video, it looks great @pavish. Nice work, it's nice to see this functionality coming together.

> New row now contains empty checkbox if one of the columns is a boolean column. We need a UX reconsideration for the new row placeholder.

We're supposed to be using indeterminate state checkboxes for `NULL` value booleans. See the [NULL value spec](https://wiki.mathesar.org/en/design/specs/specs-null-values). We should only be showing empty checkboxes for `FALSE` values.

**Review by kgodey — APPROVED** [review]
Approved from the backend side. Perhaps we need to change the codeowners for `mathesar/tests/integration/` to be frontend?

**Comment by pavish** [comment]
@kgodey 

> We're supposed to be using indeterminate state checkboxes for NULL value booleans. See the [NULL value spec](https://wiki.mathesar.org/en/design/specs/specs-null-values). We should only be showing empty checkboxes for FALSE values.

We currently do this for existing and newly created records. It can be seen in the video. The style of indeterminate checkboxes is pretty similar to checked state, we can update that in the upcoming boolean type PR.

The new record placeholder however is very different, as it is not an actual record. The false state checkbox and empty cells in the placeholder are because the value is `undefined` instead of `null` If we set NULL values for all columns in the placeholder, the client will send `null` for the columns while creating the row and override the default value which needs to be set on the db.

This requires some UX rethought and it's the reason I've mentioned it on the UX discussions required section.

> Approved from the backend side. Perhaps we need to change the codeowners for mathesar/tests/integration/ to be frontend?

Yes, I think we should do that.

**Review by seancolsen — APPROVED** [review]

**Comment by seancolsen** [comment]
I've looked over this and tested it out. Mostly everything is working great! Exciting to see these new features!

I have jotted down some additional comments, critique, and questions. Tomorrow I'll flesh them out into tickets for further discussion and action.

**Comment by seancolsen** [comment]
Here are the tickets/PRs I created in lieu of a review:

- [x] #1111
- [ ] #1112
- [ ] #1113
- [ ] #1114
- [ ] #1115
- [ ] #1116

**Pull request merged**
