### PR TITLE
fix: Context menu updates for foreign key columns/cells

### LINKED ISSUE #2350: Navigate to linked table via cell context menu
## Current behavior

- We have this context menu on all cells.

    image

## Desired behavior

- When opened via a foreign key cell (as I've done in the above screenshot)...

    - (A) The "Go To Linked Record" functions the same, but is instead labeled as:

        > Open `Patricia Anderson`

        The icon is `iconRecord`

    - (B) The menu contains an additional entry labeled like this:

        > Open **Patrons** Table

        The icon is `iconTable`

- The (B) menu entry is also present when the context menu is opened via a foreign key column's header cell.

@kgodey Are these UX changes okay with you? If so, we can un-draft this ticket and mark it as "help wanted" and "good first issue".

### PR DESCRIPTION
**Pull request by himanshuc3**
Fixes #2350 

**Technical details**

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by seancolsen — CHANGES_REQUESTED** [review]
This is what I'm seeing

image

- Please remove all the "log" related code, both in JS and HTML.

- Don't use `<span class="fk-identifier">`. Instead, use `<LinkedRecord>` and `<Identifier>` (for the record name and table name respectively).

- Show the actual table name, not `as`

- Use the text "Open" for both links (not "Go To")

**Comment by himanshuc3** [comment]
apologies @seancolsen It is still in draft mode. I switched it's status.

**Comment by himanshuc3** [comment]
> This is what I'm seeing
> 
> image
> 
> * Please remove all the "log" related code, both in JS and HTML.
> * Don't use `<span class="fk-identifier">`. Instead, use `<LinkedRecord>` and `<Identifier>` (for the record name and table name respectively).
> * Show the actual table name, not `as`
> * Use the text "Open" for both links (not "Go To")

fixed the comments.

**Comment by himanshuc3** [comment]
Ready for review @seancolsen 
Need to verify on the following:
- Dev testing on table with multiple foreign keys (in progress)
- Icons for added context menu fields.

**Comment by himanshuc3** [comment]
@seancolsen Any updates on the pr review?
I know your bandwidth might not be available but hopefully this review shouldn't be time consuming.

**Comment by seancolsen** [comment]
I'll get to this sometime this week, @himanshuc3

**Comment by rajatvijay** [comment]
@himanshuc3 what is the status of the changes requested?

**Comment by pavish** [comment]
@himanshuc3 This PR has been open for a while without any progress/communication. I'm going to close this. Please feel free to open another PR if you're still working on this.

**Pull request closed without merging**
