### PR TITLE
Use compiled type strings in types endpoint

### LINKED ISSUE #932: DB Types in column.valid_target_types are not in sync with the types returned in database types endpoint
## Description
* `valid_target_types` property of column returns "DOUBLE PRECISION"
   - Endpoint: /api/v0/tables/14/columns/
* Types endpoint returns mathesar types where Number has the db type "DOUBLE_PRECISION"
   - http://localhost:8000/api/v0/databases/1/types/
   - Mathesar type: Number

Note that "DOUBLE PRECISION" and "DOUBLE_PRECISION" differ from each other.

## Expected behavior
Both endpoints should return values with same spelling.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #932 

This modifies the `db.types.base.get_db_type_name` to use the compiled type string instead of `__visit_name__`.  The effect in the API is that now all types reported by the types endpoint have the name they actually have in the DB (according to SQLAlchemy).

**Technical details**

This means that the function in question will not return type parameters (this is desired where it's currently called).

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dmos62 — CHANGES_REQUESTED** [review]
It seems that the change has broken a number of tests.

**Comment by kgodey** [comment]
@mathemancer I don't remember why we used `__visit_name__` either, feel free to change it.

**Comment by mathemancer** [comment]
Okay, should be ready for review.  @pavish if you have time, it'd be good to make sure that this doesn't break anything for the front end (it shouldn't unless you were counting on the underscore being there for some reason).

**Comment by pavish** [comment]
@mathemancer This doesn't break anything on the frontend in the current master.

This bug introduced an issue in one of raised draft PRs #926, where the types from column.valid_target_types and the types endpoint are compared. That issue should be resolved once this is merged.

**Pull request merged**
