### PR TITLE
Record editing

### LINKED ISSUE #195: Implement record editing
**Problem**

The user should be able to edit existing records in a table.

**Proposed solution**

We should support this in the frontend.

**Additional context**

Record editing will use `PATCH` requests to `/api/v0/records/`

Blocked by design work in #192.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #195 

**This PR handles:**
* record editing
* traversing through cells
* save status indicator

**Checklist**
- [x] Select cells on click
- [x] Edit cells on double click
- [x] Send request to save records
- [x] Implement manual refresh button
- [x] Do not allow editing primary keys
- [x] Show common saving/error indication on top
- [x] Show row indication when records are saved
- [x] Implement traversing table using arrow keys
- [x] Implement scroll based on active cell
- [x] Handle enter and esc keys for entering and escaping edit mode

**Demo**
<a href="https://www.loom.com/share/b8c85d0d322d4604b1b8156c8210f58a">
    <p>Mathesar - Record editing - Watch Video</p>
    
  </a>

**Not handled in this PR (Separate issues will be created)**
* Error messages for individual cells.
  - The PATCH endpoint for row updates returns a 500 when an invalid value for a cell is sent. The ideal response should be an error message, with the values for the column that caused the error.
* Usage of home, end, ctrl+tab keys etc., Basic usage using arrows, tab, enter, esc has been implemented. Advanced usage will be implemented as a separate issue.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by ghislaineguerin — COMMENTED** [review]
Record editing looks good to me. We should have different styling for the non-editable column. We can address that as part of the UI revamp.

**Review by ghislaineguerin — APPROVED** [review]

**Review by mathemancer — APPROVED** [review]
No apparent problems, great work!

I'll leave it for you to merge in case you want others to look at it first.

**Comment by pavish** [comment]
@kgodey @zackkrida @dhruvkb @mr-gabe49 Please feel free to review this PR. I'll go ahead and merge this and take up comments, if any, in a separate PR.

**Comment by mr-gabe49** [comment]
Hey @pavish, I have two question regarding record editing:
1. When escaping while editing a record, wouldn't users expect the new edited information to be undone? Similar to other spreadsheet applications like Excel. I ask this because I used Excel extensively this summer, and it was a true blessing when I could escape a record without changes being applied. 
2. If I start editing a record and I decide to leave the record as it originally was, the whole row would still turn green. Should the row be green as if it was updated even though no actual editing took place?

**Comment by pavish** [comment]
@mr-gabe49 
> When escaping while editing a record, wouldn't users expect the new edited information to be undone? Similar to other spreadsheet applications like Excel. I ask this because I used Excel extensively this summer, and it was a true blessing when I could escape a record without changes being applied.

We have not defined the behaviour of keys yet. For the time being, I've followed tools such as Google sheets and airtable, which do not reset values to previous state on esc. It seemed more reasonable compared to excel's behaviour. We can discuss on this further. @kgodey @ghislaineguerin 

> If I start editing a record and I decide to leave the record as it originally was, the whole row would still turn green. Should the row be green as if it was updated even though no actual editing took place?

The row only changes color when a request is sent to the server. Here the row is updated twice. First when the values were changed, and then when they were reverted back. Editing did take place, and it would be essential to denote that.

**Pull request merged**
