### PR TITLE
Have CI pytest task stop after first failed test

### PR DESCRIPTION
**Pull request by dmos62**
Right now, when Github CI is running our test suite and one of the tests fails, the CI will continue to run the remaining tests, which can take a long time, and we'll only know that a test failed after the CI task finishes.

This PR adds `--exitfirst` to our CI's pytest call, so that if a test fails, pytest stops immediately, thus shortening the CI task runtime and giving us feedback sooner.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by silentninja — CHANGES_REQUESTED** [review]
I don't know how useful this would be. There is also a scenario where multiple test cases could fail and we would have to run the test suite again to find the failing test. If the failing test is at the bottom of the list, this solution would make the feedback time longer than our current feedback time.

Is there a reason why you created this PR?

**Comment by dmos62** [comment]
The specific situation that inspired this was a bug that was only reproducing itself in the CI, but not locally. I had to wait a long time for the CI to tell me if it failed (when it could have done so much faster, if `--exitfirst` was enabled), and I had to do it multiple times. I.e. iteration was very slow. Also, sometimes I don't run the full test suite on my machine before pushing, and am later surprised that the CI test run fails: I would like this feedback loop to be shorter.

I don't see a downside to having CI's test run fail early, because we don't really use the CI test run for debugging, but rather as a safeguard. If I have the CI failing, I might look at its log to tell me what kind of failure that is, but then I'll use my local environment for actual debugging, which is an order of magnitude faster than our CI runner.

@kgodey can you arbitrage?

**Comment by kgodey** [comment]
It sounds like this solves a problem for @dmos62 but @silentninja, you're objecting to this because it _might_ cause other problems. Since this is a one line change, it seems like it's worth trying. It can be easily reverted if it causes more problems than it solves.

**Review by silentninja — APPROVED** [review]

**Comment by silentninja** [comment]
> I don't see a downside to having CI's test run fail early, because we don't really use the CI test run for debugging, but rather as a safeguard.

Okay, this sounds reasonable. I am on the same page with this too. The only concern I have is that it would make the feedback longer in case of multiple test case failures, especially with external contributors. But for now, it shouldn't be a problem.

**Pull request merged**
