### PR TITLE
Server default setting and getting improvements

### LINKED ISSUE #681: Unknown server_default settings silently deleted
## Description

When the column-type-altering function doesn't understand a `server_default` value for a column (the DB-level default setting), it silently removes / deletes that default when altering the column type.  This has the potential to lose metadata about a column that we'd be unable to recover.  Further, there would be no warning to the user in this case.

## Expected behavior

If we try to alter a column's type, and cannot deal with the `server_default` setting, we should refuse, or at least throw a warning where the user can see it.

## To Reproduce

Change the type of any column with a dynamic default (e.g., change a `DATE` column with default `NOW()` to `VARCHAR`), and note that the default has disappeared on the DB (this will be invisible in the API as noted in the description above).

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

### LINKED ISSUE #682: Some `server_default` constants are not handled
## Description

Currently, we should be able to handle any constant `server_default` setting.  This is not happening, since any cast applied to a server default results in our `db.columns.operations.select.get_column_default` function deciding that the default is dynamic (and that it can't be handled).  In particular, there are entire types where the `server_default` value is always stored as a `CAST` of a different type.

## Expected behavior

We should be able to set and get `server_defaults` whenever they're constant.

## To Reproduce

Set a `server_default` for a column of type `CHAR`, watch it disappear.

## Additional context

Handling server-level defaults is quite painful.  The options are to either
- retrieve a string of the SQL that describes the default, or
- retrieve a `pg_node_tree` (an internal representation of a partially-compiled SQL statement; this is how PostgreSQL actually stores the default internally)

One option (that I currently prefer) is to retrieve the SQL string (note this is actually a decompiled `pg_node_tree`), break it into an Abstract Syntax Tree _in python_ using https://github.com/lelit/pglast, use that to determine whether the default is constant or dynamic, determine its value, and use that value for the representation in the API.

The reason to do this in python rather than using the `pg_node_tree` directly from the DB is to get the AST in a more python-friendly form.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #682 
Fixes #681 

This changes the way we handle server defaults so that we
- correctly handle more of the constant values, and 
- avoid silently passing over dynamic values, instead raising a warning and returning the default-defining string when reading.
- refuse to alter a column type if it has a dynamic default value, since we can't currently do that properly.

**Technical details**

We actually don't attempt to specifically identify constant default settings anymore.  Rather, we identify known dynamic default settings which we can't properly handle, and treat them differently.  Unfortunately, the identification of these dynamic defaults depends on the node types in the Abstract Syntax Tree given for the expression using the `pglast` package.  The only good documentation of what those node types are is in a pair of C header files that the `pglast` project uses:
- https://github.com/pganalyze/libpg_query/blob/13-latest/src/postgres/include/nodes/parsenodes.h , and
- https://github.com/pganalyze/libpg_query/blob/13-latest/src/postgres/include/nodes/primnodes.h

I was only able to find two tags that are guaranteed to appear in any dynamic default setting for a column.  It's possible more exist.  These would need to be added to the `db.columns.operations.select._is_default_expr_dynamic` function when found.

**Screenshots**

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by eito-fis — COMMENTED** [review]
Overall looks good to me! One question - do we have a test for the behavior in  #681?

**Review by kgodey — APPROVED** [review]
@mathemancer This looks good to me. Could you put the technical details you put in the PR somewhere in a code comment or README file so that we have it with the repo?

I'll leave it to you to merge after you've added the documentation and addressed @eito-fis's comment about potentially adding a test.

**Comment by mathemancer** [comment]
> Overall looks good to me! One question - do we have a test for the behavior in #681?

Actually, the tests I put for that don't go up to the API layer; good catch.  I'll actually change the behavior a bit so the API layer shows the actual SQL string for the dynamic default, rather than pulling one of the values.

**Comment by mathemancer** [comment]
> Could you put the technical details you put in the PR somewhere in a code comment or README file so that we have it with the repo?

I added the details to a code comment, since that will be more visible to whoever is working on the relevant bits of code.

**Pull request merged**
