### PR TITLE
Boolean DB type casting extension

### LINKED ISSUE #387: Handle `BOOLEAN` data type in the backend
This issue is to ensure that Mathesar can handle the Postgres `BOOLEAN` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `BOOLEAN` if it's possible to do so.
- Automatic type inference during file import suggests `BOOLEAN` when it makes sense to do so. 

Most of this is already implemented, this issue is to review the current implementation, ensure it works, and see if we can make improvements to it.

**Additional Context** 
- See PR #368 for code that calculates which types are allowed for a column.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #387 

This adds some strings that can be cast to boolean:
- yes -> true
- no -> false
- y -> true
- n -> false
- on -> true
- off -> false

**Technical details**

Note that this does _not_ restrict columns to have only two values for inferring boolean.  So, a column with '0', '1', 'true', 'TRUE', 'yes', 'off', ... would be inferred to be of boolean DB type.  This seems like the best compromise to make at the moment.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by silentninja — COMMENTED** [review]
Looks good to me!

**Review by silentninja — APPROVED** [review]

**Review by kgodey — APPROVED** [review]

**Comment by silentninja** [comment]
@mathemancer I am able to cast string values('on', 'y') using the default cast, `SELECT 'on'::bool'` works, any reason why you didn't go for that?. I approved thinking that was not possible

**Comment by mathemancer** [comment]
@silentninja It is possible for all strings we _do_ want to handle.  To control things a bit, I wanted to set aside separate "approved" strings (to avoid, e.g., `'of' -> false`).  For numbers, we need the custom behavior since the ways and types of numbers cast to booleans are a bit confusing in their default state.  I'm open to changing the behavior if we want later, but I think the current setup is the best compromise with the current constraints.

**Comment by silentninja** [comment]
Makes sense, seems extensible too.

**Pull request merged**
