### PR TITLE
Fix DisplayOptions Serializer to validate display options when updating a column

### PR DESCRIPTION
**Pull request by silentninja**
Related to #1228

When a column is partially updated with an invalid display option, it does not get validated and the request succeeds due to weird behaviour with the DRF serializer which treats nested data as a partial update too, but we completely replace the display options object when saving it, so we end up with a scenario where a required field could be missing. So when the same object is requested by the API, the serializer throws up an error when looking up for the required field in the display options JSON object. This PR fixes it by validating display options during a partial update

## Technical Details
During a partial update of a parent serializer, drf calls the nested serializer with `partial` flag even if we haven't explicitly specified it. We consider update to display options as a full update but since DRF takes a partial flag from the parent serializer, the nested display options serializer gets treated as a partial update,  so the serializer becomes valid even if a required field is missing. A mixin was used to fix the behaviour for the individual display options serializer but it wasn't applied to the mapping serializer. This PR adds the mixin that fixes the behaviour of the DRF serializer to the mapping serializer. 

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@silentninja 

>  I am assuming you would be sending empty object even if the column type has the required display options

I do not understand this. While patching a column, I'd send an empty object if the user has not set any display options even if the column has display options associated with it. See [Kriti's comment](https://github.com/centerofci/mathesar/issues/1276#issuecomment-1094989622) here.

**Comment by silentninja** [comment]
> Also the sample requests mentioned in https://github.com/centerofci/mathesar/issues/1228 contain values for all the required fields.

Sorry got confused with issue #1276 scenario 2, please ignore that message. But this PR should solve the invalid state, so now it has to be `None` or a valid object at the time of validation. I have added a comment to the issue on how to deal with empty object.

**Review by mathemancer — CHANGES_REQUESTED** [review]
While I do think this change is needed, and the test looks good, I don't understand how this PR fixes #1228 . Can you add some explanation about that to the description for posterity?

**Comment by silentninja** [comment]
@mathemancer #1228 happens due to a bugs that can lead to invalid data being saved, this PR fixes one of the bugs that can cause the error. I updated the description to mention it is related to #1228 rather being a complete fix. I have also updated the description to mention the cause of the issue and how this PR aims to solve it.

**Review by mathemancer — APPROVED** [review]
Okay, thanks for the extra explanation.

**Pull request merged**
