### PR TITLE
Add Mathesar DevCon data set

### LINKED ISSUE #2070: Event Planning Data Set
## Problem

We don't have an example data set for our live demo that shows how one can use Mathesar to schedule and plan in time.

## Proposed solution

We'd like to simulate a data set representing a conference (maybe the "Mathesar DevCon" or the like). The conference should take place over a weekend (Friday, Saturday, Sunday). The conference should have speakers who give talks in rooms in some fashion. We'd also like to have 'tracks' describing sequentially scheduled talks (perhaps in different rooms) on some topic.

Example explorations: "First day speakers", "Room A schedule", "everyone talking during time B"

Tables (tentative):
- Speakers
  - id
  - Last Name
  - First Name
  - Bio
- Rooms
  - id
  - Room Number
  - Capacity
- Topics
  - id
  - Name
- Tracks
  - id
  - Name
- Days (just convenience)
  - id
  - Name (First Day, Second Day, Third Day)
  - Date (actual Date)
- Talks
  - id
  - Date (fkey)
  - Time
  - Room (fkey)
  - Title
  - Speaker (fkey)
  - Topic (fkey)
  - Track (fkey)
- Attendees
  - id
  - Last Name
  - First Name
  - Email

If we get this far, we could consider expanding. Also, this table setup should be considered rough, and the implementer is welcome to change/improve it. The goals are explorations like those mentioned above.

## Additional context

See the [Weekly meeting notes](https://wiki.mathesar.org/en/meeting-notes/2022-11/2022-11-17-weekly) where we discussed example data.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #2070 
Related to #1906 

This adds a data set representing a conference. Note that I didn't bother to add attendees yet, since we don't have any plan for integrating them into the rest of the set, so it didn't seem worth the trouble. I'm open to being convinced otherwise.

The use of this would be more of a back end for displaying information about the conference _to_ attendees. 

**Technical details**

This also sets up a custom summary so names show up as "First Last" when used in a summary.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@kgodey As before, you can load this by starting a fresh live demo by logging into your local mathesar in a private window.

I did a custom summary, but no explorations are in this PR (those will  be the next PR).

**Comment by mathemancer** [comment]
Moved assignment to @Anish9901 since he's going to take care of changes on this.

**Review by kgodey — CHANGES_REQUESTED** [review]
Looks a lot better. Two changes needed:
- Please anonymize the bios of the speakers that were based on the core team. e.g. Emily Johnson's bio is the same as mine and includes my previous jobs. Sarah Smith's bio actually refers to her as "Ghislaine" in a later sentence.
- Can we make the default ordering of the rows in the talks column based on talk date? This is so that we can get a mix of user and developer talks in the first few talks – right now, it's all developer focused talks followed by all user focused talks.

**Comment by kgodey** [comment]
I updated all the email domains to `example` email addresses so we don't accidentally expose real emails.

**Review by kgodey — APPROVED** [review]

**Review by kgodey — APPROVED** [review]

**Comment by kgodey** [comment]
Good work @mathemancer and @Anish9901!

**Pull request merged**
