### PR TITLE
Record deletion

### LINKED ISSUE #196: Implement record deletion
**Problem**

The user should be able to delete existing records in a table.

**Proposed solution**

We should support this in the frontend.

**Additional context**

Record deletion will use `DELETE` requests to `/api/v0/records/`

Blocked by design work in #194.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #196 

This PR:
* Handles record deletion from UI
* New component: Checkbox

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Looks pretty good as an initial implementation. I have a few thoughts on behavior refinements and improvements:

- There should be some kind of UI lock while a deletion is in progress. Currently many operations can be performed during a delete, which could be problematic in the future once row editing, creating, etc. are avaliable
  - The delete button should be disabled while a delete operation is in progress. If I throttle my network to a slow connection, I'm able to press the delete button while a deletion is in-progress, which sends the same `DELETE` requests again.
  - Currently, I can change sort order while a large (I tried 20 and 100 rows) delete is in progress. This removes the red background from the rows being deleted and still performs the sort.
- Improvements to bulk deletion would be welcome:
  - `shift` click on a checkbox when a checkbox is already selected to select a range of checkboxes (this is quite fun to implement too, from a state management logic perspective)
  - "Delete all" would be nice but would likely require more UI
- Destructive actions like delete should probably have a confirmation prompt to the user, or an 'undo' feature. If some sort of undo/redo global state controls are added to the application this can wait until that implementation, otherwise I'd think a conformation dialog or the delete text changing to something like "confirm" and requiring a 2nd click would be ideal

**Comment by pavish** [comment]
Hey @zackkrida. I love your thorough reviews! Thank you!

* I agree with locking of some operations when a deletion/edit/add is in progress. I was planning on handling it along with showing saving status once I complete editing and get to adding a row, since it will be required for all these operations. This way, it will be easier to structure common code once all related functionalities are in order. I will add this comment in issue https://github.com/centerofci/mathesar/issues/197 to keep track.
* Shift click and arrow keys for selection would be nice. We have milestones for [Bulk Operations](https://github.com/centerofci/mathesar/milestones/9) and [Spreadsheet-like editing](https://github.com/centerofci/mathesar/milestones/10). I was hoping to handle it there.
* We have a milestone to implement [Undo and Redo](https://github.com/centerofci/mathesar/milestone/25) feature
* I will update the UI with confirmation of deletion and error message (ie. save status), with the add row issue, as mentioned in point 1.

**Comment by kgodey** [comment]
@pavish are you planning to make any changes to this PR or should I go ahead and review now?

Could you also make issues for shift click and arrow selection (and anything else bulk-operation related) in the appropriate milestones so that we don't forget about them?

**Comment by pavish** [comment]
@kgodey I'm not making any more changes in this PR. I will create the issues in the appropriate milestones.

**Review by kgodey — APPROVED** [review]
Looks great. @zackkrida already covered the feedback I have and it's going to be addressed, so I have nothing to add here. I like how snappy/responsive it is. :)

**Pull request merged**
