### PR TITLE
Optionally accept foreign key constraint to use when moving column 

### LINKED ISSUE #1491: Let the user choose the foreign key based on which to move the column to a different table
## Problem
 In cases where there are multiple foreign keys connecting the two tables, we need to be clear about which foreign key will be used when a column is moved between the tables.

## Proposed solution
The client should be able to choose the foreign key when moving a column to a different table

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #1491

Allows the `/tables/<id>/move_columns/` API to optionally accept a parameter `relation_fk_constraint` whose value is the `id` of foreign key constraint which links the table that contains the columns and the table to which the columns have to be moved 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by mathemancer — CHANGES_REQUESTED** [review]
Do we have a use-case for this at the moment? If not, I'd rather wait to do this work entirely:
- It further bakes in an assumption about Foreign keys being the way we specify joins that may not be valid by the time this PR is relevant
- It complicates the machinery, and I don't think that cost is acceptable without an actual use-case.

Am I missing something? I looked at the relevant issue and some surrounding context, but didn't see why this is relevant now.

As far as the code goes, I think it's fine, but I don't like the assumptions it bakes into the codebase w.r.t. foreign keys being the only way to specify the join.

**Comment by silentninja** [comment]
> It further bakes in an assumption about Foreign keys being the way we specify joins that may not be valid by the time this PR is relevant

Can you elaborate? We are using foreign keys to join the table when moving the columns right now.


> It complicates the machinery, and I don't think that cost is acceptable without an actual use-case.

This feature is helpful 
- When there is a leftover column that should be normalized and a new foreign  column is introduced to the normalized table
- when there is a table that is created manually and has two foreign key columns that are pointing to the same table and needs a column that has to be moved

For example:
Items
 - Id: Int
 - Last Name: String
 - Reviewer: Int Foreign key to Author Table
 - Author: Int Foreign key to Author Table

By default the `Reviewer` column would be used by the actual column I would want to use would be the `Author` column

**Comment by silentninja** [comment]
There is confusion about the priority of the issue this PR fixes. There were two issues related to Data Modeling tagged under the milestone `Live Demo` 

- [Add support for specifying the foreign key column name created when splitting the table #1434](https://github.com/centerofci/mathesar/issues/1434) which has the milestone `Live Demo`
- The above issue #1878 had live demo as its milestone(but the changes history in the issue was stating a change from Live demo to Post release) before I changed it to Post release.

**Review by seancolsen — COMMENTED** [review]
I have not tested this, but here are some initial thoughts:

- I agree with @mathemancer that this is not a priority right now. We'll need to do front end work before this feature can offer any benefit to users, and I have a _lot_ of other front end work that feels higher-priority than this.
- When we _do_ implement this feature, I'd rather implement it as a breaking change, removing the `target_table` parameter from the API and using the `relation_fk_constraint` parameter instead. That feels like a more intuitive API to me.

In terms of project management, I'm not sure where that leaves us. Maybe @silentninja keeps this branch locally and resurrects it in a few months hoping that it doesn't accumulate too many merge conflicts?

**Comment by kgodey** [comment]
> In terms of project management, I'm not sure where that leaves us. Maybe @silentninja keeps this branch locally and resurrects it in a few months hoping that it doesn't accumulate too many merge conflicts?

I think we should close the PR, we can always use it as a reference later when the related issue is deemed a priority. I'm not sure keeping the branch locally will have much value since the PR is pretty small, but that's up to @silentninja.

**Pull request closed without merging**
