### PR TITLE
Style database and schema home pages

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Related to #473 
Fixes https://github.com/centerofci/mathesar/issues/1231

This PR updates styling for:
- Database Page
- List of Schemas
- Schema Page
- List of Entities
- Replace Logo
- Base is Restored to 14px

Notes:

### Schema Level Navigational Items
In the schema page, navigational items need to be styled differently than buttons. I have changed the label "New Exploration" to data explorer, but this might not be valid until we allow users to open Data Explorer without saving.
image

### Description Placeholder for Schema List
A description placeholder has been added to represent style. This should be replaced with the actual schema description when ready.

### CODE REVIEW

**Review by pavish — COMMENTED** [review]
@ghislaineguerin The changes look good to me.

@kgodey I noticed that the logo was missing, and added a commit https://github.com/centerofci/mathesar/pull/1575/commits/74a0584c77fef3903fb08973f672d4656de9f2bf to address it. This also handles proxying static files for vite dev server, from django during development mode. It would be great if you or someone from the backend team took a look once before merging this.

**Comment by pavish** [comment]
Okay, I just noticed that this breaks Jest. I'll fix this and then mark the PR ready for review. I'm converting this to draft for now.

**Review by kgodey — APPROVED** [review]
Looks fine, @pavish. I made the comment a bit clearer. The linter failed, so I'm reassigning back to you to take a look and merge.

**Review by pavish — APPROVED** [review]
I added a commit https://github.com/centerofci/mathesar/pull/1575/commits/6526da1fb5beea34c2893b8ad143b64f71aa4fec which fixes Jest from breaking. I'm going to go ahead and merge this PR in. @seancolsen @rajatvijay Feel free to review this commit post merge.

**Pull request merged**
