### PR TITLE
add truncate component in Record Selector table cells

### LINKED ISSUE #2345: Use Truncate component in Record Selector table cells
## Current behavior

- We have a `Truncate` component that we use in some places when we might not have enough space to show some text. It shows the full text on hover. For example, here it is in action in the column header cell

    image

- On the Table Page, when the value in a data cell is too long, we truncate it, but we don't use the `Truncate` component. That means that users don't get the popover behavior which shows the full value.

    image

    Whether or not users _should_ see the popover on table cells is debatable. We have #2342 to show the entire cell content within the table inspector, so I don't think we need a popover here.

- _However_ in the Record Selector we're also rendering table cells, but our needs are a bit different. Here we don't have a table inspector. Also, we don't let the user resize columns. So we do have a compelling need to show some sort of popover for truncated text, otherwise the user may have no other means of distinguishing records that appear to be duplicates from the first portion of their cell content.

    Currently, we have a rather crude mechanism for displaying popover text -- we put it into the `title` attribute.

    image

    We have some [logic](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/systems/record-selector/RecordSelectorDataCell.svelte#L14L38) which shows the title tooltip only when the text is sufficiently long.

- Further, the table widget in the Record Page also renders table cells and doesn't have a table inspector. Here, I think it would be nice to at least experiment with showing the popover.

## Desired behavior

- We should use the `Truncate` component for table cells.

- On the Table Page, we should pass a prop down to all the `Truncate` components, setting `passthrough={true}`

- Within the Record Selector, and on the Record Page, we should keep `passthrough={false}` (as it is by default), producing table cells which show popover content when the values are truncated.

### PR DESCRIPTION
**Pull request by raunak-dev-edu**
Fixes #2345

This pull request will add the feature of truncate components in table cells.
Like this way-

**Screenshots**

Hovering over a cell (column 3 and row 28), it displays the popover full cell contents-
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@rajatvijay There's already another open PR for the same issue which I'm reviewing: https://github.com/centerofci/mathesar/pull/2687. We should try to keep these PRs under the same reviewer.

**Comment by seancolsen** [comment]
@pavish I'm re-assigning this to you since you've already begun reviewing the other PR for the same issue.

**Comment by dmos62** [comment]
Seems like a copy-paste of a suggestion in [this comment](https://github.com/centerofci/mathesar/pull/2687#discussion_r1149864314) by @pavish on another PR. It doesn't look good when you don't even mention that. Also, that comment raised concerns that this PR did address.

**Review by dmos62 — CHANGES_REQUESTED** [review]
Make sure that at least the concerns expressed in [the comment you copied this from](https://github.com/centerofci/mathesar/pull/2687#discussion_r1149864314) are addressed.

**Comment by raunak-dev-edu** [comment]
I'm very sorry, @dmos62. Before submitting my PR, I thoroughly reviewed the issue and PR #2687. However, even after more than a week, there was no response to the comment in https://github.com/centerofci/mathesar/pull/2687#discussion_r1149864314. Therefore, I proceeded to raise my own PR, following the review request. I sincerely apologize for not mentioning this when I submitted my PR.

**Comment by rajatvijay** [comment]
@raunak-dev-edu I am closing this PR since there has been no activity in the last 45 days. Feel free to open a new one

**Pull request closed without merging**
